/* Generated by Yosys 0.43+22 (git sha1 118b2829d, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */

(* hdlname = "blink" *)
(* top =  1  *)
(* src = "/home/user/openCologne/1.Blinky--ILA-Test/example_dut/blink/src/blink.v:3.1-44.10" *)
module blink(clk, led);
  (* src = "/home/user/openCologne/1.Blinky--ILA-Test/example_dut/blink/src/blink.v:34.2-41.5" *)
  wire [24:0] _0_;
  (* src = "/home/user/openCologne/1.Blinky--ILA-Test/example_dut/blink/src/blink.v:39.15-39.29" *)
  wire [24:0] _1_;
  (* src = "/home/user/openCologne/1.Blinky--ILA-Test/example_dut/blink/src/blink.v:36.7-36.11" *)
  wire _2_;
  wire [24:0] _3_;
  wire _4_;
  (* src = "/home/user/openCologne/1.Blinky--ILA-Test/example_dut/blink/src/blink.v:4.14-4.17" *)
  input clk;
  wire clk;
  (* src = "/home/user/openCologne/1.Blinky--ILA-Test/example_dut/blink/src/blink.v:16.30-16.34" *)
  wire clk0;
  (* src = "/home/user/openCologne/1.Blinky--ILA-Test/example_dut/blink/src/blink.v:16.15-16.21" *)
  wire clk180;
  (* src = "/home/user/openCologne/1.Blinky--ILA-Test/example_dut/blink/src/blink.v:16.7-16.13" *)
  wire clk270;
  (* src = "/home/user/openCologne/1.Blinky--ILA-Test/example_dut/blink/src/blink.v:16.23-16.28" *)
  wire clk90;
  (* src = "/home/user/openCologne/1.Blinky--ILA-Test/example_dut/blink/src/blink.v:15.12-15.19" *)
  reg [24:0] counter;
  (* src = "/home/user/openCologne/1.Blinky--ILA-Test/example_dut/blink/src/blink.v:7.15-7.18" *)
  output led;
  wire led;
  (* src = "/home/user/openCologne/1.Blinky--ILA-Test/example_dut/blink/src/blink.v:10.7-10.10" *)
  wire rst;
  (* src = "/home/user/openCologne/1.Blinky--ILA-Test/example_dut/blink/src/blink.v:17.26-17.38" *)
  wire usr_pll_lock;
  (* src = "/home/user/openCologne/1.Blinky--ILA-Test/example_dut/blink/src/blink.v:17.7-17.24" *)
  wire usr_pll_lock_stdy;
  (* src = "/home/user/openCologne/1.Blinky--ILA-Test/example_dut/blink/src/blink.v:16.36-16.47" *)
  wire usr_ref_out;
  assign _1_ = counter + (* src = "/home/user/openCologne/1.Blinky--ILA-Test/example_dut/blink/src/blink.v:39.15-39.29" *) 1'h1;
  assign _2_ = ! (* src = "/home/user/openCologne/1.Blinky--ILA-Test/example_dut/blink/src/blink.v:36.7-36.11" *) rst;
  (* src = "/home/user/openCologne/1.Blinky--ILA-Test/example_dut/blink/src/blink.v:34.2-41.5" *)
  always @(posedge clk0)
    counter <= _3_;
  assign _3_ = rst ? (* full_case = 32'd1 *) (* src = "/home/user/openCologne/1.Blinky--ILA-Test/example_dut/blink/src/blink.v:36.7-36.11|/home/user/openCologne/1.Blinky--ILA-Test/example_dut/blink/src/blink.v:36.3-40.6" *) _1_ : 25'h0000000;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/openCologne/1.Blinky--ILA-Test/example_dut/blink/src/blink.v:26.4-30.3" *)
  CC_PLL #(
    .CI_FILTER_CONST(32'sd2),
    .CP_FILTER_CONST(32'sd4),
    .LOW_JITTER(32'sd1),
    .OUT_CLK("20"),
    .PERF_MD("SPEED"),
    .REF_CLK("10.0")
  ) pll_inst (
    .CLK0(clk0),
    .CLK180(clk180),
    .CLK270(clk270),
    .CLK90(clk90),
    .CLK_FEEDBACK(1'h0),
    .CLK_REF(clk),
    .CLK_REF_OUT(usr_ref_out),
    .USR_CLK_REF(1'h0),
    .USR_LOCKED_STDY_RST(1'h0),
    .USR_PLL_LOCKED(usr_pll_lock),
    .USR_PLL_LOCKED_STDY(usr_pll_lock_stdy)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/openCologne/1.Blinky--ILA-Test/example_dut/blink/src/blink.v:11.14-13.2" *)
  CC_USR_RSTN usr_rstn_inst (
    .USR_RSTN(rst)
  );
  assign led = counter[24];
  assign _4_ = _2_;
  assign _0_ = _3_;
endmodule
