// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "Vopl3__Syms.h"
#include "Vopl3.h"
#include "Vopl3___024unit.h"
#include "Vopl3_mem_multi_bank__D1_DB12_O2_N2.h"
#include "Vopl3_mem_multi_bank__D8_DB16_N2.h"
#include "Vopl3_mem_simple_dual_port_async_read__pi13.h"
#include "Vopl3_mem_simple_dual_port_async_read__pi8.h"
#include "Vopl3_mem_simple_dual_port_async_read__pi7.h"
#include "Vopl3_mem_simple_dual_port_async_read__pi6.h"
#include "Vopl3_mem_simple_dual_port_async_read__pi4.h"
#include "Vopl3_mem_simple_dual_port_async_read__pi3.h"
#include "Vopl3_mem_simple_dual_port__pi12.h"
#include "Vopl3_mem_simple_dual_port__pi5.h"



// FUNCTIONS
Vopl3__Syms::Vopl3__Syms(Vopl3* topp, const char* namep)
    // Setup locals
    : __Vm_namep(namep)
    , __Vm_didInit(false)
    // Setup submodule names
    , TOP__opl3__DOT__channels__DOT__ch_abcd_cnt_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank(Verilated::catName(topp->name(), "opl3.channels.ch_abcd_cnt_mem.bankgen[0].genblk1.mem_bank"))
    , TOP__opl3__DOT__channels__DOT__ch_abcd_cnt_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank(Verilated::catName(topp->name(), "opl3.channels.ch_abcd_cnt_mem.bankgen[1].genblk1.mem_bank"))
    , TOP__opl3__DOT__channels__DOT__control_operators__DOT__am_vib_egt_ksr_mult_mem(Verilated::catName(topp->name(), "opl3.channels.control_operators.am_vib_egt_ksr_mult_mem"))
    , TOP__opl3__DOT__channels__DOT__control_operators__DOT__am_vib_egt_ksr_mult_mem__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank(Verilated::catName(topp->name(), "opl3.channels.control_operators.am_vib_egt_ksr_mult_mem.bankgen[0].genblk1.mem_bank"))
    , TOP__opl3__DOT__channels__DOT__control_operators__DOT__am_vib_egt_ksr_mult_mem__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank(Verilated::catName(topp->name(), "opl3.channels.control_operators.am_vib_egt_ksr_mult_mem.bankgen[1].genblk1.mem_bank"))
    , TOP__opl3__DOT__channels__DOT__control_operators__DOT__ar_dr_mem(Verilated::catName(topp->name(), "opl3.channels.control_operators.ar_dr_mem"))
    , TOP__opl3__DOT__channels__DOT__control_operators__DOT__ar_dr_mem__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank(Verilated::catName(topp->name(), "opl3.channels.control_operators.ar_dr_mem.bankgen[0].genblk1.mem_bank"))
    , TOP__opl3__DOT__channels__DOT__control_operators__DOT__ar_dr_mem__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank(Verilated::catName(topp->name(), "opl3.channels.control_operators.ar_dr_mem.bankgen[1].genblk1.mem_bank"))
    , TOP__opl3__DOT__channels__DOT__control_operators__DOT__fnum_low_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank(Verilated::catName(topp->name(), "opl3.channels.control_operators.fnum_low_mem.bankgen[0].genblk1.mem_bank"))
    , TOP__opl3__DOT__channels__DOT__control_operators__DOT__fnum_low_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank(Verilated::catName(topp->name(), "opl3.channels.control_operators.fnum_low_mem.bankgen[1].genblk1.mem_bank"))
    , TOP__opl3__DOT__channels__DOT__control_operators__DOT__kon_block_fnum_high_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank(Verilated::catName(topp->name(), "opl3.channels.control_operators.kon_block_fnum_high_mem.bankgen[0].genblk1.mem_bank"))
    , TOP__opl3__DOT__channels__DOT__control_operators__DOT__kon_block_fnum_high_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank(Verilated::catName(topp->name(), "opl3.channels.control_operators.kon_block_fnum_high_mem.bankgen[1].genblk1.mem_bank"))
    , TOP__opl3__DOT__channels__DOT__control_operators__DOT__ksl_tl_mem(Verilated::catName(topp->name(), "opl3.channels.control_operators.ksl_tl_mem"))
    , TOP__opl3__DOT__channels__DOT__control_operators__DOT__ksl_tl_mem__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank(Verilated::catName(topp->name(), "opl3.channels.control_operators.ksl_tl_mem.bankgen[0].genblk1.mem_bank"))
    , TOP__opl3__DOT__channels__DOT__control_operators__DOT__ksl_tl_mem__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank(Verilated::catName(topp->name(), "opl3.channels.control_operators.ksl_tl_mem.bankgen[1].genblk1.mem_bank"))
    , TOP__opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__env_int_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank(Verilated::catName(topp->name(), "opl3.channels.control_operators.operator.envelope_generator.env_int_mem.bankgen[0].genblk1.mem_bank"))
    , TOP__opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__env_int_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank(Verilated::catName(topp->name(), "opl3.channels.control_operators.operator.envelope_generator.env_int_mem.bankgen[1].genblk1.mem_bank"))
    , TOP__opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__state_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank(Verilated::catName(topp->name(), "opl3.channels.control_operators.operator.envelope_generator.state_mem.bankgen[0].genblk1.mem_bank"))
    , TOP__opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__state_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank(Verilated::catName(topp->name(), "opl3.channels.control_operators.operator.envelope_generator.state_mem.bankgen[1].genblk1.mem_bank"))
    , TOP__opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__feedback_mem__DOT__bankgen__BRA__0__KET____DOT__genblk2__DOT__mem_bank(Verilated::catName(topp->name(), "opl3.channels.control_operators.operator.feedback_mem.bankgen[0].genblk2.mem_bank"))
    , TOP__opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__feedback_mem__DOT__bankgen__BRA__1__KET____DOT__genblk2__DOT__mem_bank(Verilated::catName(topp->name(), "opl3.channels.control_operators.operator.feedback_mem.bankgen[1].genblk2.mem_bank"))
    , TOP__opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__final_phase_msb_mem(Verilated::catName(topp->name(), "opl3.channels.control_operators.operator.phase_generator.final_phase_msb_mem"))
    , TOP__opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__is_odd_period_msb_mem(Verilated::catName(topp->name(), "opl3.channels.control_operators.operator.phase_generator.is_odd_period_msb_mem"))
    , TOP__opl3__DOT__channels__DOT__control_operators__DOT__sl_rr_mem(Verilated::catName(topp->name(), "opl3.channels.control_operators.sl_rr_mem"))
    , TOP__opl3__DOT__channels__DOT__control_operators__DOT__sl_rr_mem__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank(Verilated::catName(topp->name(), "opl3.channels.control_operators.sl_rr_mem.bankgen[0].genblk1.mem_bank"))
    , TOP__opl3__DOT__channels__DOT__control_operators__DOT__sl_rr_mem__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank(Verilated::catName(topp->name(), "opl3.channels.control_operators.sl_rr_mem.bankgen[1].genblk1.mem_bank"))
    , TOP__opl3__DOT__channels__DOT__control_operators__DOT__ws_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank(Verilated::catName(topp->name(), "opl3.channels.control_operators.ws_mem.bankgen[0].genblk1.mem_bank"))
    , TOP__opl3__DOT__channels__DOT__control_operators__DOT__ws_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank(Verilated::catName(topp->name(), "opl3.channels.control_operators.ws_mem.bankgen[1].genblk1.mem_bank"))
    , TOP__opl3__DOT__channels__DOT__operator_out_mem__DOT__bankgen__BRA__0__KET____DOT__genblk2__DOT__mem_bank(Verilated::catName(topp->name(), "opl3.channels.operator_out_mem.bankgen[0].genblk2.mem_bank"))
    , TOP__opl3__DOT__channels__DOT__operator_out_mem__DOT__bankgen__BRA__1__KET____DOT__genblk2__DOT__mem_bank(Verilated::catName(topp->name(), "opl3.channels.operator_out_mem.bankgen[1].genblk2.mem_bank"))
{
    // Pointer to top level
    TOPp = topp;
    // Setup each module's pointers to their submodules
    TOPp->__PVT__opl3__DOT__channels__DOT__ch_abcd_cnt_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank = &TOP__opl3__DOT__channels__DOT__ch_abcd_cnt_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank;
    TOPp->__PVT__opl3__DOT__channels__DOT__ch_abcd_cnt_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank = &TOP__opl3__DOT__channels__DOT__ch_abcd_cnt_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank;
    TOPp->__PVT__opl3__DOT__channels__DOT__control_operators__DOT__am_vib_egt_ksr_mult_mem = &TOP__opl3__DOT__channels__DOT__control_operators__DOT__am_vib_egt_ksr_mult_mem;
    TOPp->__PVT__opl3__DOT__channels__DOT__control_operators__DOT__am_vib_egt_ksr_mult_mem->__PVT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank = &TOP__opl3__DOT__channels__DOT__control_operators__DOT__am_vib_egt_ksr_mult_mem__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank;
    TOPp->__PVT__opl3__DOT__channels__DOT__control_operators__DOT__am_vib_egt_ksr_mult_mem->__PVT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank = &TOP__opl3__DOT__channels__DOT__control_operators__DOT__am_vib_egt_ksr_mult_mem__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank;
    TOPp->__PVT__opl3__DOT__channels__DOT__control_operators__DOT__ar_dr_mem = &TOP__opl3__DOT__channels__DOT__control_operators__DOT__ar_dr_mem;
    TOPp->__PVT__opl3__DOT__channels__DOT__control_operators__DOT__ar_dr_mem->__PVT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank = &TOP__opl3__DOT__channels__DOT__control_operators__DOT__ar_dr_mem__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank;
    TOPp->__PVT__opl3__DOT__channels__DOT__control_operators__DOT__ar_dr_mem->__PVT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank = &TOP__opl3__DOT__channels__DOT__control_operators__DOT__ar_dr_mem__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank;
    TOPp->__PVT__opl3__DOT__channels__DOT__control_operators__DOT__fnum_low_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank = &TOP__opl3__DOT__channels__DOT__control_operators__DOT__fnum_low_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank;
    TOPp->__PVT__opl3__DOT__channels__DOT__control_operators__DOT__fnum_low_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank = &TOP__opl3__DOT__channels__DOT__control_operators__DOT__fnum_low_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank;
    TOPp->__PVT__opl3__DOT__channels__DOT__control_operators__DOT__kon_block_fnum_high_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank = &TOP__opl3__DOT__channels__DOT__control_operators__DOT__kon_block_fnum_high_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank;
    TOPp->__PVT__opl3__DOT__channels__DOT__control_operators__DOT__kon_block_fnum_high_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank = &TOP__opl3__DOT__channels__DOT__control_operators__DOT__kon_block_fnum_high_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank;
    TOPp->__PVT__opl3__DOT__channels__DOT__control_operators__DOT__ksl_tl_mem = &TOP__opl3__DOT__channels__DOT__control_operators__DOT__ksl_tl_mem;
    TOPp->__PVT__opl3__DOT__channels__DOT__control_operators__DOT__ksl_tl_mem->__PVT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank = &TOP__opl3__DOT__channels__DOT__control_operators__DOT__ksl_tl_mem__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank;
    TOPp->__PVT__opl3__DOT__channels__DOT__control_operators__DOT__ksl_tl_mem->__PVT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank = &TOP__opl3__DOT__channels__DOT__control_operators__DOT__ksl_tl_mem__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank;
    TOPp->__PVT__opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__env_int_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank = &TOP__opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__env_int_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank;
    TOPp->__PVT__opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__env_int_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank = &TOP__opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__env_int_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank;
    TOPp->__PVT__opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__state_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank = &TOP__opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__state_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank;
    TOPp->__PVT__opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__state_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank = &TOP__opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__state_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank;
    TOPp->__PVT__opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__feedback_mem__DOT__bankgen__BRA__0__KET____DOT__genblk2__DOT__mem_bank = &TOP__opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__feedback_mem__DOT__bankgen__BRA__0__KET____DOT__genblk2__DOT__mem_bank;
    TOPp->__PVT__opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__feedback_mem__DOT__bankgen__BRA__1__KET____DOT__genblk2__DOT__mem_bank = &TOP__opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__feedback_mem__DOT__bankgen__BRA__1__KET____DOT__genblk2__DOT__mem_bank;
    TOPp->__PVT__opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__final_phase_msb_mem = &TOP__opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__final_phase_msb_mem;
    TOPp->__PVT__opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__is_odd_period_msb_mem = &TOP__opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__is_odd_period_msb_mem;
    TOPp->__PVT__opl3__DOT__channels__DOT__control_operators__DOT__sl_rr_mem = &TOP__opl3__DOT__channels__DOT__control_operators__DOT__sl_rr_mem;
    TOPp->__PVT__opl3__DOT__channels__DOT__control_operators__DOT__sl_rr_mem->__PVT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank = &TOP__opl3__DOT__channels__DOT__control_operators__DOT__sl_rr_mem__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank;
    TOPp->__PVT__opl3__DOT__channels__DOT__control_operators__DOT__sl_rr_mem->__PVT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank = &TOP__opl3__DOT__channels__DOT__control_operators__DOT__sl_rr_mem__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank;
    TOPp->__PVT__opl3__DOT__channels__DOT__control_operators__DOT__ws_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank = &TOP__opl3__DOT__channels__DOT__control_operators__DOT__ws_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank;
    TOPp->__PVT__opl3__DOT__channels__DOT__control_operators__DOT__ws_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank = &TOP__opl3__DOT__channels__DOT__control_operators__DOT__ws_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank;
    TOPp->__PVT__opl3__DOT__channels__DOT__operator_out_mem__DOT__bankgen__BRA__0__KET____DOT__genblk2__DOT__mem_bank = &TOP__opl3__DOT__channels__DOT__operator_out_mem__DOT__bankgen__BRA__0__KET____DOT__genblk2__DOT__mem_bank;
    TOPp->__PVT__opl3__DOT__channels__DOT__operator_out_mem__DOT__bankgen__BRA__1__KET____DOT__genblk2__DOT__mem_bank = &TOP__opl3__DOT__channels__DOT__operator_out_mem__DOT__bankgen__BRA__1__KET____DOT__genblk2__DOT__mem_bank;
    // Setup each module's pointer back to symbol table (for public functions)
    TOPp->__Vconfigure(this, true);
    TOP__opl3__DOT__channels__DOT__ch_abcd_cnt_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank.__Vconfigure(this, true);
    TOP__opl3__DOT__channels__DOT__ch_abcd_cnt_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank.__Vconfigure(this, false);
    TOP__opl3__DOT__channels__DOT__control_operators__DOT__am_vib_egt_ksr_mult_mem.__Vconfigure(this, true);
    TOP__opl3__DOT__channels__DOT__control_operators__DOT__am_vib_egt_ksr_mult_mem__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank.__Vconfigure(this, true);
    TOP__opl3__DOT__channels__DOT__control_operators__DOT__am_vib_egt_ksr_mult_mem__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank.__Vconfigure(this, false);
    TOP__opl3__DOT__channels__DOT__control_operators__DOT__ar_dr_mem.__Vconfigure(this, false);
    TOP__opl3__DOT__channels__DOT__control_operators__DOT__ar_dr_mem__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank.__Vconfigure(this, false);
    TOP__opl3__DOT__channels__DOT__control_operators__DOT__ar_dr_mem__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank.__Vconfigure(this, false);
    TOP__opl3__DOT__channels__DOT__control_operators__DOT__fnum_low_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank.__Vconfigure(this, false);
    TOP__opl3__DOT__channels__DOT__control_operators__DOT__fnum_low_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank.__Vconfigure(this, false);
    TOP__opl3__DOT__channels__DOT__control_operators__DOT__kon_block_fnum_high_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank.__Vconfigure(this, true);
    TOP__opl3__DOT__channels__DOT__control_operators__DOT__kon_block_fnum_high_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank.__Vconfigure(this, false);
    TOP__opl3__DOT__channels__DOT__control_operators__DOT__ksl_tl_mem.__Vconfigure(this, false);
    TOP__opl3__DOT__channels__DOT__control_operators__DOT__ksl_tl_mem__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank.__Vconfigure(this, false);
    TOP__opl3__DOT__channels__DOT__control_operators__DOT__ksl_tl_mem__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank.__Vconfigure(this, false);
    TOP__opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__env_int_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank.__Vconfigure(this, true);
    TOP__opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__env_int_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank.__Vconfigure(this, false);
    TOP__opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__state_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank.__Vconfigure(this, true);
    TOP__opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__envelope_generator__DOT__state_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank.__Vconfigure(this, false);
    TOP__opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__feedback_mem__DOT__bankgen__BRA__0__KET____DOT__genblk2__DOT__mem_bank.__Vconfigure(this, true);
    TOP__opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__feedback_mem__DOT__bankgen__BRA__1__KET____DOT__genblk2__DOT__mem_bank.__Vconfigure(this, false);
    TOP__opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__final_phase_msb_mem.__Vconfigure(this, true);
    TOP__opl3__DOT__channels__DOT__control_operators__DOT__operator__DOT__phase_generator__DOT__is_odd_period_msb_mem.__Vconfigure(this, false);
    TOP__opl3__DOT__channels__DOT__control_operators__DOT__sl_rr_mem.__Vconfigure(this, false);
    TOP__opl3__DOT__channels__DOT__control_operators__DOT__sl_rr_mem__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank.__Vconfigure(this, false);
    TOP__opl3__DOT__channels__DOT__control_operators__DOT__sl_rr_mem__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank.__Vconfigure(this, false);
    TOP__opl3__DOT__channels__DOT__control_operators__DOT__ws_mem__DOT__bankgen__BRA__0__KET____DOT__genblk1__DOT__mem_bank.__Vconfigure(this, true);
    TOP__opl3__DOT__channels__DOT__control_operators__DOT__ws_mem__DOT__bankgen__BRA__1__KET____DOT__genblk1__DOT__mem_bank.__Vconfigure(this, false);
    TOP__opl3__DOT__channels__DOT__operator_out_mem__DOT__bankgen__BRA__0__KET____DOT__genblk2__DOT__mem_bank.__Vconfigure(this, true);
    TOP__opl3__DOT__channels__DOT__operator_out_mem__DOT__bankgen__BRA__1__KET____DOT__genblk2__DOT__mem_bank.__Vconfigure(this, false);
    // Setup scopes
    __Vscope_opl3__channels.configure(this, name(), "opl3.channels", "channels", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_opl3__channels__control_operators.configure(this, name(), "opl3.channels.control_operators", "control_operators", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_opl3__channels__control_operators__ERROR_operators_not_aligned_for_modulation.configure(this, name(), "opl3.channels.control_operators.ERROR_operators_not_aligned_for_modulation", "ERROR_operators_not_aligned_for_modulation", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_opl3__channels__control_operators__operator__calc_phase_inc.configure(this, name(), "opl3.channels.control_operators.operator.calc_phase_inc", "calc_phase_inc", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_opl3__channels__control_operators__operator__envelope_generator.configure(this, name(), "opl3.channels.control_operators.operator.envelope_generator", "envelope_generator", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_opl3__channels__control_operators__operator__envelope_generator__ksl_add_rom.configure(this, name(), "opl3.channels.control_operators.operator.envelope_generator.ksl_add_rom", "ksl_add_rom", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_opl3__channels__control_operators__operator__envelope_generator__state_mem.configure(this, name(), "opl3.channels.control_operators.operator.envelope_generator.state_mem", "state_mem", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_opl3__channels__control_operators__operator__phase_generator.configure(this, name(), "opl3.channels.control_operators.operator.phase_generator", "phase_generator", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_opl3__channels__control_operators__operator__phase_generator__calc_rhythm_phase.configure(this, name(), "opl3.channels.control_operators.operator.phase_generator.calc_rhythm_phase", "calc_rhythm_phase", -9, VerilatedScope::SCOPE_OTHER);
}
