/* Generated by Yosys 0.36+58 (git sha1 ea7818d31, c++ 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module reset_sync(clk, arst_n, reset);
  wire _0_;
  wire _1_;
  wire _2_;
  input arst_n;
  wire arst_n;
  input clk;
  wire clk;
  wire r0;
  wire r1;
  wire r2;
  output reset;
  wire reset;
  CC_BUFG _3_ (
    .I(_0_),
    .O(_2_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h1),
    .SR_INV(1'h1),
    .SR_VAL(1'h1)
  ) _4_ (
    .CLK(_2_),
    .D(r1),
    .EN(1'h1),
    .Q(r2),
    .SR(_1_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h1),
    .SR_INV(1'h1),
    .SR_VAL(1'h1)
  ) _5_ (
    .CLK(_2_),
    .D(r0),
    .EN(1'h1),
    .Q(r1),
    .SR(_1_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h1),
    .SR_INV(1'h1),
    .SR_VAL(1'h1)
  ) _6_ (
    .CLK(_2_),
    .D(1'h0),
    .EN(1'h1),
    .Q(r0),
    .SR(_1_)
  );
  CC_IBUF _7_ (
    .I(arst_n),
    .Y(_1_)
  );
  CC_IBUF _8_ (
    .I(clk),
    .Y(_0_)
  );
  CC_OBUF _9_ (
    .A(r2),
    .O(reset)
  );
endmodule
