-d D:\repos\openCologne\8.StressTest\7.sigma_delta_DAC\build_proj\impl\gwsynthesis\build_proj.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cfg D:\repos\openCologne\8.StressTest\7.sigma_delta_DAC\build_proj\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
