[package]
name = "svd2utra"
version = "0.1.0"
authors = ["Sean Cross <sean@xobs.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-xml = "0.19"
clap = "2"
anyhow = "1.0"
convert_case = "0.4"
