/* Generated by Yosys 0.37+39 (git sha1 461a7314f, g++ 13.2.1 -Os) */

module top(i_Rx_Serial, clk, o_Tx_Serial);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire [15:0] _040_;
  wire [15:0] _041_;
  wire [15:0] _042_;
  wire [15:0] _043_;
  wire [15:0] _044_;
  wire [15:0] _045_;
  wire [15:0] _046_;
  wire [15:0] _047_;
  wire [15:0] _048_;
  wire [15:0] _049_;
  wire [15:0] _050_;
  wire [2:0] _051_;
  wire [2:0] _052_;
  wire [2:0] _053_;
  wire [2:0] _054_;
  wire [3:0] _055_;
  wire [3:0] _056_;
  wire [3:0] _057_;
  wire [3:0] _058_;
  wire [2:0] _059_;
  wire [2:0] _060_;
  wire [2:0] _061_;
  wire [15:0] _062_;
  wire [15:0] _063_;
  wire [15:0] _064_;
  wire _065_;
  wire [15:0] _066_;
  wire [11:0] _067_;
  wire [2:0] _068_;
  wire [11:0] _069_;
  wire [2:0] _070_;
  wire _071_;
  wire [3:0] _072_;
  wire [2:0] _073_;
  wire [3:0] _074_;
  wire [1:0] _075_;
  wire [2:0] _076_;
  wire [3:0] _077_;
  wire [3:0] _078_;
  wire [2:0] _079_;
  wire [3:0] _080_;
  wire [2:0] _081_;
  wire [2:0] _082_;
  wire [2:0] _083_;
  wire [3:0] _084_;
  wire [3:0] _085_;
  wire [3:0] _086_;
  wire [1:0] _087_;
  wire [2:0] _088_;
  wire [1:0] _089_;
  wire [1:0] _090_;
  wire [1:0] _091_;
  wire [2:0] _092_;
  wire [3:0] _093_;
  wire [2:0] _094_;
  wire [3:0] _095_;
  wire [2:0] _096_;
  wire [3:0] _097_;
  wire [2:0] _098_;
  wire [2:0] _099_;
  wire [2:0] _100_;
  wire [3:0] _101_;
  wire [2:0] _102_;
  wire [3:0] _103_;
  input clk;
  wire clk;
  input i_Rx_Serial;
  wire i_Rx_Serial;
  wire [7:0] o_Rx_Byte;
  wire o_Rx_DV;
  output o_Tx_Serial;
  wire o_Tx_Serial;
  wire \uart_rx1.i_Rx_Serial ;
  wire [7:0] \uart_rx1.o_Rx_Byte ;
  wire \uart_rx1.o_Rx_DV ;
  wire \uart_rx1.osc_clk ;
  wire [2:0] \uart_rx1.r_Bit_Index ;
  wire [15:0] \uart_rx1.r_Clock_Count ;
  wire [7:0] \uart_rx1.r_Rx_Byte ;
  wire \uart_rx1.r_Rx_DV ;
  wire \uart_rx1.r_Rx_DV_last ;
  wire \uart_rx1.r_Rx_Data ;
  wire \uart_rx1.r_Rx_Data_R ;
  wire [2:0] \uart_rx1.r_SM_Main ;
  wire [7:0] \uart_tx1.i_Tx_Byte ;
  wire \uart_tx1.i_Tx_DV ;
  wire \uart_tx1.o_Tx_Done ;
  wire \uart_tx1.o_Tx_Serial ;
  wire [2:0] \uart_tx1.r_Bit_Index ;
  wire [15:0] \uart_tx1.r_Clock_Count ;
  wire [2:0] \uart_tx1.r_SM_Main ;
  wire [7:0] \uart_tx1.r_Tx_Data ;
  CC_LUT2 #(
    .INIT(4'h8)
  ) _104_ (
    .I0(_090_[0]),
    .I1(_054_[2]),
    .O(_030_)
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _105_ (
    .I0(_089_[0]),
    .I1(_084_[3]),
    .O(_090_[0])
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _106_ (
    .I0(\uart_rx1.r_SM_Main [0]),
    .I1(_080_[2]),
    .O(_084_[3])
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _107_ (
    .I0(\uart_rx1.r_SM_Main [2]),
    .I1(\uart_rx1.r_SM_Main [1]),
    .O(_080_[2])
  );
  CC_LUT3 #(
    .INIT(8'h80)
  ) _108_ (
    .I0(\uart_rx1.r_Bit_Index [1]),
    .I1(\uart_rx1.r_Bit_Index [2]),
    .I2(\uart_rx1.r_Bit_Index [0]),
    .O(_089_[0])
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _109_ (
    .I0(_090_[0]),
    .I1(_054_[1]),
    .O(_029_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _110_ (
    .I0(_090_[0]),
    .I1(_054_[0]),
    .O(_028_)
  );
  CC_LUT3 #(
    .INIT(8'h80)
  ) _111_ (
    .I0(_076_[0]),
    .I1(_076_[1]),
    .I2(_064_[15]),
    .O(_027_)
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _112_ (
    .I0(_075_[0]),
    .I1(_042_[15]),
    .O(_076_[0])
  );
  CC_LUT4 #(
    .INIT(16'h8000)
  ) _113_ (
    .I0(_074_[0]),
    .I1(_074_[1]),
    .I2(_074_[2]),
    .I3(_074_[3]),
    .O(_075_[0])
  );
  CC_LUT4 #(
    .INIT(16'h0001)
  ) _114_ (
    .I0(\uart_tx1.r_Clock_Count [12]),
    .I1(\uart_tx1.r_Clock_Count [13]),
    .I2(\uart_tx1.r_Clock_Count [14]),
    .I3(\uart_tx1.r_Clock_Count [15]),
    .O(_074_[0])
  );
  CC_LUT4 #(
    .INIT(16'h0001)
  ) _115_ (
    .I0(\uart_tx1.r_Clock_Count [8]),
    .I1(\uart_tx1.r_Clock_Count [9]),
    .I2(\uart_tx1.r_Clock_Count [10]),
    .I3(\uart_tx1.r_Clock_Count [11]),
    .O(_074_[1])
  );
  CC_LUT4 #(
    .INIT(16'h0001)
  ) _116_ (
    .I0(\uart_tx1.r_Clock_Count [0]),
    .I1(\uart_tx1.r_Clock_Count [3]),
    .I2(\uart_tx1.r_Clock_Count [5]),
    .I3(\uart_tx1.r_Clock_Count [7]),
    .O(_074_[2])
  );
  CC_LUT4 #(
    .INIT(16'h8000)
  ) _117_ (
    .I0(\uart_tx1.r_Clock_Count [1]),
    .I1(\uart_tx1.r_Clock_Count [2]),
    .I2(\uart_tx1.r_Clock_Count [4]),
    .I3(\uart_tx1.r_Clock_Count [6]),
    .O(_074_[3])
  );
  CC_LUT3 #(
    .INIT(8'h0e)
  ) _118_ (
    .I0(\uart_tx1.r_SM_Main [0]),
    .I1(\uart_tx1.r_SM_Main [1]),
    .I2(\uart_tx1.r_SM_Main [2]),
    .O(_076_[1])
  );
  CC_LUT3 #(
    .INIT(8'h80)
  ) _119_ (
    .I0(_076_[0]),
    .I1(_076_[1]),
    .I2(_064_[14]),
    .O(_026_)
  );
  CC_LUT3 #(
    .INIT(8'h80)
  ) _120_ (
    .I0(_076_[0]),
    .I1(_076_[1]),
    .I2(_064_[13]),
    .O(_025_)
  );
  CC_LUT3 #(
    .INIT(8'h80)
  ) _121_ (
    .I0(_076_[0]),
    .I1(_076_[1]),
    .I2(_064_[12]),
    .O(_024_)
  );
  CC_LUT3 #(
    .INIT(8'he0)
  ) _122_ (
    .I0(_083_[0]),
    .I1(_083_[1]),
    .I2(_050_[0]),
    .O(_066_[0])
  );
  CC_LUT3 #(
    .INIT(8'h70)
  ) _123_ (
    .I0(_080_[1]),
    .I1(_082_[1]),
    .I2(_082_[2]),
    .O(_083_[1])
  );
  CC_LUT3 #(
    .INIT(8'h40)
  ) _124_ (
    .I0(\uart_rx1.r_Clock_Count [2]),
    .I1(\uart_rx1.r_Clock_Count [0]),
    .I2(_081_[2]),
    .O(_082_[1])
  );
  CC_LUT4 #(
    .INIT(16'h1000)
  ) _125_ (
    .I0(\uart_rx1.r_Clock_Count [4]),
    .I1(\uart_rx1.r_Clock_Count [6]),
    .I2(\uart_rx1.r_Clock_Count [3]),
    .I3(\uart_rx1.r_Clock_Count [5]),
    .O(_081_[2])
  );
  CC_LUT4 #(
    .INIT(16'h1000)
  ) _126_ (
    .I0(\uart_rx1.r_Clock_Count [7]),
    .I1(\uart_rx1.r_Clock_Count [8]),
    .I2(_078_[2]),
    .I3(_078_[3]),
    .O(_080_[1])
  );
  CC_LUT4 #(
    .INIT(16'h0100)
  ) _127_ (
    .I0(\uart_rx1.r_Clock_Count [13]),
    .I1(\uart_rx1.r_Clock_Count [14]),
    .I2(\uart_rx1.r_Clock_Count [15]),
    .I3(\uart_rx1.r_Clock_Count [1]),
    .O(_078_[2])
  );
  CC_LUT4 #(
    .INIT(16'h0001)
  ) _128_ (
    .I0(\uart_rx1.r_Clock_Count [9]),
    .I1(\uart_rx1.r_Clock_Count [10]),
    .I2(\uart_rx1.r_Clock_Count [11]),
    .I3(\uart_rx1.r_Clock_Count [12]),
    .O(_078_[3])
  );
  CC_LUT3 #(
    .INIT(8'h10)
  ) _129_ (
    .I0(\uart_rx1.r_SM_Main [1]),
    .I1(\uart_rx1.r_SM_Main [2]),
    .I2(\uart_rx1.r_SM_Main [0]),
    .O(_082_[2])
  );
  CC_LUT4 #(
    .INIT(16'h7000)
  ) _130_ (
    .I0(_080_[0]),
    .I1(_080_[1]),
    .I2(_080_[2]),
    .I3(_046_[15]),
    .O(_083_[0])
  );
  CC_LUT3 #(
    .INIT(8'h40)
  ) _131_ (
    .I0(\uart_rx1.r_Clock_Count [0]),
    .I1(_079_[1]),
    .I2(\uart_rx1.r_Clock_Count [2]),
    .O(_080_[0])
  );
  CC_LUT4 #(
    .INIT(16'h1000)
  ) _132_ (
    .I0(\uart_rx1.r_Clock_Count [3]),
    .I1(\uart_rx1.r_Clock_Count [5]),
    .I2(\uart_rx1.r_Clock_Count [4]),
    .I3(\uart_rx1.r_Clock_Count [6]),
    .O(_079_[1])
  );
  CC_LUT3 #(
    .INIT(8'he0)
  ) _133_ (
    .I0(_083_[0]),
    .I1(_083_[1]),
    .I2(_050_[1]),
    .O(_066_[1])
  );
  CC_LUT3 #(
    .INIT(8'he0)
  ) _134_ (
    .I0(_083_[0]),
    .I1(_083_[1]),
    .I2(_050_[2]),
    .O(_066_[2])
  );
  CC_LUT3 #(
    .INIT(8'he0)
  ) _135_ (
    .I0(_083_[0]),
    .I1(_083_[1]),
    .I2(_050_[3]),
    .O(_066_[3])
  );
  CC_LUT3 #(
    .INIT(8'he0)
  ) _136_ (
    .I0(_083_[0]),
    .I1(_083_[1]),
    .I2(_050_[4]),
    .O(_066_[4])
  );
  CC_LUT3 #(
    .INIT(8'he0)
  ) _137_ (
    .I0(_083_[0]),
    .I1(_083_[1]),
    .I2(_050_[5]),
    .O(_066_[5])
  );
  CC_LUT3 #(
    .INIT(8'he0)
  ) _138_ (
    .I0(_083_[0]),
    .I1(_083_[1]),
    .I2(_050_[6]),
    .O(_066_[6])
  );
  CC_LUT3 #(
    .INIT(8'he0)
  ) _139_ (
    .I0(_083_[0]),
    .I1(_083_[1]),
    .I2(_050_[7]),
    .O(_066_[7])
  );
  CC_LUT3 #(
    .INIT(8'he0)
  ) _140_ (
    .I0(_083_[0]),
    .I1(_083_[1]),
    .I2(_050_[8]),
    .O(_066_[8])
  );
  CC_LUT3 #(
    .INIT(8'he0)
  ) _141_ (
    .I0(_083_[0]),
    .I1(_083_[1]),
    .I2(_050_[9]),
    .O(_066_[9])
  );
  CC_LUT3 #(
    .INIT(8'he0)
  ) _142_ (
    .I0(_083_[0]),
    .I1(_083_[1]),
    .I2(_050_[10]),
    .O(_066_[10])
  );
  CC_LUT3 #(
    .INIT(8'he0)
  ) _143_ (
    .I0(_083_[0]),
    .I1(_083_[1]),
    .I2(_050_[11]),
    .O(_066_[11])
  );
  CC_LUT3 #(
    .INIT(8'he0)
  ) _144_ (
    .I0(_083_[0]),
    .I1(_083_[1]),
    .I2(_050_[12]),
    .O(_066_[12])
  );
  CC_LUT3 #(
    .INIT(8'he0)
  ) _145_ (
    .I0(_083_[0]),
    .I1(_083_[1]),
    .I2(_050_[13]),
    .O(_066_[13])
  );
  CC_LUT3 #(
    .INIT(8'he0)
  ) _146_ (
    .I0(_083_[0]),
    .I1(_083_[1]),
    .I2(_050_[14]),
    .O(_066_[14])
  );
  CC_LUT3 #(
    .INIT(8'he0)
  ) _147_ (
    .I0(_083_[0]),
    .I1(_083_[1]),
    .I2(_050_[15]),
    .O(_066_[15])
  );
  CC_LUT4 #(
    .INIT(16'hf8ff)
  ) _148_ (
    .I0(_089_[0]),
    .I1(_100_[2]),
    .I2(_103_[2]),
    .I3(_103_[3]),
    .O(_068_[0])
  );
  CC_LUT4 #(
    .INIT(16'h8f00)
  ) _149_ (
    .I0(_080_[1]),
    .I1(_080_[0]),
    .I2(_046_[15]),
    .I3(_084_[3]),
    .O(_100_[2])
  );
  CC_LUT4 #(
    .INIT(16'h7000)
  ) _150_ (
    .I0(_080_[0]),
    .I1(_080_[1]),
    .I2(_086_[2]),
    .I3(_046_[15]),
    .O(_103_[2])
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _151_ (
    .I0(_080_[2]),
    .I1(\uart_rx1.r_SM_Main [0]),
    .O(_086_[2])
  );
  CC_LUT4 #(
    .INIT(16'h008f)
  ) _152_ (
    .I0(_080_[1]),
    .I1(_082_[1]),
    .I2(_082_[2]),
    .I3(_093_[3]),
    .O(_103_[3])
  );
  CC_LUT3 #(
    .INIT(8'h01)
  ) _153_ (
    .I0(_092_[0]),
    .I1(\uart_rx1.r_Rx_Data ),
    .I2(\uart_rx1.r_SM_Main [2]),
    .O(_093_[3])
  );
  CC_LUT2 #(
    .INIT(4'he)
  ) _154_ (
    .I0(\uart_rx1.r_SM_Main [1]),
    .I1(\uart_rx1.r_SM_Main [0]),
    .O(_092_[0])
  );
  CC_LUT3 #(
    .INIT(8'hfe)
  ) _155_ (
    .I0(_083_[0]),
    .I1(_088_[1]),
    .I2(_084_[3]),
    .O(_068_[1])
  );
  CC_LUT4 #(
    .INIT(16'h4000)
  ) _156_ (
    .I0(\uart_rx1.r_Rx_Data ),
    .I1(_080_[1]),
    .I2(_082_[2]),
    .I3(_082_[1]),
    .O(_088_[1])
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _157_ (
    .I0(_091_[0]),
    .I1(_086_[2]),
    .O(_067_[2])
  );
  CC_LUT3 #(
    .INIT(8'h70)
  ) _158_ (
    .I0(_080_[0]),
    .I1(_080_[1]),
    .I2(_046_[15]),
    .O(_091_[0])
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _159_ (
    .I0(_087_[0]),
    .I1(_061_[0]),
    .O(_009_)
  );
  CC_LUT4 #(
    .INIT(16'h7f00)
  ) _160_ (
    .I0(\uart_tx1.r_Bit_Index [0]),
    .I1(\uart_tx1.r_Bit_Index [1]),
    .I2(\uart_tx1.r_Bit_Index [2]),
    .I3(_085_[3]),
    .O(_087_[0])
  );
  CC_LUT3 #(
    .INIT(8'h10)
  ) _161_ (
    .I0(\uart_tx1.r_SM_Main [2]),
    .I1(\uart_tx1.r_SM_Main [0]),
    .I2(\uart_tx1.r_SM_Main [1]),
    .O(_085_[3])
  );
  CC_LUT3 #(
    .INIT(8'h80)
  ) _162_ (
    .I0(_076_[0]),
    .I1(_076_[1]),
    .I2(_064_[9]),
    .O(_021_)
  );
  CC_LUT4 #(
    .INIT(16'h0c07)
  ) _163_ (
    .I0(_097_[0]),
    .I1(\uart_tx1.r_SM_Main [1]),
    .I2(\uart_tx1.r_SM_Main [2]),
    .I3(\uart_tx1.r_SM_Main [0]),
    .O(_071_)
  );
  CC_LUT3 #(
    .INIT(8'h35)
  ) _164_ (
    .I0(_094_[0]),
    .I1(_094_[1]),
    .I2(\uart_tx1.r_Bit_Index [2]),
    .O(_097_[0])
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _165_ (
    .I0(_087_[0]),
    .I1(_061_[1]),
    .O(_010_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _166_ (
    .I0(_087_[0]),
    .I1(_061_[2]),
    .O(_011_)
  );
  CC_LUT3 #(
    .INIT(8'h80)
  ) _167_ (
    .I0(_076_[0]),
    .I1(_076_[1]),
    .I2(_064_[0]),
    .O(_012_)
  );
  CC_LUT4 #(
    .INIT(16'h1000)
  ) _168_ (
    .I0(_075_[0]),
    .I1(\uart_tx1.r_SM_Main [2]),
    .I2(\uart_tx1.r_SM_Main [1]),
    .I3(_042_[15]),
    .O(_099_[0])
  );
  CC_LUT4 #(
    .INIT(16'h0100)
  ) _169_ (
    .I0(\uart_tx1.r_SM_Main [2]),
    .I1(\uart_tx1.r_SM_Main [1]),
    .I2(\uart_tx1.r_SM_Main [0]),
    .I3(\uart_tx1.i_Tx_DV ),
    .O(_069_[9])
  );
  CC_LUT4 #(
    .INIT(16'h0b04)
  ) _170_ (
    .I0(_076_[0]),
    .I1(\uart_tx1.r_SM_Main [0]),
    .I2(\uart_tx1.r_SM_Main [2]),
    .I3(\uart_tx1.r_SM_Main [1]),
    .O(_070_[1])
  );
  CC_LUT4 #(
    .INIT(16'h1000)
  ) _171_ (
    .I0(_076_[0]),
    .I1(\uart_tx1.r_SM_Main [2]),
    .I2(\uart_tx1.r_SM_Main [1]),
    .I3(\uart_tx1.r_SM_Main [0]),
    .O(_070_[2])
  );
  CC_LUT3 #(
    .INIT(8'h80)
  ) _172_ (
    .I0(_076_[0]),
    .I1(_076_[1]),
    .I2(_064_[7]),
    .O(_019_)
  );
  CC_LUT3 #(
    .INIT(8'h80)
  ) _173_ (
    .I0(_076_[0]),
    .I1(_076_[1]),
    .I2(_064_[3]),
    .O(_015_)
  );
  CC_LUT3 #(
    .INIT(8'h80)
  ) _174_ (
    .I0(_076_[0]),
    .I1(_076_[1]),
    .I2(_064_[5]),
    .O(_017_)
  );
  CC_LUT3 #(
    .INIT(8'h80)
  ) _175_ (
    .I0(_076_[0]),
    .I1(_076_[1]),
    .I2(_064_[4]),
    .O(_016_)
  );
  CC_LUT3 #(
    .INIT(8'h80)
  ) _176_ (
    .I0(_076_[0]),
    .I1(_076_[1]),
    .I2(_064_[11]),
    .O(_023_)
  );
  CC_LUT3 #(
    .INIT(8'h80)
  ) _177_ (
    .I0(_076_[0]),
    .I1(_076_[1]),
    .I2(_064_[10]),
    .O(_022_)
  );
  CC_LUT3 #(
    .INIT(8'hf4)
  ) _178_ (
    .I0(\uart_tx1.o_Tx_Done ),
    .I1(\uart_tx1.i_Tx_DV ),
    .I2(o_Rx_DV),
    .O(_008_)
  );
  CC_LUT3 #(
    .INIT(8'h80)
  ) _179_ (
    .I0(_076_[0]),
    .I1(_076_[1]),
    .I2(_064_[8]),
    .O(_020_)
  );
  CC_LUT3 #(
    .INIT(8'h80)
  ) _180_ (
    .I0(_076_[0]),
    .I1(_076_[1]),
    .I2(_064_[6]),
    .O(_018_)
  );
  CC_LUT3 #(
    .INIT(8'h80)
  ) _181_ (
    .I0(_076_[0]),
    .I1(_076_[1]),
    .I2(_064_[2]),
    .O(_014_)
  );
  CC_LUT3 #(
    .INIT(8'h80)
  ) _182_ (
    .I0(_076_[0]),
    .I1(_076_[1]),
    .I2(_064_[1]),
    .O(_013_)
  );
  CC_LUT3 #(
    .INIT(8'h07)
  ) _183_ (
    .I0(\uart_rx1.r_Rx_Data ),
    .I1(_098_[1]),
    .I2(\uart_rx1.r_SM_Main [2]),
    .O(_006_)
  );
  CC_LUT3 #(
    .INIT(8'h80)
  ) _184_ (
    .I0(_082_[1]),
    .I1(_080_[1]),
    .I2(_082_[2]),
    .O(_098_[1])
  );
  CC_LUT4 #(
    .INIT(16'h100f)
  ) _185_ (
    .I0(_076_[0]),
    .I1(\uart_tx1.r_SM_Main [2]),
    .I2(\uart_tx1.r_SM_Main [1]),
    .I3(\uart_tx1.r_SM_Main [0]),
    .O(_002_)
  );
  CC_LUT3 #(
    .INIT(8'h42)
  ) _186_ (
    .I0(\uart_tx1.r_SM_Main [2]),
    .I1(\uart_tx1.r_SM_Main [1]),
    .I2(\uart_tx1.r_SM_Main [0]),
    .O(_007_)
  );
  CC_LUT3 #(
    .INIT(8'hf1)
  ) _187_ (
    .I0(_092_[0]),
    .I1(\uart_rx1.r_SM_Main [2]),
    .I2(_100_[2]),
    .O(_005_)
  );
  CC_LUT3 #(
    .INIT(8'h4f)
  ) _188_ (
    .I0(_091_[0]),
    .I1(_086_[2]),
    .I2(_092_[0]),
    .O(_004_)
  );
  CC_LUT3 #(
    .INIT(8'h01)
  ) _189_ (
    .I0(_099_[0]),
    .I1(\uart_tx1.r_SM_Main [2]),
    .I2(\uart_tx1.r_SM_Main [0]),
    .O(_003_)
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _190_ (
    .I0(\uart_rx1.r_Rx_DV_last ),
    .I1(\uart_rx1.r_Rx_DV ),
    .O(_031_)
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _191_ (
    .I0(\uart_rx1.r_Rx_Byte [0]),
    .I1(\uart_rx1.r_Rx_Data ),
    .I2(_096_[2]),
    .O(_032_)
  );
  CC_LUT4 #(
    .INIT(16'h0001)
  ) _192_ (
    .I0(_058_[3]),
    .I1(_058_[0]),
    .I2(_058_[1]),
    .I3(_058_[2]),
    .O(_096_[2])
  );
  CC_LUT4 #(
    .INIT(16'haccc)
  ) _193_ (
    .I0(\uart_rx1.r_Rx_Data ),
    .I1(\uart_rx1.r_Rx_Byte [1]),
    .I2(_095_[3]),
    .I3(_058_[2]),
    .O(_033_)
  );
  CC_LUT3 #(
    .INIT(8'h80)
  ) _194_ (
    .I0(_058_[3]),
    .I1(_058_[0]),
    .I2(_058_[1]),
    .O(_095_[3])
  );
  CC_LUT4 #(
    .INIT(16'haccc)
  ) _195_ (
    .I0(\uart_rx1.r_Rx_Data ),
    .I1(\uart_rx1.r_Rx_Byte [2]),
    .I2(_077_[2]),
    .I3(_058_[2]),
    .O(_034_)
  );
  CC_LUT3 #(
    .INIT(8'h40)
  ) _196_ (
    .I0(_058_[0]),
    .I1(_058_[3]),
    .I2(_058_[1]),
    .O(_077_[2])
  );
  CC_LUT4 #(
    .INIT(16'haccc)
  ) _197_ (
    .I0(\uart_rx1.r_Rx_Data ),
    .I1(\uart_rx1.r_Rx_Byte [3]),
    .I2(_072_[2]),
    .I3(_058_[2]),
    .O(_035_)
  );
  CC_LUT3 #(
    .INIT(8'h40)
  ) _198_ (
    .I0(_058_[1]),
    .I1(_058_[0]),
    .I2(_058_[3]),
    .O(_072_[2])
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _199_ (
    .I0(\uart_rx1.r_Rx_Byte [4]),
    .I1(\uart_rx1.r_Rx_Data ),
    .I2(_073_[2]),
    .O(_036_)
  );
  CC_LUT4 #(
    .INIT(16'h1000)
  ) _200_ (
    .I0(_058_[0]),
    .I1(_058_[1]),
    .I2(_058_[3]),
    .I3(_058_[2]),
    .O(_073_[2])
  );
  CC_LUT4 #(
    .INIT(16'hcacc)
  ) _201_ (
    .I0(\uart_rx1.r_Rx_Data ),
    .I1(\uart_rx1.r_Rx_Byte [5]),
    .I2(_058_[2]),
    .I3(_095_[3]),
    .O(_037_)
  );
  CC_LUT4 #(
    .INIT(16'hcacc)
  ) _202_ (
    .I0(\uart_rx1.r_Rx_Data ),
    .I1(\uart_rx1.r_Rx_Byte [6]),
    .I2(_058_[2]),
    .I3(_077_[2]),
    .O(_038_)
  );
  CC_LUT4 #(
    .INIT(16'hcacc)
  ) _203_ (
    .I0(\uart_rx1.r_Rx_Data ),
    .I1(\uart_rx1.r_Rx_Byte [7]),
    .I2(_058_[2]),
    .I3(_072_[2]),
    .O(_039_)
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _204_ (
    .I0(\uart_rx1.r_Bit_Index [0]),
    .O(_053_[0])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _205_ (
    .I0(\uart_rx1.r_Clock_Count [0]),
    .O(_044_[0])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _206_ (
    .I0(\uart_rx1.r_Clock_Count [1]),
    .O(_044_[1])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _207_ (
    .I0(\uart_rx1.r_Clock_Count [3]),
    .O(_044_[3])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _208_ (
    .I0(\uart_rx1.r_Clock_Count [5]),
    .O(_044_[5])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _209_ (
    .I0(\uart_rx1.r_Clock_Count [7]),
    .O(_044_[7])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _210_ (
    .I0(\uart_rx1.r_Clock_Count [8]),
    .O(_044_[8])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _211_ (
    .I0(\uart_rx1.r_Clock_Count [9]),
    .O(_044_[9])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _212_ (
    .I0(\uart_rx1.r_Clock_Count [10]),
    .O(_044_[10])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _213_ (
    .I0(\uart_rx1.r_Clock_Count [11]),
    .O(_044_[11])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _214_ (
    .I0(\uart_rx1.r_Clock_Count [12]),
    .O(_044_[12])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _215_ (
    .I0(\uart_rx1.r_Clock_Count [13]),
    .O(_044_[13])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _216_ (
    .I0(\uart_rx1.r_Clock_Count [14]),
    .O(_044_[14])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _217_ (
    .I0(\uart_rx1.r_Clock_Count [15]),
    .O(_044_[15])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _218_ (
    .I0(\uart_tx1.r_SM_Main [2]),
    .O(_001_)
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _219_ (
    .I0(\uart_tx1.r_Clock_Count [0]),
    .O(_040_[0])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _220_ (
    .I0(\uart_tx1.r_Clock_Count [3]),
    .O(_040_[3])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _221_ (
    .I0(\uart_tx1.r_Clock_Count [5]),
    .O(_040_[5])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _222_ (
    .I0(\uart_tx1.r_Clock_Count [7]),
    .O(_040_[7])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _223_ (
    .I0(\uart_tx1.r_Clock_Count [8]),
    .O(_040_[8])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _224_ (
    .I0(\uart_tx1.r_Clock_Count [9]),
    .O(_040_[9])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _225_ (
    .I0(\uart_tx1.r_Clock_Count [10]),
    .O(_040_[10])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _226_ (
    .I0(\uart_tx1.r_Clock_Count [11]),
    .O(_040_[11])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _227_ (
    .I0(\uart_tx1.r_Clock_Count [12]),
    .O(_040_[12])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _228_ (
    .I0(\uart_tx1.r_Clock_Count [13]),
    .O(_040_[13])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _229_ (
    .I0(\uart_tx1.r_Clock_Count [14]),
    .O(_040_[14])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _230_ (
    .I0(\uart_tx1.r_Clock_Count [15]),
    .O(_040_[15])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _231_ (
    .I0(\uart_tx1.r_Clock_Count [1]),
    .O(_040_[1])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _232_ (
    .I0(\uart_tx1.r_Clock_Count [2]),
    .O(_040_[2])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _233_ (
    .I0(\uart_tx1.r_Clock_Count [4]),
    .O(_040_[4])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _234_ (
    .I0(\uart_tx1.r_Clock_Count [6]),
    .O(_040_[6])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _235_ (
    .I0(\uart_rx1.r_Bit_Index [1]),
    .O(_055_[1])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _236_ (
    .I0(\uart_rx1.r_Bit_Index [2]),
    .O(_055_[2])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _237_ (
    .I0(\uart_rx1.r_Clock_Count [2]),
    .O(_044_[2])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _238_ (
    .I0(\uart_rx1.r_Clock_Count [4]),
    .O(_044_[4])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _239_ (
    .I0(\uart_rx1.r_Clock_Count [6]),
    .O(_044_[6])
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _240_ (
    .I0(_091_[0]),
    .I1(_086_[2]),
    .O(_068_[2])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _241_ (
    .I0(\uart_tx1.r_SM_Main [2]),
    .O(_000_)
  );
  CC_LUT4 #(
    .INIT(16'h8000)
  ) _242_ (
    .I0(\uart_tx1.r_Bit_Index [1]),
    .I1(\uart_tx1.r_Bit_Index [2]),
    .I2(\uart_tx1.r_SM_Main [1]),
    .I3(\uart_tx1.r_Bit_Index [0]),
    .O(_101_[0])
  );
  CC_LUT4 #(
    .INIT(16'h308a)
  ) _243_ (
    .I0(_101_[0]),
    .I1(_075_[0]),
    .I2(_042_[15]),
    .I3(\uart_tx1.r_SM_Main [0]),
    .O(_102_[1])
  );
  CC_LUT3 #(
    .INIT(8'hf4)
  ) _244_ (
    .I0(\uart_tx1.r_SM_Main [2]),
    .I1(_102_[1]),
    .I2(_069_[9]),
    .O(_070_[0])
  );
  CC_ADDF _245_ (
    .A(1'h0),
    .B(_040_[0]),
    .CI(1'h1),
    .CO(_041_[1]),
    .S(_043_[0])
  );
  CC_ADDF _246_ (
    .A(1'h0),
    .B(_040_[10]),
    .CI(_041_[10]),
    .CO(_041_[11]),
    .S(_043_[10])
  );
  CC_ADDF _247_ (
    .A(1'h0),
    .B(_040_[11]),
    .CI(_041_[11]),
    .CO(_041_[12]),
    .S(_043_[11])
  );
  CC_ADDF _248_ (
    .A(1'h0),
    .B(_040_[12]),
    .CI(_041_[12]),
    .CO(_041_[13]),
    .S(_043_[12])
  );
  CC_ADDF _249_ (
    .A(1'h0),
    .B(_040_[13]),
    .CI(_041_[13]),
    .CO(_041_[14]),
    .S(_043_[13])
  );
  CC_ADDF _250_ (
    .A(1'h0),
    .B(_040_[14]),
    .CI(_041_[14]),
    .CO(_041_[15]),
    .S(_043_[14])
  );
  CC_ADDF _251_ (
    .A(1'h0),
    .B(_040_[15]),
    .CI(_041_[15]),
    .CO(_042_[15]),
    .S(_043_[15])
  );
  CC_ADDF _252_ (
    .A(1'h1),
    .B(_040_[1]),
    .CI(_041_[1]),
    .CO(_041_[2]),
    .S(_043_[1])
  );
  CC_ADDF _253_ (
    .A(1'h1),
    .B(_040_[2]),
    .CI(_041_[2]),
    .CO(_041_[3]),
    .S(_043_[2])
  );
  CC_ADDF _254_ (
    .A(1'h0),
    .B(_040_[3]),
    .CI(_041_[3]),
    .CO(_041_[4]),
    .S(_043_[3])
  );
  CC_ADDF _255_ (
    .A(1'h1),
    .B(_040_[4]),
    .CI(_041_[4]),
    .CO(_041_[5]),
    .S(_043_[4])
  );
  CC_ADDF _256_ (
    .A(1'h0),
    .B(_040_[5]),
    .CI(_041_[5]),
    .CO(_041_[6]),
    .S(_043_[5])
  );
  CC_ADDF _257_ (
    .A(1'h1),
    .B(_040_[6]),
    .CI(_041_[6]),
    .CO(_041_[7]),
    .S(_043_[6])
  );
  CC_ADDF _258_ (
    .A(1'h0),
    .B(_040_[7]),
    .CI(_041_[7]),
    .CO(_041_[8]),
    .S(_043_[7])
  );
  CC_ADDF _259_ (
    .A(1'h0),
    .B(_040_[8]),
    .CI(_041_[8]),
    .CO(_041_[9]),
    .S(_043_[8])
  );
  CC_ADDF _260_ (
    .A(1'h0),
    .B(_040_[9]),
    .CI(_041_[9]),
    .CO(_041_[10]),
    .S(_043_[9])
  );
  CC_ADDF _261_ (
    .A(1'h0),
    .B(_044_[0]),
    .CI(1'h1),
    .CO(_045_[1]),
    .S(_047_[0])
  );
  CC_ADDF _262_ (
    .A(1'h0),
    .B(_044_[10]),
    .CI(_045_[10]),
    .CO(_045_[11]),
    .S(_047_[10])
  );
  CC_ADDF _263_ (
    .A(1'h0),
    .B(_044_[11]),
    .CI(_045_[11]),
    .CO(_045_[12]),
    .S(_047_[11])
  );
  CC_ADDF _264_ (
    .A(1'h0),
    .B(_044_[12]),
    .CI(_045_[12]),
    .CO(_045_[13]),
    .S(_047_[12])
  );
  CC_ADDF _265_ (
    .A(1'h0),
    .B(_044_[13]),
    .CI(_045_[13]),
    .CO(_045_[14]),
    .S(_047_[13])
  );
  CC_ADDF _266_ (
    .A(1'h0),
    .B(_044_[14]),
    .CI(_045_[14]),
    .CO(_045_[15]),
    .S(_047_[14])
  );
  CC_ADDF _267_ (
    .A(1'h0),
    .B(_044_[15]),
    .CI(_045_[15]),
    .CO(_046_[15]),
    .S(_047_[15])
  );
  CC_ADDF _268_ (
    .A(1'h1),
    .B(_044_[1]),
    .CI(_045_[1]),
    .CO(_045_[2]),
    .S(_047_[1])
  );
  CC_ADDF _269_ (
    .A(1'h1),
    .B(_044_[2]),
    .CI(_045_[2]),
    .CO(_045_[3]),
    .S(_047_[2])
  );
  CC_ADDF _270_ (
    .A(1'h0),
    .B(_044_[3]),
    .CI(_045_[3]),
    .CO(_045_[4]),
    .S(_047_[3])
  );
  CC_ADDF _271_ (
    .A(1'h1),
    .B(_044_[4]),
    .CI(_045_[4]),
    .CO(_045_[5]),
    .S(_047_[4])
  );
  CC_ADDF _272_ (
    .A(1'h0),
    .B(_044_[5]),
    .CI(_045_[5]),
    .CO(_045_[6]),
    .S(_047_[5])
  );
  CC_ADDF _273_ (
    .A(1'h1),
    .B(_044_[6]),
    .CI(_045_[6]),
    .CO(_045_[7]),
    .S(_047_[6])
  );
  CC_ADDF _274_ (
    .A(1'h0),
    .B(_044_[7]),
    .CI(_045_[7]),
    .CO(_045_[8]),
    .S(_047_[7])
  );
  CC_ADDF _275_ (
    .A(1'h0),
    .B(_044_[8]),
    .CI(_045_[8]),
    .CO(_045_[9]),
    .S(_047_[8])
  );
  CC_ADDF _276_ (
    .A(1'h0),
    .B(_044_[9]),
    .CI(_045_[9]),
    .CO(_045_[10]),
    .S(_047_[9])
  );
  CC_ADDF _277_ (
    .A(1'h1),
    .B(\uart_rx1.r_Clock_Count [0]),
    .CI(1'h0),
    .CO(_048_[1]),
    .S(_050_[0])
  );
  CC_ADDF _278_ (
    .A(1'h0),
    .B(\uart_rx1.r_Clock_Count [10]),
    .CI(_048_[10]),
    .CO(_048_[11]),
    .S(_050_[10])
  );
  CC_ADDF _279_ (
    .A(1'h0),
    .B(\uart_rx1.r_Clock_Count [11]),
    .CI(_048_[11]),
    .CO(_048_[12]),
    .S(_050_[11])
  );
  CC_ADDF _280_ (
    .A(1'h0),
    .B(\uart_rx1.r_Clock_Count [12]),
    .CI(_048_[12]),
    .CO(_048_[13]),
    .S(_050_[12])
  );
  CC_ADDF _281_ (
    .A(1'h0),
    .B(\uart_rx1.r_Clock_Count [13]),
    .CI(_048_[13]),
    .CO(_048_[14]),
    .S(_050_[13])
  );
  CC_ADDF _282_ (
    .A(1'h0),
    .B(\uart_rx1.r_Clock_Count [14]),
    .CI(_048_[14]),
    .CO(_048_[15]),
    .S(_050_[14])
  );
  CC_ADDF _283_ (
    .A(1'h0),
    .B(\uart_rx1.r_Clock_Count [15]),
    .CI(_048_[15]),
    .CO(_049_[15]),
    .S(_050_[15])
  );
  CC_ADDF _284_ (
    .A(1'h0),
    .B(\uart_rx1.r_Clock_Count [1]),
    .CI(_048_[1]),
    .CO(_048_[2]),
    .S(_050_[1])
  );
  CC_ADDF _285_ (
    .A(1'h0),
    .B(\uart_rx1.r_Clock_Count [2]),
    .CI(_048_[2]),
    .CO(_048_[3]),
    .S(_050_[2])
  );
  CC_ADDF _286_ (
    .A(1'h0),
    .B(\uart_rx1.r_Clock_Count [3]),
    .CI(_048_[3]),
    .CO(_048_[4]),
    .S(_050_[3])
  );
  CC_ADDF _287_ (
    .A(1'h0),
    .B(\uart_rx1.r_Clock_Count [4]),
    .CI(_048_[4]),
    .CO(_048_[5]),
    .S(_050_[4])
  );
  CC_ADDF _288_ (
    .A(1'h0),
    .B(\uart_rx1.r_Clock_Count [5]),
    .CI(_048_[5]),
    .CO(_048_[6]),
    .S(_050_[5])
  );
  CC_ADDF _289_ (
    .A(1'h0),
    .B(\uart_rx1.r_Clock_Count [6]),
    .CI(_048_[6]),
    .CO(_048_[7]),
    .S(_050_[6])
  );
  CC_ADDF _290_ (
    .A(1'h0),
    .B(\uart_rx1.r_Clock_Count [7]),
    .CI(_048_[7]),
    .CO(_048_[8]),
    .S(_050_[7])
  );
  CC_ADDF _291_ (
    .A(1'h0),
    .B(\uart_rx1.r_Clock_Count [8]),
    .CI(_048_[8]),
    .CO(_048_[9]),
    .S(_050_[8])
  );
  CC_ADDF _292_ (
    .A(1'h0),
    .B(\uart_rx1.r_Clock_Count [9]),
    .CI(_048_[9]),
    .CO(_048_[10]),
    .S(_050_[9])
  );
  CC_ADDF _293_ (
    .A(1'h1),
    .B(\uart_rx1.r_Bit_Index [0]),
    .CI(1'h0),
    .CO(_051_[1]),
    .S(_054_[0])
  );
  CC_ADDF _294_ (
    .A(1'h0),
    .B(\uart_rx1.r_Bit_Index [1]),
    .CI(_051_[1]),
    .CO(_051_[2]),
    .S(_054_[1])
  );
  CC_ADDF _295_ (
    .A(1'h0),
    .B(\uart_rx1.r_Bit_Index [2]),
    .CI(_051_[2]),
    .CO(_052_[2]),
    .S(_054_[2])
  );
  CC_ADDF _296_ (
    .A(1'h0),
    .B(_053_[0]),
    .CI(1'h1),
    .CO(_056_[1]),
    .S(_058_[0])
  );
  CC_ADDF _297_ (
    .A(1'h0),
    .B(_055_[1]),
    .CI(_056_[1]),
    .CO(_056_[2]),
    .S(_058_[1])
  );
  CC_ADDF _298_ (
    .A(1'h0),
    .B(_055_[2]),
    .CI(_056_[2]),
    .CO(_056_[3]),
    .S(_058_[2])
  );
  CC_ADDF _299_ (
    .A(1'h0),
    .B(1'h1),
    .CI(_056_[3]),
    .CO(_057_[3]),
    .S(_058_[3])
  );
  CC_ADDF _300_ (
    .A(1'h1),
    .B(\uart_tx1.r_Bit_Index [0]),
    .CI(1'h0),
    .CO(_059_[1]),
    .S(_061_[0])
  );
  CC_ADDF _301_ (
    .A(1'h0),
    .B(\uart_tx1.r_Bit_Index [1]),
    .CI(_059_[1]),
    .CO(_059_[2]),
    .S(_061_[1])
  );
  CC_ADDF _302_ (
    .A(1'h0),
    .B(\uart_tx1.r_Bit_Index [2]),
    .CI(_059_[2]),
    .CO(_060_[2]),
    .S(_061_[2])
  );
  CC_ADDF _303_ (
    .A(1'h1),
    .B(\uart_tx1.r_Clock_Count [0]),
    .CI(1'h0),
    .CO(_062_[1]),
    .S(_064_[0])
  );
  CC_ADDF _304_ (
    .A(1'h0),
    .B(\uart_tx1.r_Clock_Count [10]),
    .CI(_062_[10]),
    .CO(_062_[11]),
    .S(_064_[10])
  );
  CC_ADDF _305_ (
    .A(1'h0),
    .B(\uart_tx1.r_Clock_Count [11]),
    .CI(_062_[11]),
    .CO(_062_[12]),
    .S(_064_[11])
  );
  CC_ADDF _306_ (
    .A(1'h0),
    .B(\uart_tx1.r_Clock_Count [12]),
    .CI(_062_[12]),
    .CO(_062_[13]),
    .S(_064_[12])
  );
  CC_ADDF _307_ (
    .A(1'h0),
    .B(\uart_tx1.r_Clock_Count [13]),
    .CI(_062_[13]),
    .CO(_062_[14]),
    .S(_064_[13])
  );
  CC_ADDF _308_ (
    .A(1'h0),
    .B(\uart_tx1.r_Clock_Count [14]),
    .CI(_062_[14]),
    .CO(_062_[15]),
    .S(_064_[14])
  );
  CC_ADDF _309_ (
    .A(1'h0),
    .B(\uart_tx1.r_Clock_Count [15]),
    .CI(_062_[15]),
    .CO(_063_[15]),
    .S(_064_[15])
  );
  CC_ADDF _310_ (
    .A(1'h0),
    .B(\uart_tx1.r_Clock_Count [1]),
    .CI(_062_[1]),
    .CO(_062_[2]),
    .S(_064_[1])
  );
  CC_ADDF _311_ (
    .A(1'h0),
    .B(\uart_tx1.r_Clock_Count [2]),
    .CI(_062_[2]),
    .CO(_062_[3]),
    .S(_064_[2])
  );
  CC_ADDF _312_ (
    .A(1'h0),
    .B(\uart_tx1.r_Clock_Count [3]),
    .CI(_062_[3]),
    .CO(_062_[4]),
    .S(_064_[3])
  );
  CC_ADDF _313_ (
    .A(1'h0),
    .B(\uart_tx1.r_Clock_Count [4]),
    .CI(_062_[4]),
    .CO(_062_[5]),
    .S(_064_[4])
  );
  CC_ADDF _314_ (
    .A(1'h0),
    .B(\uart_tx1.r_Clock_Count [5]),
    .CI(_062_[5]),
    .CO(_062_[6]),
    .S(_064_[5])
  );
  CC_ADDF _315_ (
    .A(1'h0),
    .B(\uart_tx1.r_Clock_Count [6]),
    .CI(_062_[6]),
    .CO(_062_[7]),
    .S(_064_[6])
  );
  CC_ADDF _316_ (
    .A(1'h0),
    .B(\uart_tx1.r_Clock_Count [7]),
    .CI(_062_[7]),
    .CO(_062_[8]),
    .S(_064_[7])
  );
  CC_ADDF _317_ (
    .A(1'h0),
    .B(\uart_tx1.r_Clock_Count [8]),
    .CI(_062_[8]),
    .CO(_062_[9]),
    .S(_064_[8])
  );
  CC_ADDF _318_ (
    .A(1'h0),
    .B(\uart_tx1.r_Clock_Count [9]),
    .CI(_062_[9]),
    .CO(_062_[10]),
    .S(_064_[9])
  );
  CC_BUFG _319_ (
    .I(_065_),
    .O(\uart_rx1.osc_clk )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _320_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(\uart_rx1.o_Rx_DV ),
    .EN(1'h1),
    .Q(o_Rx_DV),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _321_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(\uart_rx1.o_Rx_Byte [0]),
    .EN(1'h1),
    .Q(o_Rx_Byte[0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _322_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(\uart_rx1.o_Rx_Byte [1]),
    .EN(1'h1),
    .Q(o_Rx_Byte[1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _323_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(\uart_rx1.o_Rx_Byte [2]),
    .EN(1'h1),
    .Q(o_Rx_Byte[2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _324_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(\uart_rx1.o_Rx_Byte [3]),
    .EN(1'h1),
    .Q(o_Rx_Byte[3]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _325_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(\uart_rx1.o_Rx_Byte [4]),
    .EN(1'h1),
    .Q(o_Rx_Byte[4]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _326_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(\uart_rx1.o_Rx_Byte [5]),
    .EN(1'h1),
    .Q(o_Rx_Byte[5]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _327_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(\uart_rx1.o_Rx_Byte [6]),
    .EN(1'h1),
    .Q(o_Rx_Byte[6]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _328_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(\uart_rx1.o_Rx_Byte [7]),
    .EN(1'h1),
    .Q(o_Rx_Byte[7]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _329_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_008_),
    .EN(1'h1),
    .Q(\uart_tx1.i_Tx_DV ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _330_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_007_),
    .EN(_002_),
    .Q(\uart_tx1.o_Tx_Done ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _331_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(o_Rx_Byte[0]),
    .EN(o_Rx_DV),
    .Q(\uart_tx1.i_Tx_Byte [0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _332_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(o_Rx_Byte[1]),
    .EN(o_Rx_DV),
    .Q(\uart_tx1.i_Tx_Byte [1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _333_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(o_Rx_Byte[2]),
    .EN(o_Rx_DV),
    .Q(\uart_tx1.i_Tx_Byte [2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _334_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(o_Rx_Byte[3]),
    .EN(o_Rx_DV),
    .Q(\uart_tx1.i_Tx_Byte [3]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _335_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(o_Rx_Byte[4]),
    .EN(o_Rx_DV),
    .Q(\uart_tx1.i_Tx_Byte [4]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _336_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(o_Rx_Byte[5]),
    .EN(o_Rx_DV),
    .Q(\uart_tx1.i_Tx_Byte [5]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _337_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(o_Rx_Byte[6]),
    .EN(o_Rx_DV),
    .Q(\uart_tx1.i_Tx_Byte [6]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _338_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(o_Rx_Byte[7]),
    .EN(o_Rx_DV),
    .Q(\uart_tx1.i_Tx_Byte [7]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _339_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_009_),
    .EN(_003_),
    .Q(\uart_tx1.r_Bit_Index [0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _340_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_010_),
    .EN(_003_),
    .Q(\uart_tx1.r_Bit_Index [1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _341_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_011_),
    .EN(_003_),
    .Q(\uart_tx1.r_Bit_Index [2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _342_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(\uart_rx1.r_Rx_DV ),
    .EN(1'h1),
    .Q(\uart_rx1.r_Rx_DV_last ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _343_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_031_),
    .EN(1'h1),
    .Q(\uart_rx1.o_Rx_DV ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h1),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _344_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(\uart_rx1.r_Rx_Data_R ),
    .EN(1'h1),
    .Q(\uart_rx1.r_Rx_Data ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h1),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _345_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(\uart_rx1.i_Rx_Serial ),
    .EN(1'h1),
    .Q(\uart_rx1.r_Rx_Data_R ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _346_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_032_),
    .EN(_100_[2]),
    .Q(\uart_rx1.r_Rx_Byte [0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _347_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_033_),
    .EN(_100_[2]),
    .Q(\uart_rx1.r_Rx_Byte [1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _348_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_034_),
    .EN(_100_[2]),
    .Q(\uart_rx1.r_Rx_Byte [2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _349_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_035_),
    .EN(_100_[2]),
    .Q(\uart_rx1.r_Rx_Byte [3]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _350_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_036_),
    .EN(_100_[2]),
    .Q(\uart_rx1.r_Rx_Byte [4]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _351_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_037_),
    .EN(_100_[2]),
    .Q(\uart_rx1.r_Rx_Byte [5]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _352_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_038_),
    .EN(_100_[2]),
    .Q(\uart_rx1.r_Rx_Byte [6]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _353_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_039_),
    .EN(_100_[2]),
    .Q(\uart_rx1.r_Rx_Byte [7]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _354_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_012_),
    .EN(_000_),
    .Q(\uart_tx1.r_Clock_Count [0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _355_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_013_),
    .EN(_000_),
    .Q(\uart_tx1.r_Clock_Count [1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _356_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_014_),
    .EN(_000_),
    .Q(\uart_tx1.r_Clock_Count [2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _357_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_015_),
    .EN(_000_),
    .Q(\uart_tx1.r_Clock_Count [3]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _358_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_016_),
    .EN(_000_),
    .Q(\uart_tx1.r_Clock_Count [4]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _359_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_017_),
    .EN(_000_),
    .Q(\uart_tx1.r_Clock_Count [5]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _360_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_018_),
    .EN(_000_),
    .Q(\uart_tx1.r_Clock_Count [6]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _361_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_019_),
    .EN(_000_),
    .Q(\uart_tx1.r_Clock_Count [7]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _362_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_020_),
    .EN(_000_),
    .Q(\uart_tx1.r_Clock_Count [8]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _363_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_021_),
    .EN(_000_),
    .Q(\uart_tx1.r_Clock_Count [9]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _364_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_022_),
    .EN(_000_),
    .Q(\uart_tx1.r_Clock_Count [10]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _365_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_023_),
    .EN(_000_),
    .Q(\uart_tx1.r_Clock_Count [11]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _366_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_024_),
    .EN(_000_),
    .Q(\uart_tx1.r_Clock_Count [12]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _367_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_025_),
    .EN(_000_),
    .Q(\uart_tx1.r_Clock_Count [13]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _368_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_026_),
    .EN(_000_),
    .Q(\uart_tx1.r_Clock_Count [14]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _369_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_027_),
    .EN(_000_),
    .Q(\uart_tx1.r_Clock_Count [15]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _370_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_066_[0]),
    .EN(_006_),
    .Q(\uart_rx1.r_Clock_Count [0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _371_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_066_[1]),
    .EN(_006_),
    .Q(\uart_rx1.r_Clock_Count [1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _372_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_066_[2]),
    .EN(_006_),
    .Q(\uart_rx1.r_Clock_Count [2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _373_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_066_[3]),
    .EN(_006_),
    .Q(\uart_rx1.r_Clock_Count [3]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _374_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_066_[4]),
    .EN(_006_),
    .Q(\uart_rx1.r_Clock_Count [4]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _375_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_066_[5]),
    .EN(_006_),
    .Q(\uart_rx1.r_Clock_Count [5]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _376_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_066_[6]),
    .EN(_006_),
    .Q(\uart_rx1.r_Clock_Count [6]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _377_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_066_[7]),
    .EN(_006_),
    .Q(\uart_rx1.r_Clock_Count [7]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _378_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_066_[8]),
    .EN(_006_),
    .Q(\uart_rx1.r_Clock_Count [8]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _379_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_066_[9]),
    .EN(_006_),
    .Q(\uart_rx1.r_Clock_Count [9]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _380_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_066_[10]),
    .EN(_006_),
    .Q(\uart_rx1.r_Clock_Count [10]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _381_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_066_[11]),
    .EN(_006_),
    .Q(\uart_rx1.r_Clock_Count [11]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _382_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_066_[12]),
    .EN(_006_),
    .Q(\uart_rx1.r_Clock_Count [12]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _383_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_066_[13]),
    .EN(_006_),
    .Q(\uart_rx1.r_Clock_Count [13]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _384_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_066_[14]),
    .EN(_006_),
    .Q(\uart_rx1.r_Clock_Count [14]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _385_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_066_[15]),
    .EN(_006_),
    .Q(\uart_rx1.r_Clock_Count [15]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _386_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(\uart_rx1.r_Rx_Byte [0]),
    .EN(_067_[2]),
    .Q(\uart_rx1.o_Rx_Byte [0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _387_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(\uart_rx1.r_Rx_Byte [1]),
    .EN(_067_[2]),
    .Q(\uart_rx1.o_Rx_Byte [1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _388_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(\uart_rx1.r_Rx_Byte [2]),
    .EN(_067_[2]),
    .Q(\uart_rx1.o_Rx_Byte [2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _389_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(\uart_rx1.r_Rx_Byte [3]),
    .EN(_067_[2]),
    .Q(\uart_rx1.o_Rx_Byte [3]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _390_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(\uart_rx1.r_Rx_Byte [4]),
    .EN(_067_[2]),
    .Q(\uart_rx1.o_Rx_Byte [4]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _391_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(\uart_rx1.r_Rx_Byte [5]),
    .EN(_067_[2]),
    .Q(\uart_rx1.o_Rx_Byte [5]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _392_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(\uart_rx1.r_Rx_Byte [6]),
    .EN(_067_[2]),
    .Q(\uart_rx1.o_Rx_Byte [6]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _393_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(\uart_rx1.r_Rx_Byte [7]),
    .EN(_067_[2]),
    .Q(\uart_rx1.o_Rx_Byte [7]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _394_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_068_[0]),
    .EN(1'h1),
    .Q(\uart_rx1.r_SM_Main [0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _395_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_068_[1]),
    .EN(1'h1),
    .Q(\uart_rx1.r_SM_Main [1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _396_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_068_[2]),
    .EN(1'h1),
    .Q(\uart_rx1.r_SM_Main [2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _397_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(\uart_tx1.i_Tx_Byte [0]),
    .EN(_069_[9]),
    .Q(\uart_tx1.r_Tx_Data [0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _398_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(\uart_tx1.i_Tx_Byte [1]),
    .EN(_069_[9]),
    .Q(\uart_tx1.r_Tx_Data [1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _399_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(\uart_tx1.i_Tx_Byte [2]),
    .EN(_069_[9]),
    .Q(\uart_tx1.r_Tx_Data [2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _400_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(\uart_tx1.i_Tx_Byte [3]),
    .EN(_069_[9]),
    .Q(\uart_tx1.r_Tx_Data [3]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _401_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(\uart_tx1.i_Tx_Byte [4]),
    .EN(_069_[9]),
    .Q(\uart_tx1.r_Tx_Data [4]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _402_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(\uart_tx1.i_Tx_Byte [5]),
    .EN(_069_[9]),
    .Q(\uart_tx1.r_Tx_Data [5]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _403_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(\uart_tx1.i_Tx_Byte [6]),
    .EN(_069_[9]),
    .Q(\uart_tx1.r_Tx_Data [6]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _404_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(\uart_tx1.i_Tx_Byte [7]),
    .EN(_069_[9]),
    .Q(\uart_tx1.r_Tx_Data [7]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _405_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_028_),
    .EN(_005_),
    .Q(\uart_rx1.r_Bit_Index [0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _406_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_029_),
    .EN(_005_),
    .Q(\uart_rx1.r_Bit_Index [1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _407_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_030_),
    .EN(_005_),
    .Q(\uart_rx1.r_Bit_Index [2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _408_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_071_),
    .EN(_001_),
    .Q(\uart_tx1.o_Tx_Serial ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _409_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_070_[0]),
    .EN(1'h1),
    .Q(\uart_tx1.r_SM_Main [0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _410_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_070_[1]),
    .EN(1'h1),
    .Q(\uart_tx1.r_SM_Main [1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _411_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_070_[2]),
    .EN(1'h1),
    .Q(\uart_tx1.r_SM_Main [2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _412_ (
    .CLK(\uart_rx1.osc_clk ),
    .D(_092_[0]),
    .EN(_004_),
    .Q(\uart_rx1.r_Rx_DV ),
    .SR(1'h0)
  );
  CC_MX4 _413_ (
    .D0(\uart_tx1.r_Tx_Data [0]),
    .D1(\uart_tx1.r_Tx_Data [1]),
    .D2(\uart_tx1.r_Tx_Data [2]),
    .D3(\uart_tx1.r_Tx_Data [3]),
    .S0(\uart_tx1.r_Bit_Index [0]),
    .S1(\uart_tx1.r_Bit_Index [1]),
    .Y(_094_[0])
  );
  CC_MX4 _414_ (
    .D0(\uart_tx1.r_Tx_Data [4]),
    .D1(\uart_tx1.r_Tx_Data [5]),
    .D2(\uart_tx1.r_Tx_Data [6]),
    .D3(\uart_tx1.r_Tx_Data [7]),
    .S0(\uart_tx1.r_Bit_Index [0]),
    .S1(\uart_tx1.r_Bit_Index [1]),
    .Y(_094_[1])
  );
  CC_IBUF _415_ (
    .I(clk),
    .Y(_065_)
  );
  CC_IBUF _416_ (
    .I(i_Rx_Serial),
    .Y(\uart_rx1.i_Rx_Serial )
  );
  CC_OBUF _417_ (
    .A(\uart_tx1.o_Tx_Serial ),
    .O(o_Tx_Serial)
  );
  assign _041_[0] = 1'h1;
  assign _042_[14:0] = _041_[15:1];
  assign _045_[0] = 1'h1;
  assign _046_[14:0] = _045_[15:1];
  assign _048_[0] = 1'h0;
  assign _049_[14:0] = _048_[15:1];
  assign _051_[0] = 1'h0;
  assign _052_[1:0] = _051_[2:1];
  assign _053_[2:1] = \uart_rx1.r_Bit_Index [2:1];
  assign { _055_[3], _055_[0] } = { 1'h1, _053_[0] };
  assign _056_[0] = 1'h1;
  assign _057_[2:0] = _056_[3:1];
  assign _059_[0] = 1'h0;
  assign _060_[1:0] = _059_[2:1];
  assign _062_[0] = 1'h0;
  assign _063_[14:0] = _062_[15:1];
  assign { _067_[11:10], _067_[8], _067_[5], _067_[0] } = { 4'h0, _067_[1] };
  assign { _069_[11:10], _069_[8], _069_[5], _069_[0] } = { 4'h0, _069_[1] };
  assign { _072_[3], _072_[1:0] } = { _058_[2], \uart_rx1.r_Rx_Byte [3], \uart_rx1.r_Rx_Data  };
  assign _073_[1:0] = { \uart_rx1.r_Rx_Data , \uart_rx1.r_Rx_Byte [4] };
  assign _075_[1] = _042_[15];
  assign _076_[2] = _064_[8];
  assign { _077_[3], _077_[1:0] } = { _058_[2], \uart_rx1.r_Rx_Byte [2], \uart_rx1.r_Rx_Data  };
  assign _078_[1:0] = \uart_rx1.r_Clock_Count [8:7];
  assign { _079_[2], _079_[0] } = { \uart_rx1.r_Clock_Count [2], \uart_rx1.r_Clock_Count [0] };
  assign _080_[3] = _046_[15];
  assign _081_[1:0] = { \uart_rx1.r_Clock_Count [0], \uart_rx1.r_Clock_Count [2] };
  assign _082_[0] = _080_[1];
  assign _083_[2] = _050_[12];
  assign _084_[2:0] = { _046_[15], _080_[0], _080_[1] };
  assign _085_[2:0] = \uart_tx1.r_Bit_Index ;
  assign { _086_[3], _086_[1:0] } = { _046_[15], _080_[1:0] };
  assign _087_[1] = _061_[1];
  assign { _088_[2], _088_[0] } = { _084_[3], _083_[0] };
  assign _089_[1] = _084_[3];
  assign _090_[1] = _054_[0];
  assign _091_[1] = _086_[2];
  assign _092_[2:1] = { \uart_rx1.r_SM_Main [2], \uart_rx1.r_Rx_Data  };
  assign _093_[2:0] = { _082_[2:1], _080_[1] };
  assign _094_[2] = \uart_tx1.r_Bit_Index [2];
  assign _095_[2:0] = { _058_[2], \uart_rx1.r_Rx_Byte [5], \uart_rx1.r_Rx_Data  };
  assign _096_[1:0] = { \uart_rx1.r_Rx_Data , \uart_rx1.r_Rx_Byte [0] };
  assign _097_[3:1] = { \uart_tx1.r_SM_Main [0], \uart_tx1.r_SM_Main [2:1] };
  assign { _098_[2], _098_[0] } = { \uart_rx1.r_SM_Main [2], \uart_rx1.r_Rx_Data  };
  assign _099_[2:1] = { \uart_tx1.r_SM_Main [0], \uart_tx1.r_SM_Main [2] };
  assign _100_[1:0] = { \uart_rx1.r_SM_Main [2], _092_[0] };
  assign _101_[3:1] = { \uart_tx1.r_SM_Main [0], _042_[15], _075_[0] };
  assign { _102_[2], _102_[0] } = { _069_[9], \uart_tx1.r_SM_Main [2] };
  assign _103_[1:0] = { _100_[2], _089_[0] };
endmodule
