
FAMILY  = GW2AR
PART    = 18CLQFP176
BOARD   = Tang Nano 20K
PROJECT = TestStar
CHIPDB  = /home/nikola/ChiliChips/openCologne/pnr_tests-gowin/GW2AR-18C/QFN88.json
TOP_VERILOG=$(PROJECT).sv
#SYNTH_OPTS = -nodsp
include ../../config.mk
