[ActiveSupport PAR]
; Global primary clocks
GLOBAL_PRIMARY_USED = 14;
; Global primary clock #0
GLOBAL_PRIMARY_0_SIGNALNAME = clk_c;
GLOBAL_PRIMARY_0_DRIVERTYPE = CLK_PIN;
GLOBAL_PRIMARY_0_LOADNUM = 921;
; Global primary clock #1
GLOBAL_PRIMARY_1_SIGNALNAME = clk_host_c;
GLOBAL_PRIMARY_1_DRIVERTYPE = CLK_PIN;
GLOBAL_PRIMARY_1_LOADNUM = 47;
; Global primary clock #2
GLOBAL_PRIMARY_2_SIGNALNAME = channels/control_operators/reb_mem_o;
GLOBAL_PRIMARY_2_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_2_LOADNUM = 0;
; Global primary clock #3
GLOBAL_PRIMARY_3_SIGNALNAME = channels/control_operators/reb_mem_o_0;
GLOBAL_PRIMARY_3_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_3_LOADNUM = 0;
; Global primary clock #4
GLOBAL_PRIMARY_4_SIGNALNAME = sample_clk_en;
GLOBAL_PRIMARY_4_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_4_LOADNUM = 0;
; Global primary clock #5
GLOBAL_PRIMARY_5_SIGNALNAME = channels/ram_and_0;
GLOBAL_PRIMARY_5_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_5_LOADNUM = 0;
; Global primary clock #6
GLOBAL_PRIMARY_6_SIGNALNAME = channels/ram_and_2;
GLOBAL_PRIMARY_6_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_6_LOADNUM = 0;
; Global primary clock #7
GLOBAL_PRIMARY_7_SIGNALNAME = channels/ram_and_0_0;
GLOBAL_PRIMARY_7_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_7_LOADNUM = 0;
; Global primary clock #8
GLOBAL_PRIMARY_8_SIGNALNAME = channels/ram_and_2_0;
GLOBAL_PRIMARY_8_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_8_LOADNUM = 0;
; Global primary clock #9
GLOBAL_PRIMARY_9_SIGNALNAME = channels/state[8];
GLOBAL_PRIMARY_9_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_9_LOADNUM = 0;
; Global primary clock #10
GLOBAL_PRIMARY_10_SIGNALNAME = reset;
GLOBAL_PRIMARY_10_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_10_LOADNUM = 0;
; Global primary clock #11
GLOBAL_PRIMARY_11_SIGNALNAME = channels/un1_state_19_i;
GLOBAL_PRIMARY_11_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_11_LOADNUM = 0;
; Global primary clock #12
GLOBAL_PRIMARY_12_SIGNALNAME = channels/un1_state_18_i;
GLOBAL_PRIMARY_12_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_12_LOADNUM = 0;
; Global primary clock #13
GLOBAL_PRIMARY_13_SIGNALNAME = channels/control_operators/out[2]_0;
GLOBAL_PRIMARY_13_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_13_LOADNUM = 0;
; I/O Bank 0 Usage
BANK_0_USED = 12;
BANK_0_AVAIL = 27;
BANK_0_VCCIO = 2.5V;
BANK_0_VREF1 = NA;
BANK_0_VREF2 = NA;
; I/O Bank 1 Usage
BANK_1_USED = 5;
BANK_1_AVAIL = 33;
BANK_1_VCCIO = 2.5V;
BANK_1_VREF1 = NA;
BANK_1_VREF2 = NA;
; I/O Bank 2 Usage
BANK_2_USED = 10;
BANK_2_AVAIL = 34;
BANK_2_VCCIO = 2.5V;
BANK_2_VREF1 = NA;
BANK_2_VREF2 = NA;
; I/O Bank 3 Usage
BANK_3_USED = 7;
BANK_3_AVAIL = 33;
BANK_3_VCCIO = 2.5V;
BANK_3_VREF1 = NA;
BANK_3_VREF2 = NA;
; I/O Bank 6 Usage
BANK_6_USED = 21;
BANK_6_AVAIL = 33;
BANK_6_VCCIO = 2.5V;
BANK_6_VREF1 = NA;
BANK_6_VREF2 = NA;
; I/O Bank 7 Usage
BANK_7_USED = 20;
BANK_7_AVAIL = 32;
BANK_7_VCCIO = 2.5V;
BANK_7_VREF1 = NA;
BANK_7_VREF2 = NA;
; I/O Bank 8 Usage
BANK_8_USED = 2;
BANK_8_AVAIL = 13;
BANK_8_VCCIO = 2.5V;
BANK_8_VREF1 = NA;
BANK_8_VREF2 = NA;
