/* Generated by Yosys 0.40+22 (git sha1 fa0c5c1d4, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */

module top(clk_10MHz, areset_n, led, i2c_scl, i2c_sda);
  wire [6:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire [6:0] _024_;
  wire [6:0] _025_;
  wire [6:0] _026_;
  wire [6:0] _027_;
  wire [6:0] _028_;
  wire [6:0] _029_;
  wire [6:0] _030_;
  wire [23:0] _031_;
  wire [23:0] _032_;
  wire [23:0] _033_;
  wire [6:0] _034_;
  wire [6:0] _035_;
  wire [6:0] _036_;
  wire [6:0] _037_;
  wire [3:0] _038_;
  wire [3:0] _039_;
  wire [3:0] _040_;
  wire [3:0] _041_;
  wire [3:0] _042_;
  wire _043_;
  wire [3:0] _044_;
  wire [2:0] _045_;
  wire [4:0] _046_;
  wire _047_;
  wire _048_;
  wire [2:0] _049_;
  wire [15:0] _050_;
  wire [15:0] _051_;
  wire [2:0] _052_;
  wire [2:0] _053_;
  wire [3:0] _054_;
  wire [2:0] _055_;
  wire [1:0] _056_;
  wire [1:0] _057_;
  wire [3:0] _058_;
  wire [1:0] _059_;
  wire [3:0] _060_;
  wire [1:0] _061_;
  wire [3:0] _062_;
  wire [1:0] _063_;
  wire [3:0] _064_;
  wire [3:0] _065_;
  wire [3:0] _066_;
  wire [1:0] _067_;
  wire [3:0] _068_;
  wire [2:0] _069_;
  wire [2:0] _070_;
  wire [1:0] _071_;
  wire [2:0] _072_;
  wire [2:0] _073_;
  wire _074_;
  wire [2:0] _075_;
  wire [3:0] _076_;
  wire [2:0] _077_;
  wire [3:0] _078_;
  wire [2:0] _079_;
  wire _080_;
  wire [2:0] _081_;
  wire [2:0] _082_;
  wire [2:0] _083_;
  wire [2:0] _084_;
  wire [3:0] _085_;
  wire [2:0] _086_;
  wire [2:0] _087_;
  wire [2:0] _088_;
  wire [3:0] _089_;
  wire [2:0] _090_;
  wire [3:0] _091_;
  wire [3:0] _092_;
  wire [3:0] _093_;
  wire [2:0] _094_;
  wire [3:0] _095_;
  wire _096_;
  input areset_n;
  wire areset_n;
  input clk_10MHz;
  wire clk_10MHz;
  wire [6:0] cnt_100kHz;
  wire [23:0] counter;
  inout i2c_scl;
  wire i2c_scl;
  inout i2c_sda;
  wire i2c_sda;
  output led;
  wire led;
  wire strobe_100kHz;
  wire \u_i2c_top.areset_n ;
  wire \u_i2c_top.clk ;
  wire [15:0] \u_i2c_top.i2c_reg_addr ;
  wire [6:0] \u_i2c_top.i2c_reg_cnt ;
  wire \u_i2c_top.i2c_reg_done ;
  wire \u_i2c_top.i2c_scl_di ;
  wire \u_i2c_top.i2c_scl_do ;
  wire \u_i2c_top.i2c_sda_di ;
  wire \u_i2c_top.i2c_sda_do ;
  wire \u_i2c_top.u_i2c_ctrl.acknowledge_bit ;
  wire [3:0] \u_i2c_top.u_i2c_ctrl.bit_cnt ;
  wire [3:0] \u_i2c_top.u_i2c_ctrl.bit_cnt_dec ;
  wire \u_i2c_top.u_i2c_ctrl.post_serial_data ;
  wire [3:0] \u_i2c_top.u_i2c_ctrl.post_state ;
  wire [3:0] \u_i2c_top.u_i2c_ctrl.process_cnt ;
  wire [7:0] \u_i2c_top.u_i2c_ctrl.slave_address_plus_rw ;
  wire [3:0] \u_i2c_top.u_i2c_ctrl.state ;
  CC_LUT2 #(
    .INIT(4'h4)
  ) _097_ (
    .I0(_061_[0]),
    .I1(_030_[0]),
    .O(_000_[0])
  );
  CC_LUT4 #(
    .INIT(16'h8000)
  ) _098_ (
    .I0(_060_[0]),
    .I1(cnt_100kHz[1]),
    .I2(cnt_100kHz[5]),
    .I3(cnt_100kHz[6]),
    .O(_061_[0])
  );
  CC_LUT4 #(
    .INIT(16'h0100)
  ) _099_ (
    .I0(cnt_100kHz[2]),
    .I1(cnt_100kHz[3]),
    .I2(cnt_100kHz[4]),
    .I3(cnt_100kHz[0]),
    .O(_060_[0])
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _100_ (
    .I0(_061_[0]),
    .I1(_030_[1]),
    .O(_000_[1])
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _101_ (
    .I0(_061_[0]),
    .I1(_030_[2]),
    .O(_000_[2])
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _102_ (
    .I0(_061_[0]),
    .I1(_030_[3]),
    .O(_000_[3])
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _103_ (
    .I0(_061_[0]),
    .I1(_030_[4]),
    .O(_000_[4])
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _104_ (
    .I0(_061_[0]),
    .I1(_030_[5]),
    .O(_000_[5])
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _105_ (
    .I0(_061_[0]),
    .I1(_030_[6]),
    .O(_000_[6])
  );
  CC_LUT2 #(
    .INIT(4'h7)
  ) _106_ (
    .I0(_064_[3]),
    .I1(_082_[0]),
    .O(_048_)
  );
  CC_LUT2 #(
    .INIT(4'hb)
  ) _107_ (
    .I0(\u_i2c_top.u_i2c_ctrl.state [0]),
    .I1(_063_[1]),
    .O(_064_[3])
  );
  CC_LUT2 #(
    .INIT(4'h1)
  ) _108_ (
    .I0(\u_i2c_top.u_i2c_ctrl.state [2]),
    .I1(\u_i2c_top.u_i2c_ctrl.state [1]),
    .O(_063_[1])
  );
  CC_LUT3 #(
    .INIT(8'h71)
  ) _109_ (
    .I0(\u_i2c_top.u_i2c_ctrl.state [2]),
    .I1(\u_i2c_top.u_i2c_ctrl.state [1]),
    .I2(\u_i2c_top.u_i2c_ctrl.process_cnt [1]),
    .O(_082_[0])
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _110_ (
    .I0(\u_i2c_top.u_i2c_ctrl.bit_cnt_dec [0]),
    .I1(\u_i2c_top.u_i2c_ctrl.slave_address_plus_rw [6]),
    .O(_023_)
  );
  CC_LUT2 #(
    .INIT(4'h7)
  ) _111_ (
    .I0(_067_[0]),
    .I1(_067_[1]),
    .O(_047_)
  );
  CC_LUT4 #(
    .INIT(16'h0fbb)
  ) _112_ (
    .I0(_057_[0]),
    .I1(_046_[3]),
    .I2(_046_[0]),
    .I3(_066_[3]),
    .O(_067_[0])
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _113_ (
    .I0(\u_i2c_top.u_i2c_ctrl.state [2]),
    .I1(\u_i2c_top.u_i2c_ctrl.state [0]),
    .O(_066_[3])
  );
  CC_LUT4 #(
    .INIT(16'h0007)
  ) _114_ (
    .I0(_046_[1]),
    .I1(_045_[0]),
    .I2(_065_[2]),
    .I3(_065_[3]),
    .O(_067_[1])
  );
  CC_LUT3 #(
    .INIT(8'hc1)
  ) _115_ (
    .I0(\u_i2c_top.u_i2c_ctrl.state [0]),
    .I1(\u_i2c_top.u_i2c_ctrl.state [1]),
    .I2(\u_i2c_top.u_i2c_ctrl.state [2]),
    .O(_065_[2])
  );
  CC_LUT3 #(
    .INIT(8'h80)
  ) _116_ (
    .I0(\u_i2c_top.u_i2c_ctrl.state [1]),
    .I1(\u_i2c_top.u_i2c_ctrl.state [0]),
    .I2(\u_i2c_top.u_i2c_ctrl.post_serial_data ),
    .O(_065_[3])
  );
  CC_LUT3 #(
    .INIT(8'h10)
  ) _117_ (
    .I0(\u_i2c_top.u_i2c_ctrl.state [1]),
    .I1(\u_i2c_top.u_i2c_ctrl.state [0]),
    .I2(\u_i2c_top.u_i2c_ctrl.state [2]),
    .O(_045_[0])
  );
  CC_LUT3 #(
    .INIT(8'h1c)
  ) _118_ (
    .I0(\u_i2c_top.u_i2c_ctrl.state [0]),
    .I1(\u_i2c_top.u_i2c_ctrl.state [2]),
    .I2(\u_i2c_top.u_i2c_ctrl.state [1]),
    .O(_045_[2])
  );
  CC_LUT2 #(
    .INIT(4'hb)
  ) _119_ (
    .I0(_066_[3]),
    .I1(_045_[2]),
    .O(_045_[1])
  );
  CC_LUT4 #(
    .INIT(16'h0bff)
  ) _120_ (
    .I0(\u_i2c_top.u_i2c_ctrl.post_state [0]),
    .I1(_083_[1]),
    .I2(_059_[1]),
    .I3(_064_[3]),
    .O(_049_[0])
  );
  CC_LUT2 #(
    .INIT(4'h1)
  ) _121_ (
    .I0(_045_[2]),
    .I1(_070_[2]),
    .O(_083_[1])
  );
  CC_LUT4 #(
    .INIT(16'h1000)
  ) _122_ (
    .I0(\u_i2c_top.u_i2c_ctrl.acknowledge_bit ),
    .I1(\u_i2c_top.u_i2c_ctrl.state [2]),
    .I2(\u_i2c_top.u_i2c_ctrl.state [1]),
    .I3(\u_i2c_top.u_i2c_ctrl.state [0]),
    .O(_070_[2])
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _123_ (
    .I0(\u_i2c_top.u_i2c_ctrl.state [2]),
    .I1(\u_i2c_top.u_i2c_ctrl.state [1]),
    .O(_059_[1])
  );
  CC_LUT3 #(
    .INIT(8'h0b)
  ) _124_ (
    .I0(\u_i2c_top.u_i2c_ctrl.post_state [1]),
    .I1(_083_[1]),
    .I2(_065_[2]),
    .O(_049_[1])
  );
  CC_LUT4 #(
    .INIT(16'hff40)
  ) _125_ (
    .I0(\u_i2c_top.u_i2c_ctrl.state [2]),
    .I1(\u_i2c_top.u_i2c_ctrl.post_state [2]),
    .I2(\u_i2c_top.u_i2c_ctrl.state [0]),
    .I3(_070_[2]),
    .O(_049_[2])
  );
  CC_LUT3 #(
    .INIT(8'h40)
  ) _126_ (
    .I0(\u_i2c_top.u_i2c_ctrl.process_cnt [3]),
    .I1(\u_i2c_top.u_i2c_ctrl.bit_cnt_dec [0]),
    .I2(_045_[2]),
    .O(_044_[0])
  );
  CC_LUT3 #(
    .INIT(8'h40)
  ) _127_ (
    .I0(\u_i2c_top.u_i2c_ctrl.process_cnt [3]),
    .I1(_045_[2]),
    .I2(\u_i2c_top.u_i2c_ctrl.bit_cnt_dec [1]),
    .O(_044_[1])
  );
  CC_LUT3 #(
    .INIT(8'h40)
  ) _128_ (
    .I0(\u_i2c_top.u_i2c_ctrl.process_cnt [3]),
    .I1(_045_[2]),
    .I2(\u_i2c_top.u_i2c_ctrl.bit_cnt_dec [2]),
    .O(_044_[2])
  );
  CC_LUT3 #(
    .INIT(8'hf8)
  ) _129_ (
    .I0(_063_[1]),
    .I1(\u_i2c_top.u_i2c_ctrl.state [0]),
    .I2(_077_[2]),
    .O(_044_[3])
  );
  CC_LUT3 #(
    .INIT(8'he0)
  ) _130_ (
    .I0(\u_i2c_top.u_i2c_ctrl.bit_cnt_dec [3]),
    .I1(\u_i2c_top.u_i2c_ctrl.process_cnt [3]),
    .I2(_045_[2]),
    .O(_077_[2])
  );
  CC_LUT2 #(
    .INIT(4'h1)
  ) _131_ (
    .I0(\u_i2c_top.i2c_reg_cnt [1]),
    .I1(\u_i2c_top.i2c_reg_cnt [0]),
    .O(_096_)
  );
  CC_LUT2 #(
    .INIT(4'h6)
  ) _132_ (
    .I0(\u_i2c_top.i2c_reg_cnt [1]),
    .I1(\u_i2c_top.i2c_reg_cnt [0]),
    .O(_053_[1])
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _133_ (
    .I0(\u_i2c_top.i2c_reg_cnt [2]),
    .I1(_053_[1]),
    .O(_090_[2])
  );
  CC_LUT3 #(
    .INIT(8'h0e)
  ) _134_ (
    .I0(_075_[0]),
    .I1(\u_i2c_top.i2c_reg_cnt [4]),
    .I2(_054_[2]),
    .O(\u_i2c_top.i2c_reg_addr [1])
  );
  CC_LUT3 #(
    .INIT(8'h40)
  ) _135_ (
    .I0(\u_i2c_top.i2c_reg_cnt [2]),
    .I1(_053_[1]),
    .I2(\u_i2c_top.i2c_reg_cnt [4]),
    .O(_054_[2])
  );
  CC_LUT3 #(
    .INIT(8'h07)
  ) _136_ (
    .I0(\u_i2c_top.i2c_reg_cnt [3]),
    .I1(_090_[1]),
    .I2(_090_[2]),
    .O(\u_i2c_top.i2c_reg_addr [2])
  );
  CC_LUT4 #(
    .INIT(16'h007f)
  ) _137_ (
    .I0(_080_),
    .I1(\u_i2c_top.i2c_reg_cnt [2]),
    .I2(\u_i2c_top.i2c_reg_cnt [3]),
    .I3(\u_i2c_top.i2c_reg_cnt [4]),
    .O(_090_[1])
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _138_ (
    .I0(\u_i2c_top.i2c_reg_cnt [1]),
    .I1(\u_i2c_top.i2c_reg_cnt [0]),
    .O(_080_)
  );
  CC_LUT4 #(
    .INIT(16'h000e)
  ) _139_ (
    .I0(_076_[0]),
    .I1(\u_i2c_top.i2c_reg_cnt [4]),
    .I2(_054_[2]),
    .I3(_054_[3]),
    .O(\u_i2c_top.i2c_reg_addr [3])
  );
  CC_LUT3 #(
    .INIT(8'h80)
  ) _140_ (
    .I0(\u_i2c_top.i2c_reg_cnt [2]),
    .I1(\u_i2c_top.i2c_reg_cnt [4]),
    .I2(\u_i2c_top.i2c_reg_cnt [0]),
    .O(_054_[3])
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _141_ (
    .I0(\u_i2c_top.i2c_reg_cnt [1]),
    .I1(\u_i2c_top.i2c_reg_cnt [0]),
    .O(_074_)
  );
  CC_LUT3 #(
    .INIT(8'h0b)
  ) _142_ (
    .I0(_094_[0]),
    .I1(_090_[1]),
    .I2(_054_[2]),
    .O(\u_i2c_top.i2c_reg_addr [4])
  );
  CC_LUT4 #(
    .INIT(16'h0305)
  ) _143_ (
    .I0(\u_i2c_top.i2c_reg_cnt [0]),
    .I1(\u_i2c_top.i2c_reg_cnt [2]),
    .I2(\u_i2c_top.i2c_reg_cnt [3]),
    .I3(\u_i2c_top.i2c_reg_cnt [1]),
    .O(_094_[0])
  );
  CC_LUT3 #(
    .INIT(8'h0e)
  ) _144_ (
    .I0(_086_[0]),
    .I1(\u_i2c_top.i2c_reg_cnt [4]),
    .I2(_054_[2]),
    .O(\u_i2c_top.i2c_reg_addr [5])
  );
  CC_LUT4 #(
    .INIT(16'hfff2)
  ) _145_ (
    .I0(_078_[0]),
    .I1(\u_i2c_top.i2c_reg_cnt [4]),
    .I2(_054_[3]),
    .I3(_078_[3]),
    .O(\u_i2c_top.i2c_reg_addr [7])
  );
  CC_LUT4 #(
    .INIT(16'h0100)
  ) _146_ (
    .I0(\u_i2c_top.i2c_reg_cnt [1]),
    .I1(\u_i2c_top.i2c_reg_cnt [2]),
    .I2(\u_i2c_top.i2c_reg_cnt [0]),
    .I3(\u_i2c_top.i2c_reg_cnt [4]),
    .O(_078_[3])
  );
  CC_LUT3 #(
    .INIT(8'h0e)
  ) _147_ (
    .I0(_081_[0]),
    .I1(\u_i2c_top.i2c_reg_cnt [4]),
    .I2(_054_[3]),
    .O(\u_i2c_top.i2c_reg_addr [8])
  );
  CC_LUT4 #(
    .INIT(16'hbbf0)
  ) _148_ (
    .I0(\u_i2c_top.i2c_reg_cnt [2]),
    .I1(\u_i2c_top.i2c_reg_cnt [0]),
    .I2(_095_[2]),
    .I3(\u_i2c_top.i2c_reg_cnt [4]),
    .O(\u_i2c_top.i2c_reg_addr [9])
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _149_ (
    .I0(\u_i2c_top.i2c_reg_cnt [0]),
    .I1(\u_i2c_top.i2c_reg_cnt [1]),
    .O(_055_[1])
  );
  CC_LUT4 #(
    .INIT(16'h000e)
  ) _150_ (
    .I0(_089_[0]),
    .I1(\u_i2c_top.i2c_reg_cnt [4]),
    .I2(_079_[2]),
    .I3(_054_[3]),
    .O(\u_i2c_top.i2c_reg_addr [10])
  );
  CC_LUT3 #(
    .INIT(8'h40)
  ) _151_ (
    .I0(\u_i2c_top.i2c_reg_cnt [2]),
    .I1(_055_[1]),
    .I2(\u_i2c_top.i2c_reg_cnt [4]),
    .O(_079_[2])
  );
  CC_LUT3 #(
    .INIT(8'hf4)
  ) _152_ (
    .I0(\u_i2c_top.i2c_reg_cnt [4]),
    .I1(_079_[1]),
    .I2(_079_[2]),
    .O(\u_i2c_top.i2c_reg_addr [11])
  );
  CC_LUT3 #(
    .INIT(8'hf4)
  ) _153_ (
    .I0(\u_i2c_top.i2c_reg_cnt [4]),
    .I1(_088_[1]),
    .I2(_078_[3]),
    .O(\u_i2c_top.i2c_reg_addr [12])
  );
  CC_LUT3 #(
    .INIT(8'hf4)
  ) _154_ (
    .I0(\u_i2c_top.i2c_reg_cnt [4]),
    .I1(_087_[1]),
    .I2(_054_[3]),
    .O(\u_i2c_top.i2c_reg_addr [13])
  );
  CC_LUT4 #(
    .INIT(16'hfff2)
  ) _155_ (
    .I0(_054_[0]),
    .I1(\u_i2c_top.i2c_reg_cnt [4]),
    .I2(_054_[2]),
    .I3(_054_[3]),
    .O(\u_i2c_top.i2c_reg_addr [14])
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _156_ (
    .I0(\u_i2c_top.u_i2c_ctrl.slave_address_plus_rw [6]),
    .I1(\u_i2c_top.u_i2c_ctrl.bit_cnt_dec [0]),
    .O(_022_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _157_ (
    .I0(\u_i2c_top.i2c_reg_addr [7]),
    .I1(_045_[0]),
    .O(_015_)
  );
  CC_LUT4 #(
    .INIT(16'h1000)
  ) _158_ (
    .I0(\u_i2c_top.u_i2c_ctrl.process_cnt [3]),
    .I1(\u_i2c_top.u_i2c_ctrl.state [2]),
    .I2(\u_i2c_top.u_i2c_ctrl.state [1]),
    .I3(\u_i2c_top.u_i2c_ctrl.state [0]),
    .O(_014_)
  );
  CC_LUT4 #(
    .INIT(16'h1000)
  ) _159_ (
    .I0(_058_[0]),
    .I1(_058_[1]),
    .I2(_058_[2]),
    .I3(_068_[3]),
    .O(_008_)
  );
  CC_LUT2 #(
    .INIT(4'h1)
  ) _160_ (
    .I0(_057_[0]),
    .I1(_056_[0]),
    .O(_058_[0])
  );
  CC_LUT3 #(
    .INIT(8'he7)
  ) _161_ (
    .I0(\u_i2c_top.u_i2c_ctrl.state [2]),
    .I1(\u_i2c_top.u_i2c_ctrl.state [0]),
    .I2(\u_i2c_top.u_i2c_ctrl.state [1]),
    .O(_057_[0])
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _162_ (
    .I0(\u_i2c_top.u_i2c_ctrl.process_cnt [3]),
    .I1(strobe_100kHz),
    .O(_072_[1])
  );
  CC_LUT4 #(
    .INIT(16'h0001)
  ) _163_ (
    .I0(\u_i2c_top.u_i2c_ctrl.bit_cnt [0]),
    .I1(\u_i2c_top.u_i2c_ctrl.bit_cnt [1]),
    .I2(\u_i2c_top.u_i2c_ctrl.bit_cnt [2]),
    .I3(\u_i2c_top.u_i2c_ctrl.bit_cnt [3]),
    .O(_056_[0])
  );
  CC_LUT3 #(
    .INIT(8'h8f)
  ) _164_ (
    .I0(\u_i2c_top.u_i2c_ctrl.process_cnt [3]),
    .I1(strobe_100kHz),
    .I2(_045_[2]),
    .O(_058_[2])
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _165_ (
    .I0(_056_[0]),
    .I1(_045_[0]),
    .O(_058_[1])
  );
  CC_LUT4 #(
    .INIT(16'h03cd)
  ) _166_ (
    .I0(_025_[6]),
    .I1(\u_i2c_top.u_i2c_ctrl.state [2]),
    .I2(\u_i2c_top.u_i2c_ctrl.state [0]),
    .I3(\u_i2c_top.u_i2c_ctrl.state [1]),
    .O(_068_[3])
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _167_ (
    .I0(\u_i2c_top.u_i2c_ctrl.state [0]),
    .I1(_059_[1]),
    .O(_016_)
  );
  CC_LUT4 #(
    .INIT(16'hf2ff)
  ) _168_ (
    .I0(_072_[1]),
    .I1(_065_[2]),
    .I2(_091_[2]),
    .I3(_064_[3]),
    .O(_001_)
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _169_ (
    .I0(strobe_100kHz),
    .I1(\u_i2c_top.u_i2c_ctrl.process_cnt [0]),
    .O(_091_[2])
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _170_ (
    .I0(\u_i2c_top.u_i2c_ctrl.process_cnt [1]),
    .I1(\u_i2c_top.u_i2c_ctrl.process_cnt [2]),
    .I2(strobe_100kHz),
    .I3(_064_[3]),
    .O(_002_)
  );
  CC_LUT4 #(
    .INIT(16'h2003)
  ) _171_ (
    .I0(_062_[0]),
    .I1(\u_i2c_top.u_i2c_ctrl.state [2]),
    .I2(\u_i2c_top.u_i2c_ctrl.state [1]),
    .I3(\u_i2c_top.u_i2c_ctrl.state [0]),
    .O(_005_)
  );
  CC_LUT4 #(
    .INIT(16'h5c00)
  ) _172_ (
    .I0(\u_i2c_top.i2c_sda_do ),
    .I1(\u_i2c_top.u_i2c_ctrl.process_cnt [3]),
    .I2(\u_i2c_top.u_i2c_ctrl.process_cnt [1]),
    .I3(strobe_100kHz),
    .O(_062_[0])
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _173_ (
    .I0(\u_i2c_top.u_i2c_ctrl.process_cnt [2]),
    .I1(\u_i2c_top.u_i2c_ctrl.process_cnt [0]),
    .I2(strobe_100kHz),
    .I3(_064_[3]),
    .O(_003_)
  );
  CC_LUT4 #(
    .INIT(16'hf800)
  ) _174_ (
    .I0(strobe_100kHz),
    .I1(\u_i2c_top.u_i2c_ctrl.process_cnt [1]),
    .I2(_092_[2]),
    .I3(_064_[3]),
    .O(_004_)
  );
  CC_LUT3 #(
    .INIT(8'hd0)
  ) _175_ (
    .I0(strobe_100kHz),
    .I1(_059_[1]),
    .I2(\u_i2c_top.u_i2c_ctrl.process_cnt [3]),
    .O(_092_[2])
  );
  CC_LUT4 #(
    .INIT(16'h1000)
  ) _176_ (
    .I0(_058_[0]),
    .I1(_058_[1]),
    .I2(_058_[2]),
    .I3(_045_[2]),
    .O(_006_)
  );
  CC_LUT3 #(
    .INIT(8'h10)
  ) _177_ (
    .I0(_073_[0]),
    .I1(_073_[1]),
    .I2(_073_[2]),
    .O(_007_)
  );
  CC_LUT2 #(
    .INIT(4'h1)
  ) _178_ (
    .I0(_071_[0]),
    .I1(\u_i2c_top.u_i2c_ctrl.process_cnt [1]),
    .O(_073_[0])
  );
  CC_LUT4 #(
    .INIT(16'hfea3)
  ) _179_ (
    .I0(\u_i2c_top.u_i2c_ctrl.process_cnt [3]),
    .I1(\u_i2c_top.u_i2c_ctrl.state [0]),
    .I2(\u_i2c_top.u_i2c_ctrl.state [2]),
    .I3(\u_i2c_top.u_i2c_ctrl.state [1]),
    .O(_071_[0])
  );
  CC_LUT3 #(
    .INIT(8'h40)
  ) _180_ (
    .I0(_056_[0]),
    .I1(_072_[1]),
    .I2(_045_[2]),
    .O(_073_[1])
  );
  CC_LUT4 #(
    .INIT(16'h5701)
  ) _181_ (
    .I0(\u_i2c_top.u_i2c_ctrl.state [1]),
    .I1(\u_i2c_top.u_i2c_ctrl.state [2]),
    .I2(\u_i2c_top.u_i2c_ctrl.state [0]),
    .I3(strobe_100kHz),
    .O(_073_[2])
  );
  CC_LUT3 #(
    .INIT(8'hf8)
  ) _182_ (
    .I0(_045_[2]),
    .I1(_056_[0]),
    .I2(_070_[2]),
    .O(_093_[2])
  );
  CC_LUT3 #(
    .INIT(8'hb0)
  ) _183_ (
    .I0(strobe_100kHz),
    .I1(\u_i2c_top.u_i2c_ctrl.state [0]),
    .I2(_052_[2]),
    .O(_093_[3])
  );
  CC_LUT4 #(
    .INIT(16'h8ccf)
  ) _184_ (
    .I0(\u_i2c_top.u_i2c_ctrl.process_cnt [1]),
    .I1(strobe_100kHz),
    .I2(\u_i2c_top.u_i2c_ctrl.state [2]),
    .I3(\u_i2c_top.u_i2c_ctrl.state [1]),
    .O(_052_[2])
  );
  CC_LUT3 #(
    .INIT(8'h40)
  ) _185_ (
    .I0(_025_[6]),
    .I1(\u_i2c_top.i2c_reg_done ),
    .I2(strobe_100kHz),
    .O(_013_)
  );
  CC_LUT4 #(
    .INIT(16'h0c05)
  ) _186_ (
    .I0(_025_[6]),
    .I1(_072_[1]),
    .I2(_073_[1]),
    .I3(_064_[3]),
    .O(_012_)
  );
  CC_LUT3 #(
    .INIT(8'hc5)
  ) _187_ (
    .I0(_025_[6]),
    .I1(_069_[1]),
    .I2(_064_[3]),
    .O(_011_)
  );
  CC_LUT4 #(
    .INIT(16'h4000)
  ) _188_ (
    .I0(\u_i2c_top.u_i2c_ctrl.state [0]),
    .I1(_059_[1]),
    .I2(strobe_100kHz),
    .I3(\u_i2c_top.u_i2c_ctrl.process_cnt [1]),
    .O(_069_[1])
  );
  CC_LUT3 #(
    .INIT(8'h0e)
  ) _189_ (
    .I0(_082_[0]),
    .I1(\u_i2c_top.u_i2c_ctrl.process_cnt [0]),
    .I2(_082_[2]),
    .O(_010_)
  );
  CC_LUT4 #(
    .INIT(16'h7303)
  ) _190_ (
    .I0(\u_i2c_top.u_i2c_ctrl.process_cnt [3]),
    .I1(strobe_100kHz),
    .I2(_063_[1]),
    .I3(\u_i2c_top.u_i2c_ctrl.state [0]),
    .O(_082_[2])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _191_ (
    .I0(_053_[1]),
    .O(_017_)
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _192_ (
    .I0(\u_i2c_top.i2c_reg_cnt [0]),
    .O(_036_[0])
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _193_ (
    .I0(_074_),
    .O(_018_)
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _194_ (
    .I0(_080_),
    .O(_019_)
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _195_ (
    .I0(_055_[1]),
    .O(_020_)
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _196_ (
    .I0(_096_),
    .O(_021_)
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _197_ (
    .I0(\u_i2c_top.i2c_reg_cnt [1]),
    .O(_026_[1])
  );
  CC_LUT4 #(
    .INIT(16'h0fab)
  ) _198_ (
    .I0(\u_i2c_top.i2c_reg_cnt [3]),
    .I1(\u_i2c_top.i2c_reg_cnt [1]),
    .I2(\u_i2c_top.i2c_reg_cnt [2]),
    .I3(\u_i2c_top.i2c_reg_cnt [4]),
    .O(_084_[1])
  );
  CC_LUT4 #(
    .INIT(16'h0337)
  ) _199_ (
    .I0(\u_i2c_top.i2c_reg_cnt [3]),
    .I1(\u_i2c_top.i2c_reg_cnt [1]),
    .I2(\u_i2c_top.i2c_reg_cnt [2]),
    .I3(\u_i2c_top.i2c_reg_cnt [4]),
    .O(_084_[2])
  );
  CC_LUT3 #(
    .INIT(8'h4b)
  ) _200_ (
    .I0(\u_i2c_top.i2c_reg_cnt [0]),
    .I1(_084_[1]),
    .I2(_084_[2]),
    .O(\u_i2c_top.i2c_reg_addr [0])
  );
  CC_LUT4 #(
    .INIT(16'h0ff1)
  ) _201_ (
    .I0(\u_i2c_top.i2c_reg_cnt [2]),
    .I1(\u_i2c_top.i2c_reg_cnt [0]),
    .I2(\u_i2c_top.i2c_reg_cnt [3]),
    .I3(_053_[1]),
    .O(_085_[2])
  );
  CC_LUT4 #(
    .INIT(16'hbbf0)
  ) _202_ (
    .I0(\u_i2c_top.i2c_reg_cnt [2]),
    .I1(_053_[1]),
    .I2(_085_[2]),
    .I3(\u_i2c_top.i2c_reg_cnt [4]),
    .O(\u_i2c_top.i2c_reg_addr [6])
  );
  CC_LUT4 #(
    .INIT(16'h0ff4)
  ) _203_ (
    .I0(\u_i2c_top.u_i2c_ctrl.process_cnt [2]),
    .I1(\u_i2c_top.u_i2c_ctrl.state [0]),
    .I2(\u_i2c_top.u_i2c_ctrl.state [2]),
    .I3(\u_i2c_top.u_i2c_ctrl.state [1]),
    .O(_093_[0])
  );
  CC_LUT4 #(
    .INIT(16'h0d00)
  ) _204_ (
    .I0(_093_[0]),
    .I1(\u_i2c_top.u_i2c_ctrl.process_cnt [3]),
    .I2(_093_[2]),
    .I3(_093_[3]),
    .O(_009_)
  );
  CC_ADDF _205_ (
    .A(\u_i2c_top.i2c_reg_cnt [0]),
    .B(1'h0),
    .CI(1'h1),
    .CO(_024_[1]),
    .S(_027_[0])
  );
  CC_ADDF _206_ (
    .A(\u_i2c_top.i2c_reg_cnt [1]),
    .B(1'h1),
    .CI(_024_[1]),
    .CO(_024_[2]),
    .S(_027_[1])
  );
  CC_ADDF _207_ (
    .A(\u_i2c_top.i2c_reg_cnt [2]),
    .B(1'h1),
    .CI(_024_[2]),
    .CO(_024_[3]),
    .S(_027_[2])
  );
  CC_ADDF _208_ (
    .A(\u_i2c_top.i2c_reg_cnt [3]),
    .B(1'h1),
    .CI(_024_[3]),
    .CO(_024_[4]),
    .S(_027_[3])
  );
  CC_ADDF _209_ (
    .A(\u_i2c_top.i2c_reg_cnt [4]),
    .B(1'h1),
    .CI(_024_[4]),
    .CO(_024_[5]),
    .S(_027_[4])
  );
  CC_ADDF _210_ (
    .A(\u_i2c_top.i2c_reg_cnt [5]),
    .B(1'h1),
    .CI(_024_[5]),
    .CO(_024_[6]),
    .S(_027_[5])
  );
  CC_ADDF _211_ (
    .A(\u_i2c_top.i2c_reg_cnt [6]),
    .B(1'h0),
    .CI(_024_[6]),
    .CO(_025_[6]),
    .S(_027_[6])
  );
  CC_ADDF _212_ (
    .A(1'h1),
    .B(cnt_100kHz[0]),
    .CI(1'h0),
    .CO(_028_[1]),
    .S(_030_[0])
  );
  CC_ADDF _213_ (
    .A(1'h0),
    .B(cnt_100kHz[1]),
    .CI(_028_[1]),
    .CO(_028_[2]),
    .S(_030_[1])
  );
  CC_ADDF _214_ (
    .A(1'h0),
    .B(cnt_100kHz[2]),
    .CI(_028_[2]),
    .CO(_028_[3]),
    .S(_030_[2])
  );
  CC_ADDF _215_ (
    .A(1'h0),
    .B(cnt_100kHz[3]),
    .CI(_028_[3]),
    .CO(_028_[4]),
    .S(_030_[3])
  );
  CC_ADDF _216_ (
    .A(1'h0),
    .B(cnt_100kHz[4]),
    .CI(_028_[4]),
    .CO(_028_[5]),
    .S(_030_[4])
  );
  CC_ADDF _217_ (
    .A(1'h0),
    .B(cnt_100kHz[5]),
    .CI(_028_[5]),
    .CO(_028_[6]),
    .S(_030_[5])
  );
  CC_ADDF _218_ (
    .A(1'h0),
    .B(cnt_100kHz[6]),
    .CI(_028_[6]),
    .CO(_029_[6]),
    .S(_030_[6])
  );
  CC_ADDF _219_ (
    .A(1'h1),
    .B(counter[0]),
    .CI(1'h0),
    .CO(_031_[1]),
    .S(_033_[0])
  );
  CC_ADDF _220_ (
    .A(1'h0),
    .B(counter[10]),
    .CI(_031_[10]),
    .CO(_031_[11]),
    .S(_033_[10])
  );
  CC_ADDF _221_ (
    .A(1'h0),
    .B(counter[11]),
    .CI(_031_[11]),
    .CO(_031_[12]),
    .S(_033_[11])
  );
  CC_ADDF _222_ (
    .A(1'h0),
    .B(counter[12]),
    .CI(_031_[12]),
    .CO(_031_[13]),
    .S(_033_[12])
  );
  CC_ADDF _223_ (
    .A(1'h0),
    .B(counter[13]),
    .CI(_031_[13]),
    .CO(_031_[14]),
    .S(_033_[13])
  );
  CC_ADDF _224_ (
    .A(1'h0),
    .B(counter[14]),
    .CI(_031_[14]),
    .CO(_031_[15]),
    .S(_033_[14])
  );
  CC_ADDF _225_ (
    .A(1'h0),
    .B(counter[15]),
    .CI(_031_[15]),
    .CO(_031_[16]),
    .S(_033_[15])
  );
  CC_ADDF _226_ (
    .A(1'h0),
    .B(counter[16]),
    .CI(_031_[16]),
    .CO(_031_[17]),
    .S(_033_[16])
  );
  CC_ADDF _227_ (
    .A(1'h0),
    .B(counter[17]),
    .CI(_031_[17]),
    .CO(_031_[18]),
    .S(_033_[17])
  );
  CC_ADDF _228_ (
    .A(1'h0),
    .B(counter[18]),
    .CI(_031_[18]),
    .CO(_031_[19]),
    .S(_033_[18])
  );
  CC_ADDF _229_ (
    .A(1'h0),
    .B(counter[19]),
    .CI(_031_[19]),
    .CO(_031_[20]),
    .S(_033_[19])
  );
  CC_ADDF _230_ (
    .A(1'h0),
    .B(counter[1]),
    .CI(_031_[1]),
    .CO(_031_[2]),
    .S(_033_[1])
  );
  CC_ADDF _231_ (
    .A(1'h0),
    .B(counter[20]),
    .CI(_031_[20]),
    .CO(_031_[21]),
    .S(_033_[20])
  );
  CC_ADDF _232_ (
    .A(1'h0),
    .B(counter[21]),
    .CI(_031_[21]),
    .CO(_031_[22]),
    .S(_033_[21])
  );
  CC_ADDF _233_ (
    .A(1'h0),
    .B(counter[22]),
    .CI(_031_[22]),
    .CO(_031_[23]),
    .S(_033_[22])
  );
  CC_ADDF _234_ (
    .A(1'h0),
    .B(counter[23]),
    .CI(_031_[23]),
    .CO(_032_[23]),
    .S(_033_[23])
  );
  CC_ADDF _235_ (
    .A(1'h0),
    .B(counter[2]),
    .CI(_031_[2]),
    .CO(_031_[3]),
    .S(_033_[2])
  );
  CC_ADDF _236_ (
    .A(1'h0),
    .B(counter[3]),
    .CI(_031_[3]),
    .CO(_031_[4]),
    .S(_033_[3])
  );
  CC_ADDF _237_ (
    .A(1'h0),
    .B(counter[4]),
    .CI(_031_[4]),
    .CO(_031_[5]),
    .S(_033_[4])
  );
  CC_ADDF _238_ (
    .A(1'h0),
    .B(counter[5]),
    .CI(_031_[5]),
    .CO(_031_[6]),
    .S(_033_[5])
  );
  CC_ADDF _239_ (
    .A(1'h0),
    .B(counter[6]),
    .CI(_031_[6]),
    .CO(_031_[7]),
    .S(_033_[6])
  );
  CC_ADDF _240_ (
    .A(1'h0),
    .B(counter[7]),
    .CI(_031_[7]),
    .CO(_031_[8]),
    .S(_033_[7])
  );
  CC_ADDF _241_ (
    .A(1'h0),
    .B(counter[8]),
    .CI(_031_[8]),
    .CO(_031_[9]),
    .S(_033_[8])
  );
  CC_ADDF _242_ (
    .A(1'h0),
    .B(counter[9]),
    .CI(_031_[9]),
    .CO(_031_[10]),
    .S(_033_[9])
  );
  CC_ADDF _243_ (
    .A(1'h1),
    .B(\u_i2c_top.i2c_reg_cnt [0]),
    .CI(1'h0),
    .CO(_034_[1]),
    .S(_037_[0])
  );
  CC_ADDF _244_ (
    .A(1'h0),
    .B(\u_i2c_top.i2c_reg_cnt [1]),
    .CI(_034_[1]),
    .CO(_034_[2]),
    .S(_037_[1])
  );
  CC_ADDF _245_ (
    .A(1'h0),
    .B(\u_i2c_top.i2c_reg_cnt [2]),
    .CI(_034_[2]),
    .CO(_034_[3]),
    .S(_037_[2])
  );
  CC_ADDF _246_ (
    .A(1'h0),
    .B(\u_i2c_top.i2c_reg_cnt [3]),
    .CI(_034_[3]),
    .CO(_034_[4]),
    .S(_037_[3])
  );
  CC_ADDF _247_ (
    .A(1'h0),
    .B(\u_i2c_top.i2c_reg_cnt [4]),
    .CI(_034_[4]),
    .CO(_034_[5]),
    .S(_037_[4])
  );
  CC_ADDF _248_ (
    .A(1'h0),
    .B(\u_i2c_top.i2c_reg_cnt [5]),
    .CI(_034_[5]),
    .CO(_034_[6]),
    .S(_037_[5])
  );
  CC_ADDF _249_ (
    .A(1'h0),
    .B(\u_i2c_top.i2c_reg_cnt [6]),
    .CI(_034_[6]),
    .CO(_035_[6]),
    .S(_037_[6])
  );
  CC_ADDF _250_ (
    .A(1'h1),
    .B(\u_i2c_top.u_i2c_ctrl.bit_cnt [0]),
    .CI(1'h0),
    .CO(_038_[1]),
    .S(_040_[0])
  );
  CC_ADDF _251_ (
    .A(1'h1),
    .B(\u_i2c_top.u_i2c_ctrl.bit_cnt [1]),
    .CI(_038_[1]),
    .CO(_038_[2]),
    .S(_040_[1])
  );
  CC_ADDF _252_ (
    .A(1'h1),
    .B(\u_i2c_top.u_i2c_ctrl.bit_cnt [2]),
    .CI(_038_[2]),
    .CO(_038_[3]),
    .S(_040_[2])
  );
  CC_ADDF _253_ (
    .A(1'h0),
    .B(\u_i2c_top.u_i2c_ctrl.bit_cnt [3]),
    .CI(_038_[3]),
    .CO(_039_[3]),
    .S(_040_[3])
  );
  CC_ADDF _254_ (
    .A(\u_i2c_top.u_i2c_ctrl.bit_cnt [0]),
    .B(1'h0),
    .CI(1'h1),
    .CO(_041_[1]),
    .S(\u_i2c_top.u_i2c_ctrl.bit_cnt_dec [0])
  );
  CC_ADDF _255_ (
    .A(\u_i2c_top.u_i2c_ctrl.bit_cnt [1]),
    .B(1'h1),
    .CI(_041_[1]),
    .CO(_041_[2]),
    .S(\u_i2c_top.u_i2c_ctrl.bit_cnt_dec [1])
  );
  CC_ADDF _256_ (
    .A(\u_i2c_top.u_i2c_ctrl.bit_cnt [2]),
    .B(1'h1),
    .CI(_041_[2]),
    .CO(_041_[3]),
    .S(\u_i2c_top.u_i2c_ctrl.bit_cnt_dec [2])
  );
  CC_ADDF _257_ (
    .A(\u_i2c_top.u_i2c_ctrl.bit_cnt [3]),
    .B(1'h1),
    .CI(_041_[3]),
    .CO(_042_[3]),
    .S(\u_i2c_top.u_i2c_ctrl.bit_cnt_dec [3])
  );
  CC_BUFG _258_ (
    .I(_043_),
    .O(\u_i2c_top.clk )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _259_ (
    .CLK(\u_i2c_top.clk ),
    .D(_033_[0]),
    .EN(1'h1),
    .Q(counter[0]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _260_ (
    .CLK(\u_i2c_top.clk ),
    .D(_033_[1]),
    .EN(1'h1),
    .Q(counter[1]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _261_ (
    .CLK(\u_i2c_top.clk ),
    .D(_033_[2]),
    .EN(1'h1),
    .Q(counter[2]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _262_ (
    .CLK(\u_i2c_top.clk ),
    .D(_033_[3]),
    .EN(1'h1),
    .Q(counter[3]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _263_ (
    .CLK(\u_i2c_top.clk ),
    .D(_033_[4]),
    .EN(1'h1),
    .Q(counter[4]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _264_ (
    .CLK(\u_i2c_top.clk ),
    .D(_033_[5]),
    .EN(1'h1),
    .Q(counter[5]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _265_ (
    .CLK(\u_i2c_top.clk ),
    .D(_033_[6]),
    .EN(1'h1),
    .Q(counter[6]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _266_ (
    .CLK(\u_i2c_top.clk ),
    .D(_033_[7]),
    .EN(1'h1),
    .Q(counter[7]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _267_ (
    .CLK(\u_i2c_top.clk ),
    .D(_033_[8]),
    .EN(1'h1),
    .Q(counter[8]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _268_ (
    .CLK(\u_i2c_top.clk ),
    .D(_033_[9]),
    .EN(1'h1),
    .Q(counter[9]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _269_ (
    .CLK(\u_i2c_top.clk ),
    .D(_033_[10]),
    .EN(1'h1),
    .Q(counter[10]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _270_ (
    .CLK(\u_i2c_top.clk ),
    .D(_033_[11]),
    .EN(1'h1),
    .Q(counter[11]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _271_ (
    .CLK(\u_i2c_top.clk ),
    .D(_033_[12]),
    .EN(1'h1),
    .Q(counter[12]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _272_ (
    .CLK(\u_i2c_top.clk ),
    .D(_033_[13]),
    .EN(1'h1),
    .Q(counter[13]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _273_ (
    .CLK(\u_i2c_top.clk ),
    .D(_033_[14]),
    .EN(1'h1),
    .Q(counter[14]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _274_ (
    .CLK(\u_i2c_top.clk ),
    .D(_033_[15]),
    .EN(1'h1),
    .Q(counter[15]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _275_ (
    .CLK(\u_i2c_top.clk ),
    .D(_033_[16]),
    .EN(1'h1),
    .Q(counter[16]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _276_ (
    .CLK(\u_i2c_top.clk ),
    .D(_033_[17]),
    .EN(1'h1),
    .Q(counter[17]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _277_ (
    .CLK(\u_i2c_top.clk ),
    .D(_033_[18]),
    .EN(1'h1),
    .Q(counter[18]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _278_ (
    .CLK(\u_i2c_top.clk ),
    .D(_033_[19]),
    .EN(1'h1),
    .Q(counter[19]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _279_ (
    .CLK(\u_i2c_top.clk ),
    .D(_033_[20]),
    .EN(1'h1),
    .Q(counter[20]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _280_ (
    .CLK(\u_i2c_top.clk ),
    .D(_033_[21]),
    .EN(1'h1),
    .Q(counter[21]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _281_ (
    .CLK(\u_i2c_top.clk ),
    .D(_033_[22]),
    .EN(1'h1),
    .Q(counter[22]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _282_ (
    .CLK(\u_i2c_top.clk ),
    .D(_033_[23]),
    .EN(1'h1),
    .Q(counter[23]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _283_ (
    .CLK(\u_i2c_top.clk ),
    .D(_061_[0]),
    .EN(1'h1),
    .Q(strobe_100kHz),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _284_ (
    .CLK(\u_i2c_top.clk ),
    .D(_000_[0]),
    .EN(1'h1),
    .Q(cnt_100kHz[0]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _285_ (
    .CLK(\u_i2c_top.clk ),
    .D(_000_[1]),
    .EN(1'h1),
    .Q(cnt_100kHz[1]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _286_ (
    .CLK(\u_i2c_top.clk ),
    .D(_000_[2]),
    .EN(1'h1),
    .Q(cnt_100kHz[2]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _287_ (
    .CLK(\u_i2c_top.clk ),
    .D(_000_[3]),
    .EN(1'h1),
    .Q(cnt_100kHz[3]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _288_ (
    .CLK(\u_i2c_top.clk ),
    .D(_000_[4]),
    .EN(1'h1),
    .Q(cnt_100kHz[4]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _289_ (
    .CLK(\u_i2c_top.clk ),
    .D(_000_[5]),
    .EN(1'h1),
    .Q(cnt_100kHz[5]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _290_ (
    .CLK(\u_i2c_top.clk ),
    .D(_000_[6]),
    .EN(1'h1),
    .Q(cnt_100kHz[6]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _291_ (
    .CLK(\u_i2c_top.clk ),
    .D(_045_[0]),
    .EN(_008_),
    .Q(\u_i2c_top.u_i2c_ctrl.post_state [0]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _292_ (
    .CLK(\u_i2c_top.clk ),
    .D(_045_[1]),
    .EN(_008_),
    .Q(\u_i2c_top.u_i2c_ctrl.post_state [1]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _293_ (
    .CLK(\u_i2c_top.clk ),
    .D(_045_[2]),
    .EN(_008_),
    .Q(\u_i2c_top.u_i2c_ctrl.post_state [2]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h1)
  ) _294_ (
    .CLK(\u_i2c_top.clk ),
    .D(_001_),
    .EN(1'h1),
    .Q(\u_i2c_top.u_i2c_ctrl.process_cnt [0]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _295_ (
    .CLK(\u_i2c_top.clk ),
    .D(_002_),
    .EN(1'h1),
    .Q(\u_i2c_top.u_i2c_ctrl.process_cnt [1]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _296_ (
    .CLK(\u_i2c_top.clk ),
    .D(_003_),
    .EN(1'h1),
    .Q(\u_i2c_top.u_i2c_ctrl.process_cnt [2]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _297_ (
    .CLK(\u_i2c_top.clk ),
    .D(_004_),
    .EN(1'h1),
    .Q(\u_i2c_top.u_i2c_ctrl.process_cnt [3]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _298_ (
    .CLK(\u_i2c_top.clk ),
    .D(_014_),
    .EN(_005_),
    .Q(\u_i2c_top.u_i2c_ctrl.acknowledge_bit ),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _299_ (
    .CLK(\u_i2c_top.clk ),
    .D(_044_[0]),
    .EN(_007_),
    .Q(\u_i2c_top.u_i2c_ctrl.bit_cnt [0]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _300_ (
    .CLK(\u_i2c_top.clk ),
    .D(_044_[1]),
    .EN(_007_),
    .Q(\u_i2c_top.u_i2c_ctrl.bit_cnt [1]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _301_ (
    .CLK(\u_i2c_top.clk ),
    .D(_044_[2]),
    .EN(_007_),
    .Q(\u_i2c_top.u_i2c_ctrl.bit_cnt [2]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _302_ (
    .CLK(\u_i2c_top.clk ),
    .D(_044_[3]),
    .EN(_007_),
    .Q(\u_i2c_top.u_i2c_ctrl.bit_cnt [3]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _303_ (
    .CLK(\u_i2c_top.clk ),
    .D(_049_[0]),
    .EN(_012_),
    .Q(\u_i2c_top.u_i2c_ctrl.state [0]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _304_ (
    .CLK(\u_i2c_top.clk ),
    .D(_049_[1]),
    .EN(_012_),
    .Q(\u_i2c_top.u_i2c_ctrl.state [1]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _305_ (
    .CLK(\u_i2c_top.clk ),
    .D(_049_[2]),
    .EN(_012_),
    .Q(\u_i2c_top.u_i2c_ctrl.state [2]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _306_ (
    .CLK(\u_i2c_top.clk ),
    .D(_015_),
    .EN(_006_),
    .Q(\u_i2c_top.u_i2c_ctrl.post_serial_data ),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h1)
  ) _307_ (
    .CLK(\u_i2c_top.clk ),
    .D(_047_),
    .EN(_009_),
    .Q(\u_i2c_top.i2c_sda_di ),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h1)
  ) _308_ (
    .CLK(\u_i2c_top.clk ),
    .D(_048_),
    .EN(_010_),
    .Q(\u_i2c_top.i2c_scl_di ),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _309_ (
    .CLK(\u_i2c_top.clk ),
    .D(_016_),
    .EN(_011_),
    .Q(\u_i2c_top.i2c_reg_done ),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _310_ (
    .CLK(\u_i2c_top.clk ),
    .D(_037_[0]),
    .EN(_013_),
    .Q(\u_i2c_top.i2c_reg_cnt [0]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _311_ (
    .CLK(\u_i2c_top.clk ),
    .D(_037_[1]),
    .EN(_013_),
    .Q(\u_i2c_top.i2c_reg_cnt [1]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _312_ (
    .CLK(\u_i2c_top.clk ),
    .D(_037_[2]),
    .EN(_013_),
    .Q(\u_i2c_top.i2c_reg_cnt [2]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _313_ (
    .CLK(\u_i2c_top.clk ),
    .D(_037_[3]),
    .EN(_013_),
    .Q(\u_i2c_top.i2c_reg_cnt [3]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _314_ (
    .CLK(\u_i2c_top.clk ),
    .D(_037_[4]),
    .EN(_013_),
    .Q(\u_i2c_top.i2c_reg_cnt [4]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _315_ (
    .CLK(\u_i2c_top.clk ),
    .D(_037_[5]),
    .EN(_013_),
    .Q(\u_i2c_top.i2c_reg_cnt [5]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _316_ (
    .CLK(\u_i2c_top.clk ),
    .D(_037_[6]),
    .EN(_013_),
    .Q(\u_i2c_top.i2c_reg_cnt [6]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h1),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _317_ (
    .CLK(\u_i2c_top.clk ),
    .D(1'h1),
    .EN(_064_[3]),
    .Q(\u_i2c_top.u_i2c_ctrl.slave_address_plus_rw [6]),
    .SR(\u_i2c_top.areset_n )
  );
  CC_MX4 _318_ (
    .D0(\u_i2c_top.i2c_reg_addr [0]),
    .D1(\u_i2c_top.i2c_reg_addr [1]),
    .D2(\u_i2c_top.i2c_reg_addr [2]),
    .D3(\u_i2c_top.i2c_reg_addr [3]),
    .S0(\u_i2c_top.u_i2c_ctrl.bit_cnt_dec [0]),
    .S1(\u_i2c_top.u_i2c_ctrl.bit_cnt_dec [1]),
    .Y(_051_[0])
  );
  CC_MX4 _319_ (
    .D0(\u_i2c_top.i2c_reg_addr [4]),
    .D1(\u_i2c_top.i2c_reg_addr [5]),
    .D2(\u_i2c_top.i2c_reg_addr [6]),
    .D3(\u_i2c_top.i2c_reg_addr [7]),
    .S0(\u_i2c_top.u_i2c_ctrl.bit_cnt_dec [0]),
    .S1(\u_i2c_top.u_i2c_ctrl.bit_cnt_dec [1]),
    .Y(_051_[4])
  );
  CC_MX4 _320_ (
    .D0(\u_i2c_top.i2c_reg_addr [8]),
    .D1(\u_i2c_top.i2c_reg_addr [9]),
    .D2(\u_i2c_top.i2c_reg_addr [10]),
    .D3(\u_i2c_top.i2c_reg_addr [11]),
    .S0(\u_i2c_top.u_i2c_ctrl.bit_cnt_dec [0]),
    .S1(\u_i2c_top.u_i2c_ctrl.bit_cnt_dec [1]),
    .Y(_051_[8])
  );
  CC_MX4 _321_ (
    .D0(\u_i2c_top.i2c_reg_addr [12]),
    .D1(\u_i2c_top.i2c_reg_addr [13]),
    .D2(\u_i2c_top.i2c_reg_addr [14]),
    .D3(1'h0),
    .S0(\u_i2c_top.u_i2c_ctrl.bit_cnt_dec [0]),
    .S1(\u_i2c_top.u_i2c_ctrl.bit_cnt_dec [1]),
    .Y(_051_[12])
  );
  CC_MX4 _322_ (
    .D0(_051_[0]),
    .D1(_051_[4]),
    .D2(_051_[8]),
    .D3(_051_[12]),
    .S0(\u_i2c_top.u_i2c_ctrl.bit_cnt_dec [2]),
    .S1(\u_i2c_top.u_i2c_ctrl.bit_cnt_dec [3]),
    .Y(_046_[0])
  );
  CC_MX4 _323_ (
    .D0(\u_i2c_top.i2c_reg_addr [0]),
    .D1(\u_i2c_top.i2c_reg_addr [1]),
    .D2(\u_i2c_top.i2c_reg_addr [2]),
    .D3(\u_i2c_top.i2c_reg_addr [3]),
    .S0(_040_[0]),
    .S1(_040_[1]),
    .Y(_050_[0])
  );
  CC_MX4 _324_ (
    .D0(\u_i2c_top.i2c_reg_addr [4]),
    .D1(\u_i2c_top.i2c_reg_addr [5]),
    .D2(\u_i2c_top.i2c_reg_addr [6]),
    .D3(\u_i2c_top.i2c_reg_addr [7]),
    .S0(_040_[0]),
    .S1(_040_[1]),
    .Y(_050_[4])
  );
  CC_MX4 _325_ (
    .D0(\u_i2c_top.i2c_reg_addr [8]),
    .D1(\u_i2c_top.i2c_reg_addr [9]),
    .D2(\u_i2c_top.i2c_reg_addr [10]),
    .D3(\u_i2c_top.i2c_reg_addr [11]),
    .S0(_040_[0]),
    .S1(_040_[1]),
    .Y(_050_[8])
  );
  CC_MX4 _326_ (
    .D0(\u_i2c_top.i2c_reg_addr [12]),
    .D1(\u_i2c_top.i2c_reg_addr [13]),
    .D2(\u_i2c_top.i2c_reg_addr [14]),
    .D3(1'h0),
    .S0(_040_[0]),
    .S1(_040_[1]),
    .Y(_050_[12])
  );
  CC_MX4 _327_ (
    .D0(_050_[0]),
    .D1(_050_[4]),
    .D2(_050_[8]),
    .D3(_050_[12]),
    .S0(_040_[2]),
    .S1(_040_[3]),
    .Y(_046_[1])
  );
  CC_MX4 _328_ (
    .D0(1'h0),
    .D1(_022_),
    .D2(_022_),
    .D3(_023_),
    .S0(\u_i2c_top.u_i2c_ctrl.bit_cnt_dec [1]),
    .S1(\u_i2c_top.u_i2c_ctrl.bit_cnt_dec [2]),
    .Y(_046_[3])
  );
  CC_MX4 _329_ (
    .D0(_096_),
    .D1(_055_[1]),
    .D2(_080_),
    .D3(_017_),
    .S0(\u_i2c_top.i2c_reg_cnt [2]),
    .S1(\u_i2c_top.i2c_reg_cnt [3]),
    .Y(_075_[0])
  );
  CC_MX4 _330_ (
    .D0(1'h1),
    .D1(_053_[1]),
    .D2(_074_),
    .D3(_080_),
    .S0(\u_i2c_top.i2c_reg_cnt [2]),
    .S1(\u_i2c_top.i2c_reg_cnt [3]),
    .Y(_076_[0])
  );
  CC_MX4 _331_ (
    .D0(1'h1),
    .D1(_096_),
    .D2(_096_),
    .D3(_080_),
    .S0(\u_i2c_top.i2c_reg_cnt [2]),
    .S1(\u_i2c_top.i2c_reg_cnt [3]),
    .Y(_086_[0])
  );
  CC_MX4 _332_ (
    .D0(_019_),
    .D1(_026_[1]),
    .D2(_080_),
    .D3(1'h1),
    .S0(\u_i2c_top.i2c_reg_cnt [2]),
    .S1(\u_i2c_top.i2c_reg_cnt [3]),
    .Y(_078_[0])
  );
  CC_MX4 _333_ (
    .D0(_036_[0]),
    .D1(_019_),
    .D2(\u_i2c_top.i2c_reg_cnt [0]),
    .D3(_017_),
    .S0(\u_i2c_top.i2c_reg_cnt [2]),
    .S1(\u_i2c_top.i2c_reg_cnt [3]),
    .Y(_081_[0])
  );
  CC_MX4 _334_ (
    .D0(_020_),
    .D1(\u_i2c_top.i2c_reg_cnt [1]),
    .D2(\u_i2c_top.i2c_reg_cnt [1]),
    .D3(_074_),
    .S0(\u_i2c_top.i2c_reg_cnt [2]),
    .S1(\u_i2c_top.i2c_reg_cnt [3]),
    .Y(_095_[2])
  );
  CC_MX4 _335_ (
    .D0(_018_),
    .D1(_080_),
    .D2(1'h0),
    .D3(_018_),
    .S0(\u_i2c_top.i2c_reg_cnt [2]),
    .S1(\u_i2c_top.i2c_reg_cnt [3]),
    .Y(_089_[0])
  );
  CC_MX4 _336_ (
    .D0(_017_),
    .D1(_096_),
    .D2(_018_),
    .D3(_019_),
    .S0(\u_i2c_top.i2c_reg_cnt [2]),
    .S1(\u_i2c_top.i2c_reg_cnt [3]),
    .Y(_079_[1])
  );
  CC_MX4 _337_ (
    .D0(1'h1),
    .D1(\u_i2c_top.i2c_reg_cnt [0]),
    .D2(1'h0),
    .D3(_021_),
    .S0(\u_i2c_top.i2c_reg_cnt [2]),
    .S1(\u_i2c_top.i2c_reg_cnt [3]),
    .Y(_088_[1])
  );
  CC_MX4 _338_ (
    .D0(_053_[1]),
    .D1(\u_i2c_top.i2c_reg_cnt [1]),
    .D2(_080_),
    .D3(_096_),
    .S0(\u_i2c_top.i2c_reg_cnt [2]),
    .S1(\u_i2c_top.i2c_reg_cnt [3]),
    .Y(_087_[1])
  );
  CC_MX4 _339_ (
    .D0(_080_),
    .D1(1'h0),
    .D2(_026_[1]),
    .D3(_053_[1]),
    .S0(\u_i2c_top.i2c_reg_cnt [2]),
    .S1(\u_i2c_top.i2c_reg_cnt [3]),
    .Y(_054_[0])
  );
  CC_IBUF _340_ (
    .I(areset_n),
    .Y(\u_i2c_top.areset_n )
  );
  CC_IBUF _341_ (
    .I(clk_10MHz),
    .Y(_043_)
  );
  CC_OBUF _342_ (
    .A(counter[23]),
    .O(led)
  );
  CC_IOBUF #(
    .DELAY_IBF(4'h0),
    .DELAY_OBF(4'h0),
    .DRIVE("12"),
    .FF_IBF(1'h0),
    .FF_OBF(1'h0),
    .KEEPER(32'sd0),
    .PIN_NAME("IO_EA_A0"),
    .PULLDOWN(32'sd0),
    .PULLUP(32'sd0),
    .SCHMITT_TRIGGER(32'sd0),
    .SLEW("SLOW"),
    .V_IO("2.5")
  ) \u_i2c_top.i2c_iobuf_scl  (
    .A(1'h0),
    .IO(i2c_scl),
    .T(\u_i2c_top.i2c_scl_di ),
    .Y(\u_i2c_top.i2c_scl_do )
  );
  CC_IOBUF #(
    .DELAY_IBF(4'h0),
    .DELAY_OBF(4'h0),
    .DRIVE("12"),
    .FF_IBF(1'h0),
    .FF_OBF(1'h0),
    .KEEPER(32'sd0),
    .PIN_NAME("IO_EA_B0"),
    .PULLDOWN(32'sd0),
    .PULLUP(32'sd0),
    .SCHMITT_TRIGGER(32'sd0),
    .SLEW("SLOW"),
    .V_IO("2.5")
  ) \u_i2c_top.i2c_iobuf_sda  (
    .A(1'h0),
    .IO(i2c_sda),
    .T(\u_i2c_top.i2c_sda_di ),
    .Y(\u_i2c_top.i2c_sda_do )
  );
  assign _024_[0] = 1'h1;
  assign _025_[5:0] = _024_[6:1];
  assign { _026_[6], _026_[0] } = { \u_i2c_top.i2c_reg_cnt [6], \u_i2c_top.i2c_reg_cnt [0] };
  assign _028_[0] = 1'h0;
  assign _029_[5:0] = _028_[6:1];
  assign _031_[0] = 1'h0;
  assign _032_[22:0] = _031_[23:1];
  assign _034_[0] = 1'h0;
  assign _035_[5:0] = _034_[6:1];
  assign _036_[6:1] = \u_i2c_top.i2c_reg_cnt [6:1];
  assign _038_[0] = 1'h0;
  assign _039_[2:0] = _038_[3:1];
  assign _041_[0] = 1'h1;
  assign _042_[2:0] = _041_[3:1];
  assign { _046_[4], _046_[2] } = { 1'h0, \u_i2c_top.u_i2c_ctrl.post_serial_data  };
  assign _052_[1:0] = { \u_i2c_top.u_i2c_ctrl.state [0], strobe_100kHz };
  assign { _053_[2], _053_[0] } = { \u_i2c_top.i2c_reg_cnt [4], \u_i2c_top.i2c_reg_cnt [2] };
  assign _054_[1] = \u_i2c_top.i2c_reg_cnt [4];
  assign { _055_[2], _055_[0] } = { \u_i2c_top.i2c_reg_cnt [4], \u_i2c_top.i2c_reg_cnt [2] };
  assign _056_[1] = _045_[0];
  assign _057_[1] = _056_[0];
  assign _058_[3] = _045_[2];
  assign _059_[0] = \u_i2c_top.u_i2c_ctrl.state [0];
  assign _060_[3:1] = { cnt_100kHz[6:5], cnt_100kHz[1] };
  assign _061_[1] = _030_[4];
  assign _062_[3:1] = { \u_i2c_top.u_i2c_ctrl.state [0], \u_i2c_top.u_i2c_ctrl.state [1], \u_i2c_top.u_i2c_ctrl.state [2] };
  assign _063_[0] = \u_i2c_top.u_i2c_ctrl.state [0];
  assign _064_[2:0] = { strobe_100kHz, \u_i2c_top.u_i2c_ctrl.process_cnt [0], \u_i2c_top.u_i2c_ctrl.process_cnt [2] };
  assign _065_[1:0] = { _045_[0], _046_[1] };
  assign _066_[2:0] = { _046_[0], _046_[3], _057_[0] };
  assign _068_[2:0] = _058_[2:0];
  assign { _069_[2], _069_[0] } = { _064_[3], _025_[6] };
  assign _070_[1:0] = { _056_[0], _045_[2] };
  assign _071_[1] = \u_i2c_top.u_i2c_ctrl.process_cnt [1];
  assign { _072_[2], _072_[0] } = { _045_[2], _056_[0] };
  assign _075_[2:1] = { _054_[2], \u_i2c_top.i2c_reg_cnt [4] };
  assign _076_[3:1] = { _054_[3:2], \u_i2c_top.i2c_reg_cnt [4] };
  assign _077_[1:0] = { \u_i2c_top.u_i2c_ctrl.state [0], _063_[1] };
  assign _078_[2:1] = { _054_[3], \u_i2c_top.i2c_reg_cnt [4] };
  assign _079_[0] = \u_i2c_top.i2c_reg_cnt [4];
  assign _081_[2:1] = { _054_[3], \u_i2c_top.i2c_reg_cnt [4] };
  assign _082_[1] = \u_i2c_top.u_i2c_ctrl.process_cnt [0];
  assign { _083_[2], _083_[0] } = { _065_[2], \u_i2c_top.u_i2c_ctrl.post_state [1] };
  assign _084_[0] = \u_i2c_top.i2c_reg_cnt [0];
  assign { _085_[3], _085_[1:0] } = { \u_i2c_top.i2c_reg_cnt [4], _053_[1], \u_i2c_top.i2c_reg_cnt [2] };
  assign _086_[2:1] = { _054_[2], \u_i2c_top.i2c_reg_cnt [4] };
  assign { _087_[2], _087_[0] } = { _054_[3], \u_i2c_top.i2c_reg_cnt [4] };
  assign { _088_[2], _088_[0] } = { _078_[3], \u_i2c_top.i2c_reg_cnt [4] };
  assign _089_[3:1] = { _054_[3], _079_[2], \u_i2c_top.i2c_reg_cnt [4] };
  assign _090_[0] = \u_i2c_top.i2c_reg_cnt [3];
  assign { _091_[3], _091_[1:0] } = { _064_[3], _065_[2], _072_[1] };
  assign { _092_[3], _092_[1:0] } = { _064_[3], \u_i2c_top.u_i2c_ctrl.process_cnt [1], strobe_100kHz };
  assign _093_[1] = \u_i2c_top.u_i2c_ctrl.process_cnt [3];
  assign _094_[2:1] = { _054_[2], _090_[1] };
  assign { _095_[3], _095_[1:0] } = { \u_i2c_top.i2c_reg_cnt [4], \u_i2c_top.i2c_reg_cnt [0], \u_i2c_top.i2c_reg_cnt [2] };
  assign \u_i2c_top.i2c_reg_addr [15] = 1'h0;
  assign \u_i2c_top.u_i2c_ctrl.post_state [3] = 1'h0;
  assign { \u_i2c_top.u_i2c_ctrl.slave_address_plus_rw [7], \u_i2c_top.u_i2c_ctrl.slave_address_plus_rw [5:0] } = { 1'h0, \u_i2c_top.u_i2c_ctrl.slave_address_plus_rw [6], 1'h0, \u_i2c_top.u_i2c_ctrl.slave_address_plus_rw [6], 3'h0 };
  assign \u_i2c_top.u_i2c_ctrl.state [3] = 1'h0;
endmodule
