/* Generated by Yosys 0.43+22 (git sha1 118b2829d, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */

module ila_top(i_sclk_ILA, i_mosi_ILA, o_miso_ILA, clk, led, i_ss_ILA);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire [24:0] _118_;
  wire [24:0] _119_;
  wire [10:0] _120_;
  wire [10:0] _121_;
  wire [10:0] _122_;
  wire [10:0] _123_;
  wire [10:0] _124_;
  wire [10:0] _125_;
  wire [10:0] _126_;
  wire [10:0] _127_;
  wire [10:0] _128_;
  wire [10:0] _129_;
  wire [10:0] _130_;
  wire [10:0] _131_;
  wire _132_;
  wire _133_;
  wire [14:0] _134_;
  wire [4:0] _135_;
  wire [19:0] _136_;
  wire _137_;
  wire [2:0] _138_;
  wire [3:0] _139_;
  wire [3:0] _140_;
  wire [1:0] _141_;
  wire [2:0] _142_;
  wire [1:0] _143_;
  wire [2:0] _144_;
  wire [2:0] _145_;
  wire [3:0] _146_;
  wire [3:0] _147_;
  wire [3:0] _148_;
  wire [3:0] _149_;
  wire [2:0] _150_;
  wire \DUT.ILA_rst ;
  wire [24:0] \DUT._1_ ;
  wire \DUT.clk ;
  wire \DUT.clk0 ;
  wire \DUT.clk180 ;
  wire \DUT.clk270 ;
  wire \DUT.clk90 ;
  wire [24:0] \DUT.counter ;
  wire \DUT.led ;
  wire \DUT.usr_pll_lock ;
  wire \DUT.usr_pll_lock_stdy ;
  wire \DUT.usr_ref_out ;
  wire [3:0] \change_trigger.i_nib ;
  wire \change_trigger.o_hold ;
  input clk;
  wire clk;
  wire clk0;
  wire clk180;
  wire clk270;
  wire clk90;
  wire clk_reset_check;
  wire \command_read.o_hold ;
  wire conf_trigger_start;
  input i_mosi_ILA;
  wire i_mosi_ILA;
  input i_sclk_ILA;
  wire i_sclk_ILA;
  input i_ss_ILA;
  wire i_ss_ILA;
  wire ila_reset_register_clk;
  wire ila_reset_register_sclk;
  wire ila_reset_signal;
  output led;
  wire led;
  wire [4:0] \mem_control.BRAM_do_tmp[0] ;
  wire [10:0] \mem_control.addr_cnt_rd ;
  wire [10:0] \mem_control.addr_cnt_wd ;
  wire [10:0] \mem_control.addr_cnt_wd_pip ;
  wire [3:0] \mem_control.genblk4.send_nib_sync ;
  wire \mem_control.i_read_active ;
  wire \mem_control.i_reset ;
  wire \mem_control.i_slave_end_byte_post_edge ;
  wire \mem_control.i_trigger_triggered ;
  wire \mem_control.make_wd_cnt ;
  wire \mem_control.o_write_done ;
  wire \mem_control.save_before_done ;
  wire \mem_control.save_before_done_edge.i_signal ;
  wire \mem_control.save_before_done_edge.o_nedge_edge ;
  wire \mem_control.save_before_done_edge.signal_old ;
  wire \mem_control.wd_cnt_done_edge.i_signal ;
  wire [10:0] \mem_control.wd_counter ;
  wire \mem_control.write_done_edge.i_signal ;
  wire \mem_control.write_done_edge.o_nedge_edge ;
  wire \mem_control.write_done_edge.signal_old ;
  output o_miso_ILA;
  wire o_miso_ILA;
  wire read_active_pipe;
  wire sclk_reset_check;
  wire [1:0] \spi_passiv.bit_cnt ;
  wire \spi_passiv.i_mosi ;
  wire \spi_passiv.i_sclk ;
  wire \spi_passiv.i_ss ;
  wire \spi_passiv.o_miso ;
  wire [3:0] \spi_passiv.rx_shift_reg ;
  wire [3:0] \spi_passiv.tx_shift_reg ;
  wire [1:0] state_trigger_conf;
  wire trigger;
  wire [1:0] trigger_activation;
  wire [5:0] trigger_column;
  wire \trigger_edge.o_nedge_edge ;
  wire \trigger_edge.o_post_edge ;
  wire \trigger_edge.signal_new ;
  wire \trigger_edge.signal_old ;
  wire trigger_nedge_edge;
  wire [1:0] trigger_pipe;
  wire trigger_post_edge;
  wire usr_pll_lock_1;
  wire usr_pll_lock_stdy_1;
  wire usr_ref_out_1;
  CC_LUT4 #(
    .INIT(16'h0c0a)
  ) _151_ (
    .I0(\change_trigger.i_nib [2]),
    .I1(\spi_passiv.rx_shift_reg [2]),
    .I2(\spi_passiv.i_ss ),
    .I3(_140_[3]),
    .O(_030_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _152_ (
    .I0(\spi_passiv.bit_cnt [1]),
    .I1(\spi_passiv.bit_cnt [0]),
    .O(_140_[3])
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _153_ (
    .I0(\mem_control.i_read_active ),
    .I1(\mem_control.BRAM_do_tmp[0] [1]),
    .O(_092_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _154_ (
    .I0(\DUT.ILA_rst ),
    .I1(\DUT._1_ [0]),
    .O(_034_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _155_ (
    .I0(ila_reset_register_clk),
    .I1(\trigger_edge.o_nedge_edge ),
    .O(_004_)
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _156_ (
    .I0(\spi_passiv.i_ss ),
    .I1(\spi_passiv.rx_shift_reg [2]),
    .O(_064_)
  );
  CC_LUT3 #(
    .INIT(8'h40)
  ) _157_ (
    .I0(\trigger_edge.signal_old ),
    .I1(\trigger_edge.signal_new ),
    .I2(ila_reset_register_clk),
    .O(_060_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _158_ (
    .I0(\DUT.ILA_rst ),
    .I1(\DUT._1_ [24]),
    .O(_058_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _159_ (
    .I0(\DUT.ILA_rst ),
    .I1(\DUT._1_ [23]),
    .O(_057_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _160_ (
    .I0(\DUT.ILA_rst ),
    .I1(\DUT._1_ [22]),
    .O(_056_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _161_ (
    .I0(\DUT.ILA_rst ),
    .I1(\DUT._1_ [11]),
    .O(_045_)
  );
  CC_LUT3 #(
    .INIT(8'h40)
  ) _162_ (
    .I0(conf_trigger_start),
    .I1(_142_[1]),
    .I2(\mem_control.i_slave_end_byte_post_edge ),
    .O(_059_)
  );
  CC_LUT4 #(
    .INIT(16'h1000)
  ) _163_ (
    .I0(\change_trigger.i_nib [2]),
    .I1(\change_trigger.i_nib [1]),
    .I2(\change_trigger.i_nib [0]),
    .I3(\change_trigger.i_nib [3]),
    .O(_142_[1])
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _164_ (
    .I0(\spi_passiv.i_ss ),
    .I1(\spi_passiv.rx_shift_reg [0]),
    .O(_062_)
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _165_ (
    .I0(_141_[0]),
    .I1(_141_[1]),
    .O(_065_)
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _166_ (
    .I0(\spi_passiv.i_ss ),
    .I1(_140_[3]),
    .O(_141_[1])
  );
  CC_LUT4 #(
    .INIT(16'h770f)
  ) _167_ (
    .I0(\mem_control.i_read_active ),
    .I1(\mem_control.genblk4.send_nib_sync [0]),
    .I2(\spi_passiv.rx_shift_reg [0]),
    .I3(\mem_control.o_write_done ),
    .O(_141_[0])
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _168_ (
    .I0(_128_[9]),
    .I1(\mem_control.addr_cnt_wd [9]),
    .I2(\mem_control.o_write_done ),
    .I3(\mem_control.i_reset ),
    .O(_089_)
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _169_ (
    .I0(\spi_passiv.i_ss ),
    .I1(\spi_passiv.i_mosi ),
    .O(_061_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _170_ (
    .I0(\DUT.ILA_rst ),
    .I1(\DUT._1_ [7]),
    .O(_041_)
  );
  CC_LUT3 #(
    .INIT(8'hbe)
  ) _171_ (
    .I0(\spi_passiv.i_ss ),
    .I1(\spi_passiv.bit_cnt [1]),
    .I2(\spi_passiv.bit_cnt [0]),
    .O(_024_)
  );
  CC_LUT3 #(
    .INIT(8'h40)
  ) _172_ (
    .I0(\mem_control.save_before_done_edge.i_signal ),
    .I1(\mem_control.i_reset ),
    .I2(\mem_control.save_before_done_edge.signal_old ),
    .O(_066_)
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _173_ (
    .I0(\mem_control.addr_cnt_wd [0]),
    .I1(\mem_control.addr_cnt_wd_pip [0]),
    .I2(\mem_control.o_write_done ),
    .I3(\mem_control.i_reset ),
    .O(_069_)
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _174_ (
    .I0(_128_[10]),
    .I1(\mem_control.wd_cnt_done_edge.i_signal ),
    .I2(\mem_control.o_write_done ),
    .I3(\mem_control.i_reset ),
    .O(_090_)
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _175_ (
    .I0(_128_[8]),
    .I1(\mem_control.addr_cnt_wd [8]),
    .I2(\mem_control.o_write_done ),
    .I3(\mem_control.i_reset ),
    .O(_088_)
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _176_ (
    .I0(_128_[7]),
    .I1(\mem_control.addr_cnt_wd [7]),
    .I2(\mem_control.o_write_done ),
    .I3(\mem_control.i_reset ),
    .O(_087_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _177_ (
    .I0(\DUT.ILA_rst ),
    .I1(\DUT._1_ [18]),
    .O(_052_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _178_ (
    .I0(\DUT.ILA_rst ),
    .I1(\DUT._1_ [17]),
    .O(_051_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _179_ (
    .I0(\DUT.ILA_rst ),
    .I1(\DUT._1_ [21]),
    .O(_055_)
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _180_ (
    .I0(_128_[6]),
    .I1(\mem_control.save_before_done_edge.i_signal ),
    .I2(\mem_control.o_write_done ),
    .I3(\mem_control.i_reset ),
    .O(_086_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _181_ (
    .I0(\DUT.ILA_rst ),
    .I1(\DUT._1_ [20]),
    .O(_054_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _182_ (
    .I0(\DUT.ILA_rst ),
    .I1(\DUT._1_ [16]),
    .O(_050_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _183_ (
    .I0(\DUT.ILA_rst ),
    .I1(\DUT._1_ [19]),
    .O(_053_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _184_ (
    .I0(\DUT.ILA_rst ),
    .I1(\DUT._1_ [15]),
    .O(_049_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _185_ (
    .I0(\DUT.ILA_rst ),
    .I1(\DUT._1_ [8]),
    .O(_042_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _186_ (
    .I0(\DUT.ILA_rst ),
    .I1(\DUT._1_ [9]),
    .O(_043_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _187_ (
    .I0(\DUT.ILA_rst ),
    .I1(\DUT._1_ [2]),
    .O(_036_)
  );
  CC_LUT4 #(
    .INIT(16'hac00)
  ) _188_ (
    .I0(_131_[1]),
    .I1(\mem_control.wd_counter [1]),
    .I2(\mem_control.make_wd_cnt ),
    .I3(\mem_control.i_reset ),
    .O(_094_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _189_ (
    .I0(\DUT.ILA_rst ),
    .I1(\DUT._1_ [3]),
    .O(_037_)
  );
  CC_LUT3 #(
    .INIT(8'h60)
  ) _190_ (
    .I0(_143_[0]),
    .I1(state_trigger_conf[1]),
    .I2(ila_reset_register_sclk),
    .O(_019_)
  );
  CC_LUT3 #(
    .INIT(8'h80)
  ) _191_ (
    .I0(conf_trigger_start),
    .I1(state_trigger_conf[0]),
    .I2(\mem_control.i_slave_end_byte_post_edge ),
    .O(_143_[0])
  );
  CC_LUT4 #(
    .INIT(16'h0e00)
  ) _192_ (
    .I0(\change_trigger.o_hold ),
    .I1(conf_trigger_start),
    .I2(\mem_control.i_reset ),
    .I3(ila_reset_register_sclk),
    .O(_020_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _193_ (
    .I0(\DUT.ILA_rst ),
    .I1(\DUT._1_ [6]),
    .O(_040_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _194_ (
    .I0(\DUT.ILA_rst ),
    .I1(\DUT._1_ [10]),
    .O(_044_)
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _195_ (
    .I0(_128_[5]),
    .I1(\mem_control.addr_cnt_wd [5]),
    .I2(\mem_control.o_write_done ),
    .I3(\mem_control.i_reset ),
    .O(_085_)
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _196_ (
    .I0(_128_[4]),
    .I1(\mem_control.addr_cnt_wd [4]),
    .I2(\mem_control.o_write_done ),
    .I3(\mem_control.i_reset ),
    .O(_084_)
  );
  CC_LUT4 #(
    .INIT(16'h7800)
  ) _197_ (
    .I0(conf_trigger_start),
    .I1(\mem_control.i_slave_end_byte_post_edge ),
    .I2(state_trigger_conf[0]),
    .I3(ila_reset_register_sclk),
    .O(_018_)
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _198_ (
    .I0(_128_[3]),
    .I1(\mem_control.addr_cnt_wd [3]),
    .I2(\mem_control.o_write_done ),
    .I3(\mem_control.i_reset ),
    .O(_083_)
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _199_ (
    .I0(trigger_activation[0]),
    .I1(\change_trigger.i_nib [0]),
    .I2(_144_[1]),
    .I3(ila_reset_register_sclk),
    .O(_013_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _200_ (
    .I0(_143_[0]),
    .I1(state_trigger_conf[1]),
    .O(_144_[1])
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _201_ (
    .I0(_128_[2]),
    .I1(\mem_control.addr_cnt_wd [2]),
    .I2(\mem_control.o_write_done ),
    .I3(\mem_control.i_reset ),
    .O(_082_)
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _202_ (
    .I0(_128_[1]),
    .I1(\mem_control.addr_cnt_wd [1]),
    .I2(\mem_control.o_write_done ),
    .I3(\mem_control.i_reset ),
    .O(_081_)
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _203_ (
    .I0(trigger_activation[1]),
    .I1(\change_trigger.i_nib [1]),
    .I2(_144_[1]),
    .I3(ila_reset_register_sclk),
    .O(_014_)
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _204_ (
    .I0(_128_[0]),
    .I1(\mem_control.addr_cnt_wd [0]),
    .I2(\mem_control.o_write_done ),
    .I3(\mem_control.i_reset ),
    .O(_080_)
  );
  CC_LUT4 #(
    .INIT(16'h0e00)
  ) _205_ (
    .I0(\command_read.o_hold ),
    .I1(read_active_pipe),
    .I2(\mem_control.i_read_active ),
    .I3(ila_reset_register_sclk),
    .O(_011_)
  );
  CC_LUT3 #(
    .INIT(8'he0)
  ) _206_ (
    .I0(\mem_control.i_reset ),
    .I1(_144_[1]),
    .I2(ila_reset_register_sclk),
    .O(_012_)
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _207_ (
    .I0(trigger_column[2]),
    .I1(\change_trigger.i_nib [2]),
    .I2(_139_[2]),
    .I3(ila_reset_register_sclk),
    .O(_017_)
  );
  CC_LUT4 #(
    .INIT(16'h4000)
  ) _208_ (
    .I0(state_trigger_conf[0]),
    .I1(conf_trigger_start),
    .I2(state_trigger_conf[1]),
    .I3(\mem_control.i_slave_end_byte_post_edge ),
    .O(_139_[2])
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _209_ (
    .I0(trigger_column[0]),
    .I1(\change_trigger.i_nib [0]),
    .I2(_139_[2]),
    .I3(ila_reset_register_sclk),
    .O(_015_)
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _210_ (
    .I0(\mem_control.wd_cnt_done_edge.i_signal ),
    .I1(\mem_control.addr_cnt_wd_pip [10]),
    .I2(\mem_control.o_write_done ),
    .I3(\mem_control.i_reset ),
    .O(_079_)
  );
  CC_LUT4 #(
    .INIT(16'h0c0a)
  ) _211_ (
    .I0(\change_trigger.i_nib [3]),
    .I1(\spi_passiv.rx_shift_reg [3]),
    .I2(\spi_passiv.i_ss ),
    .I3(_140_[3]),
    .O(_031_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _212_ (
    .I0(\DUT.ILA_rst ),
    .I1(\DUT._1_ [1]),
    .O(_035_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _213_ (
    .I0(\DUT.ILA_rst ),
    .I1(\DUT._1_ [5]),
    .O(_039_)
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _214_ (
    .I0(\mem_control.wd_counter [2]),
    .I1(_131_[2]),
    .I2(\mem_control.make_wd_cnt ),
    .I3(\mem_control.i_reset ),
    .O(_095_)
  );
  CC_LUT3 #(
    .INIT(8'h40)
  ) _215_ (
    .I0(\mem_control.write_done_edge.i_signal ),
    .I1(\mem_control.i_reset ),
    .I2(\mem_control.write_done_edge.signal_old ),
    .O(_032_)
  );
  CC_LUT4 #(
    .INIT(16'h0e00)
  ) _216_ (
    .I0(clk_reset_check),
    .I1(ila_reset_register_clk),
    .I2(ila_reset_signal),
    .I3(\DUT.ILA_rst ),
    .O(_022_)
  );
  CC_LUT4 #(
    .INIT(16'hf800)
  ) _217_ (
    .I0(read_active_pipe),
    .I1(\mem_control.i_slave_end_byte_post_edge ),
    .I2(\mem_control.i_read_active ),
    .I3(ila_reset_register_sclk),
    .O(_010_)
  );
  CC_LUT4 #(
    .INIT(16'h0c0a)
  ) _218_ (
    .I0(\change_trigger.i_nib [0]),
    .I1(\spi_passiv.rx_shift_reg [0]),
    .I2(\spi_passiv.i_ss ),
    .I3(_140_[3]),
    .O(_028_)
  );
  CC_LUT4 #(
    .INIT(16'h0c0a)
  ) _219_ (
    .I0(\change_trigger.i_nib [1]),
    .I1(\spi_passiv.rx_shift_reg [1]),
    .I2(\spi_passiv.i_ss ),
    .I3(_140_[3]),
    .O(_029_)
  );
  CC_LUT3 #(
    .INIT(8'h40)
  ) _220_ (
    .I0(\trigger_edge.signal_new ),
    .I1(ila_reset_register_clk),
    .I2(\trigger_edge.signal_old ),
    .O(_005_)
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _221_ (
    .I0(\mem_control.addr_cnt_wd [9]),
    .I1(\mem_control.addr_cnt_wd_pip [9]),
    .I2(\mem_control.o_write_done ),
    .I3(\mem_control.i_reset ),
    .O(_078_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _222_ (
    .I0(\DUT.ILA_rst ),
    .I1(\DUT._1_ [4]),
    .O(_038_)
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _223_ (
    .I0(\mem_control.wd_counter [0]),
    .I1(_131_[0]),
    .I2(\mem_control.make_wd_cnt ),
    .I3(\mem_control.i_reset ),
    .O(_093_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _224_ (
    .I0(\DUT.ILA_rst ),
    .I1(\DUT._1_ [14]),
    .O(_048_)
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _225_ (
    .I0(trigger),
    .I1(\trigger_edge.signal_new ),
    .I2(ila_reset_register_clk),
    .O(_117_)
  );
  CC_LUT3 #(
    .INIT(8'h40)
  ) _226_ (
    .I0(\change_trigger.i_nib [1]),
    .I1(_145_[2]),
    .I2(\change_trigger.i_nib [3]),
    .O(_033_)
  );
  CC_LUT4 #(
    .INIT(16'h1000)
  ) _227_ (
    .I0(conf_trigger_start),
    .I1(\change_trigger.i_nib [0]),
    .I2(\change_trigger.i_nib [2]),
    .I3(\mem_control.i_slave_end_byte_post_edge ),
    .O(_145_[2])
  );
  CC_LUT3 #(
    .INIT(8'he0)
  ) _228_ (
    .I0(\mem_control.save_before_done_edge.o_nedge_edge ),
    .I1(\mem_control.save_before_done ),
    .I2(\mem_control.i_reset ),
    .O(_067_)
  );
  CC_LUT4 #(
    .INIT(16'h4000)
  ) _229_ (
    .I0(\mem_control.o_write_done ),
    .I1(\mem_control.i_reset ),
    .I2(\mem_control.save_before_done ),
    .I3(\mem_control.i_trigger_triggered ),
    .O(_068_)
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _230_ (
    .I0(\spi_passiv.i_ss ),
    .I1(\spi_passiv.rx_shift_reg [1]),
    .O(_063_)
  );
  CC_LUT3 #(
    .INIT(8'hac)
  ) _231_ (
    .I0(_122_[0]),
    .I1(_125_[0]),
    .I2(\mem_control.i_slave_end_byte_post_edge ),
    .O(_106_)
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _232_ (
    .I0(_125_[1]),
    .I1(_122_[1]),
    .I2(\mem_control.i_slave_end_byte_post_edge ),
    .O(_108_)
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _233_ (
    .I0(_125_[2]),
    .I1(_122_[2]),
    .I2(\mem_control.i_slave_end_byte_post_edge ),
    .O(_109_)
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _234_ (
    .I0(_125_[3]),
    .I1(_122_[3]),
    .I2(\mem_control.i_slave_end_byte_post_edge ),
    .O(_110_)
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _235_ (
    .I0(_125_[4]),
    .I1(_122_[4]),
    .I2(\mem_control.i_slave_end_byte_post_edge ),
    .O(_111_)
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _236_ (
    .I0(_125_[5]),
    .I1(_122_[5]),
    .I2(\mem_control.i_slave_end_byte_post_edge ),
    .O(_112_)
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _237_ (
    .I0(_125_[6]),
    .I1(_122_[6]),
    .I2(\mem_control.i_slave_end_byte_post_edge ),
    .O(_113_)
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _238_ (
    .I0(_125_[7]),
    .I1(_122_[7]),
    .I2(\mem_control.i_slave_end_byte_post_edge ),
    .O(_114_)
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _239_ (
    .I0(_125_[8]),
    .I1(_122_[8]),
    .I2(\mem_control.i_slave_end_byte_post_edge ),
    .O(_115_)
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _240_ (
    .I0(_125_[9]),
    .I1(_122_[9]),
    .I2(\mem_control.i_slave_end_byte_post_edge ),
    .O(_116_)
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _241_ (
    .I0(_125_[10]),
    .I1(_122_[10]),
    .I2(\mem_control.i_slave_end_byte_post_edge ),
    .O(_107_)
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _242_ (
    .I0(\mem_control.addr_cnt_wd [8]),
    .I1(\mem_control.addr_cnt_wd_pip [8]),
    .I2(\mem_control.o_write_done ),
    .I3(\mem_control.i_reset ),
    .O(_077_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _243_ (
    .I0(\mem_control.i_read_active ),
    .I1(\mem_control.BRAM_do_tmp[0] [0]),
    .O(_091_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _244_ (
    .I0(\DUT.ILA_rst ),
    .I1(\DUT._1_ [13]),
    .O(_047_)
  );
  CC_LUT3 #(
    .INIT(8'h01)
  ) _245_ (
    .I0(_138_[0]),
    .I1(trigger_column[2]),
    .I2(trigger_column[1]),
    .O(_137_)
  );
  CC_LUT3 #(
    .INIT(8'h35)
  ) _246_ (
    .I0(trigger_pipe[0]),
    .I1(trigger_pipe[1]),
    .I2(trigger_column[0]),
    .O(_138_[0])
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _247_ (
    .I0(\DUT.ILA_rst ),
    .I1(\DUT._1_ [12]),
    .O(_046_)
  );
  CC_LUT4 #(
    .INIT(16'h0e00)
  ) _248_ (
    .I0(sclk_reset_check),
    .I1(ila_reset_register_sclk),
    .I2(ila_reset_signal),
    .I3(\DUT.ILA_rst ),
    .O(_021_)
  );
  CC_LUT2 #(
    .INIT(4'hb)
  ) _249_ (
    .I0(\spi_passiv.i_ss ),
    .I1(\spi_passiv.bit_cnt [0]),
    .O(_023_)
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _250_ (
    .I0(trigger_column[1]),
    .I1(\change_trigger.i_nib [1]),
    .I2(_139_[2]),
    .I3(ila_reset_register_sclk),
    .O(_016_)
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _251_ (
    .I0(\mem_control.addr_cnt_wd [7]),
    .I1(\mem_control.addr_cnt_wd_pip [7]),
    .I2(\mem_control.o_write_done ),
    .I3(\mem_control.i_reset ),
    .O(_076_)
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _252_ (
    .I0(\mem_control.save_before_done_edge.i_signal ),
    .I1(\mem_control.addr_cnt_wd_pip [6]),
    .I2(\mem_control.o_write_done ),
    .I3(\mem_control.i_reset ),
    .O(_075_)
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _253_ (
    .I0(\mem_control.addr_cnt_wd [5]),
    .I1(\mem_control.addr_cnt_wd_pip [5]),
    .I2(\mem_control.o_write_done ),
    .I3(\mem_control.i_reset ),
    .O(_074_)
  );
  CC_LUT3 #(
    .INIT(8'h40)
  ) _254_ (
    .I0(\change_trigger.i_nib [3]),
    .I1(\change_trigger.i_nib [1]),
    .I2(_145_[2]),
    .O(_105_)
  );
  CC_LUT3 #(
    .INIT(8'he0)
  ) _255_ (
    .I0(\mem_control.write_done_edge.o_nedge_edge ),
    .I1(\mem_control.o_write_done ),
    .I2(\mem_control.i_reset ),
    .O(_104_)
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _256_ (
    .I0(\mem_control.write_done_edge.i_signal ),
    .I1(_131_[10]),
    .I2(\mem_control.make_wd_cnt ),
    .I3(\mem_control.i_reset ),
    .O(_103_)
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _257_ (
    .I0(\mem_control.wd_counter [9]),
    .I1(_131_[9]),
    .I2(\mem_control.make_wd_cnt ),
    .I3(\mem_control.i_reset ),
    .O(_102_)
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _258_ (
    .I0(\mem_control.addr_cnt_wd [4]),
    .I1(\mem_control.addr_cnt_wd_pip [4]),
    .I2(\mem_control.o_write_done ),
    .I3(\mem_control.i_reset ),
    .O(_073_)
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _259_ (
    .I0(\mem_control.addr_cnt_wd [3]),
    .I1(\mem_control.addr_cnt_wd_pip [3]),
    .I2(\mem_control.o_write_done ),
    .I3(\mem_control.i_reset ),
    .O(_072_)
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _260_ (
    .I0(\mem_control.wd_counter [8]),
    .I1(_131_[8]),
    .I2(\mem_control.make_wd_cnt ),
    .I3(\mem_control.i_reset ),
    .O(_101_)
  );
  CC_LUT4 #(
    .INIT(16'hcaff)
  ) _261_ (
    .I0(\mem_control.wd_counter [7]),
    .I1(_131_[7]),
    .I2(\mem_control.make_wd_cnt ),
    .I3(\mem_control.i_reset ),
    .O(_100_)
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _262_ (
    .I0(\mem_control.wd_counter [6]),
    .I1(_131_[6]),
    .I2(\mem_control.make_wd_cnt ),
    .I3(\mem_control.i_reset ),
    .O(_099_)
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _263_ (
    .I0(\mem_control.wd_counter [5]),
    .I1(_131_[5]),
    .I2(\mem_control.make_wd_cnt ),
    .I3(\mem_control.i_reset ),
    .O(_098_)
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _264_ (
    .I0(\mem_control.wd_counter [4]),
    .I1(_131_[4]),
    .I2(\mem_control.make_wd_cnt ),
    .I3(\mem_control.i_reset ),
    .O(_097_)
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _265_ (
    .I0(\mem_control.wd_counter [3]),
    .I1(_131_[3]),
    .I2(\mem_control.make_wd_cnt ),
    .I3(\mem_control.i_reset ),
    .O(_096_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _266_ (
    .I0(ila_reset_register_clk),
    .I1(\trigger_edge.o_post_edge ),
    .O(_009_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _267_ (
    .I0(ila_reset_register_clk),
    .I1(\DUT.clk ),
    .O(_008_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _268_ (
    .I0(ila_reset_register_clk),
    .I1(\DUT.clk0 ),
    .O(_007_)
  );
  CC_LUT3 #(
    .INIT(8'he0)
  ) _269_ (
    .I0(\mem_control.i_trigger_triggered ),
    .I1(_150_[1]),
    .I2(ila_reset_register_clk),
    .O(_006_)
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _270_ (
    .I0(trigger_nedge_edge),
    .I1(trigger_post_edge),
    .I2(_149_[2]),
    .I3(\mem_control.i_reset ),
    .O(_150_[1])
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _271_ (
    .I0(trigger_activation[1]),
    .I1(trigger_activation[0]),
    .O(_149_[2])
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _272_ (
    .I0(\mem_control.addr_cnt_wd [2]),
    .I1(\mem_control.addr_cnt_wd_pip [2]),
    .I2(\mem_control.o_write_done ),
    .I3(\mem_control.i_reset ),
    .O(_071_)
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _273_ (
    .I0(\mem_control.addr_cnt_wd [1]),
    .I1(\mem_control.addr_cnt_wd_pip [1]),
    .I2(\mem_control.o_write_done ),
    .I3(\mem_control.i_reset ),
    .O(_070_)
  );
  CC_LUT3 #(
    .INIT(8'hf4)
  ) _274_ (
    .I0(\mem_control.i_read_active ),
    .I1(\mem_control.o_write_done ),
    .I2(\mem_control.i_slave_end_byte_post_edge ),
    .O(_002_)
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _275_ (
    .I0(ila_reset_register_sclk),
    .O(_001_)
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _276_ (
    .I0(\mem_control.o_write_done ),
    .O(_003_)
  );
  CC_LUT1 #(
    .INIT(2'h1)
  ) _277_ (
    .I0(ila_reset_register_clk),
    .O(_000_)
  );
  CC_LUT3 #(
    .INIT(8'hc5)
  ) _278_ (
    .I0(\spi_passiv.rx_shift_reg [3]),
    .I1(\mem_control.i_read_active ),
    .I2(\mem_control.o_write_done ),
    .O(_146_[1])
  );
  CC_LUT4 #(
    .INIT(16'h030a)
  ) _279_ (
    .I0(\spi_passiv.tx_shift_reg [2]),
    .I1(_146_[1]),
    .I2(\spi_passiv.i_ss ),
    .I3(_140_[3]),
    .O(_027_)
  );
  CC_LUT4 #(
    .INIT(16'h440f)
  ) _280_ (
    .I0(\mem_control.genblk4.send_nib_sync [1]),
    .I1(\mem_control.i_read_active ),
    .I2(\spi_passiv.rx_shift_reg [1]),
    .I3(\mem_control.o_write_done ),
    .O(_147_[1])
  );
  CC_LUT4 #(
    .INIT(16'h030a)
  ) _281_ (
    .I0(\spi_passiv.tx_shift_reg [0]),
    .I1(_147_[1]),
    .I2(\spi_passiv.i_ss ),
    .I3(_140_[3]),
    .O(_025_)
  );
  CC_LUT4 #(
    .INIT(16'h44f0)
  ) _282_ (
    .I0(\mem_control.i_read_active ),
    .I1(read_active_pipe),
    .I2(\spi_passiv.rx_shift_reg [2]),
    .I3(\mem_control.o_write_done ),
    .O(_148_[1])
  );
  CC_LUT4 #(
    .INIT(16'h0c0a)
  ) _283_ (
    .I0(\spi_passiv.tx_shift_reg [1]),
    .I1(_148_[1]),
    .I2(\spi_passiv.i_ss ),
    .I3(_140_[3]),
    .O(_026_)
  );
  CC_ADDF _284_ (
    .A(1'h1),
    .B(\DUT.counter [0]),
    .CI(1'h0),
    .CO(_118_[1]),
    .S(\DUT._1_ [0])
  );
  CC_ADDF _285_ (
    .A(1'h0),
    .B(\DUT.counter [10]),
    .CI(_118_[10]),
    .CO(_118_[11]),
    .S(\DUT._1_ [10])
  );
  CC_ADDF _286_ (
    .A(1'h0),
    .B(\DUT.counter [11]),
    .CI(_118_[11]),
    .CO(_118_[12]),
    .S(\DUT._1_ [11])
  );
  CC_ADDF _287_ (
    .A(1'h0),
    .B(\DUT.counter [12]),
    .CI(_118_[12]),
    .CO(_118_[13]),
    .S(\DUT._1_ [12])
  );
  CC_ADDF _288_ (
    .A(1'h0),
    .B(\DUT.counter [13]),
    .CI(_118_[13]),
    .CO(_118_[14]),
    .S(\DUT._1_ [13])
  );
  CC_ADDF _289_ (
    .A(1'h0),
    .B(\DUT.counter [14]),
    .CI(_118_[14]),
    .CO(_118_[15]),
    .S(\DUT._1_ [14])
  );
  CC_ADDF _290_ (
    .A(1'h0),
    .B(\DUT.counter [15]),
    .CI(_118_[15]),
    .CO(_118_[16]),
    .S(\DUT._1_ [15])
  );
  CC_ADDF _291_ (
    .A(1'h0),
    .B(\DUT.counter [16]),
    .CI(_118_[16]),
    .CO(_118_[17]),
    .S(\DUT._1_ [16])
  );
  CC_ADDF _292_ (
    .A(1'h0),
    .B(\DUT.counter [17]),
    .CI(_118_[17]),
    .CO(_118_[18]),
    .S(\DUT._1_ [17])
  );
  CC_ADDF _293_ (
    .A(1'h0),
    .B(\DUT.counter [18]),
    .CI(_118_[18]),
    .CO(_118_[19]),
    .S(\DUT._1_ [18])
  );
  CC_ADDF _294_ (
    .A(1'h0),
    .B(\DUT.counter [19]),
    .CI(_118_[19]),
    .CO(_118_[20]),
    .S(\DUT._1_ [19])
  );
  CC_ADDF _295_ (
    .A(1'h0),
    .B(\DUT.counter [1]),
    .CI(_118_[1]),
    .CO(_118_[2]),
    .S(\DUT._1_ [1])
  );
  CC_ADDF _296_ (
    .A(1'h0),
    .B(\DUT.counter [20]),
    .CI(_118_[20]),
    .CO(_118_[21]),
    .S(\DUT._1_ [20])
  );
  CC_ADDF _297_ (
    .A(1'h0),
    .B(\DUT.counter [21]),
    .CI(_118_[21]),
    .CO(_118_[22]),
    .S(\DUT._1_ [21])
  );
  CC_ADDF _298_ (
    .A(1'h0),
    .B(\DUT.counter [22]),
    .CI(_118_[22]),
    .CO(_118_[23]),
    .S(\DUT._1_ [22])
  );
  CC_ADDF _299_ (
    .A(1'h0),
    .B(\DUT.counter [23]),
    .CI(_118_[23]),
    .CO(_118_[24]),
    .S(\DUT._1_ [23])
  );
  CC_ADDF _300_ (
    .A(1'h0),
    .B(\DUT.led ),
    .CI(_118_[24]),
    .CO(_119_[24]),
    .S(\DUT._1_ [24])
  );
  CC_ADDF _301_ (
    .A(1'h0),
    .B(\DUT.counter [2]),
    .CI(_118_[2]),
    .CO(_118_[3]),
    .S(\DUT._1_ [2])
  );
  CC_ADDF _302_ (
    .A(1'h0),
    .B(\DUT.counter [3]),
    .CI(_118_[3]),
    .CO(_118_[4]),
    .S(\DUT._1_ [3])
  );
  CC_ADDF _303_ (
    .A(1'h0),
    .B(\DUT.counter [4]),
    .CI(_118_[4]),
    .CO(_118_[5]),
    .S(\DUT._1_ [4])
  );
  CC_ADDF _304_ (
    .A(1'h0),
    .B(\DUT.counter [5]),
    .CI(_118_[5]),
    .CO(_118_[6]),
    .S(\DUT._1_ [5])
  );
  CC_ADDF _305_ (
    .A(1'h0),
    .B(\DUT.counter [6]),
    .CI(_118_[6]),
    .CO(_118_[7]),
    .S(\DUT._1_ [6])
  );
  CC_ADDF _306_ (
    .A(1'h0),
    .B(\DUT.counter [7]),
    .CI(_118_[7]),
    .CO(_118_[8]),
    .S(\DUT._1_ [7])
  );
  CC_ADDF _307_ (
    .A(1'h0),
    .B(\DUT.counter [8]),
    .CI(_118_[8]),
    .CO(_118_[9]),
    .S(\DUT._1_ [8])
  );
  CC_ADDF _308_ (
    .A(1'h0),
    .B(\DUT.counter [9]),
    .CI(_118_[9]),
    .CO(_118_[10]),
    .S(\DUT._1_ [9])
  );
  CC_ADDF _309_ (
    .A(1'h1),
    .B(\mem_control.addr_cnt_rd [0]),
    .CI(1'h0),
    .CO(_120_[1]),
    .S(_122_[0])
  );
  CC_ADDF _310_ (
    .A(1'h0),
    .B(\mem_control.addr_cnt_rd [10]),
    .CI(_120_[10]),
    .CO(_121_[10]),
    .S(_122_[10])
  );
  CC_ADDF _311_ (
    .A(1'h0),
    .B(\mem_control.addr_cnt_rd [1]),
    .CI(_120_[1]),
    .CO(_120_[2]),
    .S(_122_[1])
  );
  CC_ADDF _312_ (
    .A(1'h0),
    .B(\mem_control.addr_cnt_rd [2]),
    .CI(_120_[2]),
    .CO(_120_[3]),
    .S(_122_[2])
  );
  CC_ADDF _313_ (
    .A(1'h0),
    .B(\mem_control.addr_cnt_rd [3]),
    .CI(_120_[3]),
    .CO(_120_[4]),
    .S(_122_[3])
  );
  CC_ADDF _314_ (
    .A(1'h0),
    .B(\mem_control.addr_cnt_rd [4]),
    .CI(_120_[4]),
    .CO(_120_[5]),
    .S(_122_[4])
  );
  CC_ADDF _315_ (
    .A(1'h0),
    .B(\mem_control.addr_cnt_rd [5]),
    .CI(_120_[5]),
    .CO(_120_[6]),
    .S(_122_[5])
  );
  CC_ADDF _316_ (
    .A(1'h0),
    .B(\mem_control.addr_cnt_rd [6]),
    .CI(_120_[6]),
    .CO(_120_[7]),
    .S(_122_[6])
  );
  CC_ADDF _317_ (
    .A(1'h0),
    .B(\mem_control.addr_cnt_rd [7]),
    .CI(_120_[7]),
    .CO(_120_[8]),
    .S(_122_[7])
  );
  CC_ADDF _318_ (
    .A(1'h0),
    .B(\mem_control.addr_cnt_rd [8]),
    .CI(_120_[8]),
    .CO(_120_[9]),
    .S(_122_[8])
  );
  CC_ADDF _319_ (
    .A(1'h0),
    .B(\mem_control.addr_cnt_rd [9]),
    .CI(_120_[9]),
    .CO(_120_[10]),
    .S(_122_[9])
  );
  CC_ADDF _320_ (
    .A(1'h1),
    .B(\mem_control.addr_cnt_wd_pip [0]),
    .CI(1'h0),
    .CO(_123_[1]),
    .S(_125_[0])
  );
  CC_ADDF _321_ (
    .A(1'h0),
    .B(\mem_control.addr_cnt_wd_pip [10]),
    .CI(_123_[10]),
    .CO(_124_[10]),
    .S(_125_[10])
  );
  CC_ADDF _322_ (
    .A(1'h0),
    .B(\mem_control.addr_cnt_wd_pip [1]),
    .CI(_123_[1]),
    .CO(_123_[2]),
    .S(_125_[1])
  );
  CC_ADDF _323_ (
    .A(1'h0),
    .B(\mem_control.addr_cnt_wd_pip [2]),
    .CI(_123_[2]),
    .CO(_123_[3]),
    .S(_125_[2])
  );
  CC_ADDF _324_ (
    .A(1'h0),
    .B(\mem_control.addr_cnt_wd_pip [3]),
    .CI(_123_[3]),
    .CO(_123_[4]),
    .S(_125_[3])
  );
  CC_ADDF _325_ (
    .A(1'h0),
    .B(\mem_control.addr_cnt_wd_pip [4]),
    .CI(_123_[4]),
    .CO(_123_[5]),
    .S(_125_[4])
  );
  CC_ADDF _326_ (
    .A(1'h0),
    .B(\mem_control.addr_cnt_wd_pip [5]),
    .CI(_123_[5]),
    .CO(_123_[6]),
    .S(_125_[5])
  );
  CC_ADDF _327_ (
    .A(1'h0),
    .B(\mem_control.addr_cnt_wd_pip [6]),
    .CI(_123_[6]),
    .CO(_123_[7]),
    .S(_125_[6])
  );
  CC_ADDF _328_ (
    .A(1'h0),
    .B(\mem_control.addr_cnt_wd_pip [7]),
    .CI(_123_[7]),
    .CO(_123_[8]),
    .S(_125_[7])
  );
  CC_ADDF _329_ (
    .A(1'h0),
    .B(\mem_control.addr_cnt_wd_pip [8]),
    .CI(_123_[8]),
    .CO(_123_[9]),
    .S(_125_[8])
  );
  CC_ADDF _330_ (
    .A(1'h0),
    .B(\mem_control.addr_cnt_wd_pip [9]),
    .CI(_123_[9]),
    .CO(_123_[10]),
    .S(_125_[9])
  );
  CC_ADDF _331_ (
    .A(1'h1),
    .B(\mem_control.addr_cnt_wd [0]),
    .CI(1'h0),
    .CO(_126_[1]),
    .S(_128_[0])
  );
  CC_ADDF _332_ (
    .A(1'h0),
    .B(\mem_control.wd_cnt_done_edge.i_signal ),
    .CI(_126_[10]),
    .CO(_127_[10]),
    .S(_128_[10])
  );
  CC_ADDF _333_ (
    .A(1'h0),
    .B(\mem_control.addr_cnt_wd [1]),
    .CI(_126_[1]),
    .CO(_126_[2]),
    .S(_128_[1])
  );
  CC_ADDF _334_ (
    .A(1'h0),
    .B(\mem_control.addr_cnt_wd [2]),
    .CI(_126_[2]),
    .CO(_126_[3]),
    .S(_128_[2])
  );
  CC_ADDF _335_ (
    .A(1'h0),
    .B(\mem_control.addr_cnt_wd [3]),
    .CI(_126_[3]),
    .CO(_126_[4]),
    .S(_128_[3])
  );
  CC_ADDF _336_ (
    .A(1'h0),
    .B(\mem_control.addr_cnt_wd [4]),
    .CI(_126_[4]),
    .CO(_126_[5]),
    .S(_128_[4])
  );
  CC_ADDF _337_ (
    .A(1'h0),
    .B(\mem_control.addr_cnt_wd [5]),
    .CI(_126_[5]),
    .CO(_126_[6]),
    .S(_128_[5])
  );
  CC_ADDF _338_ (
    .A(1'h0),
    .B(\mem_control.save_before_done_edge.i_signal ),
    .CI(_126_[6]),
    .CO(_126_[7]),
    .S(_128_[6])
  );
  CC_ADDF _339_ (
    .A(1'h0),
    .B(\mem_control.addr_cnt_wd [7]),
    .CI(_126_[7]),
    .CO(_126_[8]),
    .S(_128_[7])
  );
  CC_ADDF _340_ (
    .A(1'h0),
    .B(\mem_control.addr_cnt_wd [8]),
    .CI(_126_[8]),
    .CO(_126_[9]),
    .S(_128_[8])
  );
  CC_ADDF _341_ (
    .A(1'h0),
    .B(\mem_control.addr_cnt_wd [9]),
    .CI(_126_[9]),
    .CO(_126_[10]),
    .S(_128_[9])
  );
  CC_ADDF _342_ (
    .A(1'h1),
    .B(\mem_control.wd_counter [0]),
    .CI(1'h0),
    .CO(_129_[1]),
    .S(_131_[0])
  );
  CC_ADDF _343_ (
    .A(1'h0),
    .B(\mem_control.write_done_edge.i_signal ),
    .CI(_129_[10]),
    .CO(_130_[10]),
    .S(_131_[10])
  );
  CC_ADDF _344_ (
    .A(1'h0),
    .B(\mem_control.wd_counter [1]),
    .CI(_129_[1]),
    .CO(_129_[2]),
    .S(_131_[1])
  );
  CC_ADDF _345_ (
    .A(1'h0),
    .B(\mem_control.wd_counter [2]),
    .CI(_129_[2]),
    .CO(_129_[3]),
    .S(_131_[2])
  );
  CC_ADDF _346_ (
    .A(1'h0),
    .B(\mem_control.wd_counter [3]),
    .CI(_129_[3]),
    .CO(_129_[4]),
    .S(_131_[3])
  );
  CC_ADDF _347_ (
    .A(1'h0),
    .B(\mem_control.wd_counter [4]),
    .CI(_129_[4]),
    .CO(_129_[5]),
    .S(_131_[4])
  );
  CC_ADDF _348_ (
    .A(1'h0),
    .B(\mem_control.wd_counter [5]),
    .CI(_129_[5]),
    .CO(_129_[6]),
    .S(_131_[5])
  );
  CC_ADDF _349_ (
    .A(1'h0),
    .B(\mem_control.wd_counter [6]),
    .CI(_129_[6]),
    .CO(_129_[7]),
    .S(_131_[6])
  );
  CC_ADDF _350_ (
    .A(1'h0),
    .B(\mem_control.wd_counter [7]),
    .CI(_129_[7]),
    .CO(_129_[8]),
    .S(_131_[7])
  );
  CC_ADDF _351_ (
    .A(1'h0),
    .B(\mem_control.wd_counter [8]),
    .CI(_129_[8]),
    .CO(_129_[9]),
    .S(_131_[8])
  );
  CC_ADDF _352_ (
    .A(1'h0),
    .B(\mem_control.wd_counter [9]),
    .CI(_129_[9]),
    .CO(_129_[10]),
    .S(_131_[9])
  );
  CC_BUFG _353_ (
    .I(_132_),
    .O(\DUT.clk0 )
  );
  CC_BUFG _354_ (
    .I(_133_),
    .O(clk180)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _355_ (
    .CLK(clk180),
    .D(_004_),
    .EN(1'h1),
    .Q(trigger_nedge_edge),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _356_ (
    .CLK(clk180),
    .D(_005_),
    .EN(1'h1),
    .Q(\trigger_edge.o_nedge_edge ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _357_ (
    .CLK(clk180),
    .D(_006_),
    .EN(1'h1),
    .Q(\mem_control.i_trigger_triggered ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _358_ (
    .CLK(clk180),
    .D(_007_),
    .EN(1'h1),
    .Q(trigger_pipe[0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _359_ (
    .CLK(clk180),
    .D(_008_),
    .EN(1'h1),
    .Q(trigger_pipe[1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _360_ (
    .CLK(clk180),
    .D(_009_),
    .EN(1'h1),
    .Q(trigger_post_edge),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _361_ (
    .CLK(clk180),
    .D(_137_),
    .EN(1'h1),
    .Q(trigger),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _362_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_010_),
    .EN(1'h1),
    .Q(\mem_control.i_read_active ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _363_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_011_),
    .EN(1'h1),
    .Q(read_active_pipe),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _364_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_012_),
    .EN(1'h1),
    .Q(\mem_control.i_reset ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _365_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_013_),
    .EN(1'h1),
    .Q(trigger_activation[0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _366_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_014_),
    .EN(1'h1),
    .Q(trigger_activation[1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _367_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_015_),
    .EN(1'h1),
    .Q(trigger_column[0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _368_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_016_),
    .EN(1'h1),
    .Q(trigger_column[1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _369_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_017_),
    .EN(1'h1),
    .Q(trigger_column[2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _370_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_018_),
    .EN(1'h1),
    .Q(state_trigger_conf[0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _371_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_019_),
    .EN(1'h1),
    .Q(state_trigger_conf[1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _372_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_020_),
    .EN(1'h1),
    .Q(conf_trigger_start),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'h0),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _373_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_001_),
    .EN(1'h1),
    .Q(sclk_reset_check),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _374_ (
    .CLK(clk180),
    .D(_000_),
    .EN(1'h1),
    .Q(clk_reset_check),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _375_ (
    .CLK(clk180),
    .D(_021_),
    .EN(1'h1),
    .Q(ila_reset_register_sclk),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _376_ (
    .CLK(clk180),
    .D(_022_),
    .EN(1'h1),
    .Q(ila_reset_register_clk),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _377_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_023_),
    .EN(1'h1),
    .Q(\spi_passiv.bit_cnt [0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _378_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_024_),
    .EN(1'h1),
    .Q(\spi_passiv.bit_cnt [1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h1),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _379_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_025_),
    .EN(1'h1),
    .Q(\spi_passiv.tx_shift_reg [1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h1),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _380_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_026_),
    .EN(1'h1),
    .Q(\spi_passiv.tx_shift_reg [2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h1),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _381_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_027_),
    .EN(1'h1),
    .Q(\spi_passiv.o_miso ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h1),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _382_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_141_[1]),
    .EN(1'h1),
    .Q(\mem_control.i_slave_end_byte_post_edge ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h1),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _383_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_028_),
    .EN(1'h1),
    .Q(\change_trigger.i_nib [0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h1),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _384_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_029_),
    .EN(1'h1),
    .Q(\change_trigger.i_nib [1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h1),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _385_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_030_),
    .EN(1'h1),
    .Q(\change_trigger.i_nib [2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h1),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _386_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_031_),
    .EN(1'h1),
    .Q(\change_trigger.i_nib [3]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _387_ (
    .CLK(clk180),
    .D(_032_),
    .EN(1'h1),
    .Q(\mem_control.write_done_edge.o_nedge_edge ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _388_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_033_),
    .EN(1'h1),
    .Q(\command_read.o_hold ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _389_ (
    .CLK(\DUT.clk0 ),
    .D(_034_),
    .EN(1'h1),
    .Q(\DUT.counter [0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _390_ (
    .CLK(\DUT.clk0 ),
    .D(_035_),
    .EN(1'h1),
    .Q(\DUT.counter [1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _391_ (
    .CLK(\DUT.clk0 ),
    .D(_036_),
    .EN(1'h1),
    .Q(\DUT.counter [2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _392_ (
    .CLK(\DUT.clk0 ),
    .D(_037_),
    .EN(1'h1),
    .Q(\DUT.counter [3]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _393_ (
    .CLK(\DUT.clk0 ),
    .D(_038_),
    .EN(1'h1),
    .Q(\DUT.counter [4]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _394_ (
    .CLK(\DUT.clk0 ),
    .D(_039_),
    .EN(1'h1),
    .Q(\DUT.counter [5]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _395_ (
    .CLK(\DUT.clk0 ),
    .D(_040_),
    .EN(1'h1),
    .Q(\DUT.counter [6]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _396_ (
    .CLK(\DUT.clk0 ),
    .D(_041_),
    .EN(1'h1),
    .Q(\DUT.counter [7]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _397_ (
    .CLK(\DUT.clk0 ),
    .D(_042_),
    .EN(1'h1),
    .Q(\DUT.counter [8]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _398_ (
    .CLK(\DUT.clk0 ),
    .D(_043_),
    .EN(1'h1),
    .Q(\DUT.counter [9]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _399_ (
    .CLK(\DUT.clk0 ),
    .D(_044_),
    .EN(1'h1),
    .Q(\DUT.counter [10]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _400_ (
    .CLK(\DUT.clk0 ),
    .D(_045_),
    .EN(1'h1),
    .Q(\DUT.counter [11]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _401_ (
    .CLK(\DUT.clk0 ),
    .D(_046_),
    .EN(1'h1),
    .Q(\DUT.counter [12]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _402_ (
    .CLK(\DUT.clk0 ),
    .D(_047_),
    .EN(1'h1),
    .Q(\DUT.counter [13]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _403_ (
    .CLK(\DUT.clk0 ),
    .D(_048_),
    .EN(1'h1),
    .Q(\DUT.counter [14]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _404_ (
    .CLK(\DUT.clk0 ),
    .D(_049_),
    .EN(1'h1),
    .Q(\DUT.counter [15]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _405_ (
    .CLK(\DUT.clk0 ),
    .D(_050_),
    .EN(1'h1),
    .Q(\DUT.counter [16]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _406_ (
    .CLK(\DUT.clk0 ),
    .D(_051_),
    .EN(1'h1),
    .Q(\DUT.counter [17]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _407_ (
    .CLK(\DUT.clk0 ),
    .D(_052_),
    .EN(1'h1),
    .Q(\DUT.counter [18]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _408_ (
    .CLK(\DUT.clk0 ),
    .D(_053_),
    .EN(1'h1),
    .Q(\DUT.counter [19]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _409_ (
    .CLK(\DUT.clk0 ),
    .D(_054_),
    .EN(1'h1),
    .Q(\DUT.counter [20]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _410_ (
    .CLK(\DUT.clk0 ),
    .D(_055_),
    .EN(1'h1),
    .Q(\DUT.counter [21]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _411_ (
    .CLK(\DUT.clk0 ),
    .D(_056_),
    .EN(1'h1),
    .Q(\DUT.counter [22]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _412_ (
    .CLK(\DUT.clk0 ),
    .D(_057_),
    .EN(1'h1),
    .Q(\DUT.counter [23]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _413_ (
    .CLK(\DUT.clk0 ),
    .D(_058_),
    .EN(1'h1),
    .Q(\DUT.led ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _414_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_059_),
    .EN(1'h1),
    .Q(\change_trigger.o_hold ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _415_ (
    .CLK(clk180),
    .D(_117_),
    .EN(1'h1),
    .Q(\trigger_edge.signal_old ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _416_ (
    .CLK(clk180),
    .D(trigger),
    .EN(1'h1),
    .Q(\trigger_edge.signal_new ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _417_ (
    .CLK(clk180),
    .D(_060_),
    .EN(1'h1),
    .Q(\trigger_edge.o_post_edge ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _418_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_061_),
    .EN(1'h1),
    .Q(\spi_passiv.rx_shift_reg [0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _419_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_062_),
    .EN(1'h1),
    .Q(\spi_passiv.rx_shift_reg [1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _420_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_063_),
    .EN(1'h1),
    .Q(\spi_passiv.rx_shift_reg [2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _421_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_064_),
    .EN(1'h1),
    .Q(\spi_passiv.rx_shift_reg [3]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h1),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _422_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_065_),
    .EN(1'h1),
    .Q(\spi_passiv.tx_shift_reg [0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _423_ (
    .CLK(clk180),
    .D(_066_),
    .EN(1'h1),
    .Q(\mem_control.save_before_done_edge.o_nedge_edge ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _424_ (
    .CLK(clk180),
    .D(\mem_control.write_done_edge.i_signal ),
    .EN(1'h1),
    .Q(\mem_control.write_done_edge.signal_old ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _425_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_106_),
    .EN(_002_),
    .Q(\mem_control.addr_cnt_rd [0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _426_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_108_),
    .EN(_002_),
    .Q(\mem_control.addr_cnt_rd [1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _427_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_109_),
    .EN(_002_),
    .Q(\mem_control.addr_cnt_rd [2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _428_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_110_),
    .EN(_002_),
    .Q(\mem_control.addr_cnt_rd [3]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _429_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_111_),
    .EN(_002_),
    .Q(\mem_control.addr_cnt_rd [4]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _430_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_112_),
    .EN(_002_),
    .Q(\mem_control.addr_cnt_rd [5]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _431_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_113_),
    .EN(_002_),
    .Q(\mem_control.addr_cnt_rd [6]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _432_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_114_),
    .EN(_002_),
    .Q(\mem_control.addr_cnt_rd [7]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _433_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_115_),
    .EN(_002_),
    .Q(\mem_control.addr_cnt_rd [8]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _434_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_116_),
    .EN(_002_),
    .Q(\mem_control.addr_cnt_rd [9]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _435_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_107_),
    .EN(_002_),
    .Q(\mem_control.addr_cnt_rd [10]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _436_ (
    .CLK(clk180),
    .D(\mem_control.save_before_done_edge.i_signal ),
    .EN(1'h1),
    .Q(\mem_control.save_before_done_edge.signal_old ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _437_ (
    .CLK(clk180),
    .D(_067_),
    .EN(1'h1),
    .Q(\mem_control.save_before_done ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _438_ (
    .CLK(clk180),
    .D(_068_),
    .EN(1'h1),
    .Q(\mem_control.make_wd_cnt ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _439_ (
    .CLK(clk180),
    .D(_069_),
    .EN(1'h1),
    .Q(\mem_control.addr_cnt_wd_pip [0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _440_ (
    .CLK(clk180),
    .D(_070_),
    .EN(1'h1),
    .Q(\mem_control.addr_cnt_wd_pip [1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _441_ (
    .CLK(clk180),
    .D(_071_),
    .EN(1'h1),
    .Q(\mem_control.addr_cnt_wd_pip [2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _442_ (
    .CLK(clk180),
    .D(_072_),
    .EN(1'h1),
    .Q(\mem_control.addr_cnt_wd_pip [3]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _443_ (
    .CLK(clk180),
    .D(_073_),
    .EN(1'h1),
    .Q(\mem_control.addr_cnt_wd_pip [4]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _444_ (
    .CLK(clk180),
    .D(_074_),
    .EN(1'h1),
    .Q(\mem_control.addr_cnt_wd_pip [5]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _445_ (
    .CLK(clk180),
    .D(_075_),
    .EN(1'h1),
    .Q(\mem_control.addr_cnt_wd_pip [6]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _446_ (
    .CLK(clk180),
    .D(_076_),
    .EN(1'h1),
    .Q(\mem_control.addr_cnt_wd_pip [7]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _447_ (
    .CLK(clk180),
    .D(_077_),
    .EN(1'h1),
    .Q(\mem_control.addr_cnt_wd_pip [8]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _448_ (
    .CLK(clk180),
    .D(_078_),
    .EN(1'h1),
    .Q(\mem_control.addr_cnt_wd_pip [9]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _449_ (
    .CLK(clk180),
    .D(_079_),
    .EN(1'h1),
    .Q(\mem_control.addr_cnt_wd_pip [10]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _450_ (
    .CLK(clk180),
    .D(_080_),
    .EN(1'h1),
    .Q(\mem_control.addr_cnt_wd [0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _451_ (
    .CLK(clk180),
    .D(_081_),
    .EN(1'h1),
    .Q(\mem_control.addr_cnt_wd [1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _452_ (
    .CLK(clk180),
    .D(_082_),
    .EN(1'h1),
    .Q(\mem_control.addr_cnt_wd [2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _453_ (
    .CLK(clk180),
    .D(_083_),
    .EN(1'h1),
    .Q(\mem_control.addr_cnt_wd [3]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _454_ (
    .CLK(clk180),
    .D(_084_),
    .EN(1'h1),
    .Q(\mem_control.addr_cnt_wd [4]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _455_ (
    .CLK(clk180),
    .D(_085_),
    .EN(1'h1),
    .Q(\mem_control.addr_cnt_wd [5]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _456_ (
    .CLK(clk180),
    .D(_086_),
    .EN(1'h1),
    .Q(\mem_control.save_before_done_edge.i_signal ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _457_ (
    .CLK(clk180),
    .D(_087_),
    .EN(1'h1),
    .Q(\mem_control.addr_cnt_wd [7]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _458_ (
    .CLK(clk180),
    .D(_088_),
    .EN(1'h1),
    .Q(\mem_control.addr_cnt_wd [8]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _459_ (
    .CLK(clk180),
    .D(_089_),
    .EN(1'h1),
    .Q(\mem_control.addr_cnt_wd [9]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _460_ (
    .CLK(clk180),
    .D(_090_),
    .EN(1'h1),
    .Q(\mem_control.wd_cnt_done_edge.i_signal ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _461_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_091_),
    .EN(1'h1),
    .Q(\mem_control.genblk4.send_nib_sync [0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _462_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_092_),
    .EN(1'h1),
    .Q(\mem_control.genblk4.send_nib_sync [1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _463_ (
    .CLK(clk180),
    .D(_093_),
    .EN(1'h1),
    .Q(\mem_control.wd_counter [0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _464_ (
    .CLK(clk180),
    .D(_094_),
    .EN(1'h1),
    .Q(\mem_control.wd_counter [1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _465_ (
    .CLK(clk180),
    .D(_095_),
    .EN(1'h1),
    .Q(\mem_control.wd_counter [2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _466_ (
    .CLK(clk180),
    .D(_096_),
    .EN(1'h1),
    .Q(\mem_control.wd_counter [3]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _467_ (
    .CLK(clk180),
    .D(_097_),
    .EN(1'h1),
    .Q(\mem_control.wd_counter [4]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _468_ (
    .CLK(clk180),
    .D(_098_),
    .EN(1'h1),
    .Q(\mem_control.wd_counter [5]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _469_ (
    .CLK(clk180),
    .D(_099_),
    .EN(1'h1),
    .Q(\mem_control.wd_counter [6]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _470_ (
    .CLK(clk180),
    .D(_100_),
    .EN(1'h1),
    .Q(\mem_control.wd_counter [7]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _471_ (
    .CLK(clk180),
    .D(_101_),
    .EN(1'h1),
    .Q(\mem_control.wd_counter [8]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _472_ (
    .CLK(clk180),
    .D(_102_),
    .EN(1'h1),
    .Q(\mem_control.wd_counter [9]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _473_ (
    .CLK(clk180),
    .D(_103_),
    .EN(1'h1),
    .Q(\mem_control.write_done_edge.i_signal ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _474_ (
    .CLK(clk180),
    .D(_104_),
    .EN(1'h1),
    .Q(\mem_control.o_write_done ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _475_ (
    .CLK(\spi_passiv.i_sclk ),
    .D(_105_),
    .EN(1'h1),
    .Q(ila_reset_signal),
    .SR(1'h0)
  );
  CC_IBUF _476_ (
    .I(clk),
    .Y(\DUT.clk )
  );
  CC_IBUF _477_ (
    .I(i_mosi_ILA),
    .Y(\spi_passiv.i_mosi )
  );
  CC_IBUF _478_ (
    .I(i_sclk_ILA),
    .Y(\spi_passiv.i_sclk )
  );
  CC_IBUF _479_ (
    .I(i_ss_ILA),
    .Y(\spi_passiv.i_ss )
  );
  CC_OBUF _480_ (
    .A(\DUT.led ),
    .O(led)
  );
  CC_OBUF _481_ (
    .A(\spi_passiv.o_miso ),
    .O(o_miso_ILA)
  );
  CC_PLL #(
    .CI_FILTER_CONST(32'sd2),
    .CP_FILTER_CONST(32'sd4),
    .LOW_JITTER(32'sd1),
    .OUT_CLK("20"),
    .PERF_MD("SPEED"),
    .REF_CLK("10.0")
  ) \DUT.pll_inst  (
    .CLK0(_132_),
    .CLK180(\DUT.clk180 ),
    .CLK270(\DUT.clk270 ),
    .CLK90(\DUT.clk90 ),
    .CLK_FEEDBACK(1'h0),
    .CLK_REF(\DUT.clk ),
    .CLK_REF_OUT(\DUT.usr_ref_out ),
    .USR_CLK_REF(1'h0),
    .USR_LOCKED_STDY_RST(1'h0),
    .USR_PLL_LOCKED(\DUT.usr_pll_lock ),
    .USR_PLL_LOCKED_STDY(\DUT.usr_pll_lock_stdy )
  );
  CC_PLL #(
    .CI_FILTER_CONST(32'sd2),
    .CP_FILTER_CONST(32'sd4),
    .LOW_JITTER(32'sd1),
    .OUT_CLK("1"),
    .PERF_MD("SPEED"),
    .REF_CLK("10.0")
  ) \genblk1.pll_inst_ila  (
    .CLK0(clk0),
    .CLK180(_133_),
    .CLK270(clk270),
    .CLK90(clk90),
    .CLK_FEEDBACK(1'h0),
    .CLK_REF(\DUT.clk ),
    .CLK_REF_OUT(usr_ref_out_1),
    .USR_CLK_REF(1'h0),
    .USR_LOCKED_STDY_RST(1'h0),
    .USR_PLL_LOCKED(usr_pll_lock_1),
    .USR_PLL_LOCKED_STDY(usr_pll_lock_stdy_1)
  );
  CC_BRAM_20K #(
    .A_CLK_INV(1'h1),
    .A_RD_WIDTH(32'd0),
    .A_WR_MODE("WRITE_THROUGH"),
    .A_WR_WIDTH(32'd5),
    .B_CLK_INV(1'h1),
    .B_RD_WIDTH(32'd5),
    .B_WR_MODE("WRITE_THROUGH"),
    .B_WR_WIDTH(32'd0),
    .INIT_00(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_01(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_02(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_03(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_04(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_05(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_06(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_07(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_08(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_09(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_0A(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_0B(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_0C(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_0D(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_0E(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_0F(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_10(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_11(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_12(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_13(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_14(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_15(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_16(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_17(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_18(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_19(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_1A(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_1B(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_1C(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_1D(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_1E(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_1F(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_20(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_21(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_22(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_23(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_24(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_25(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_26(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_27(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_28(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_29(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_2A(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_2B(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_2C(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_2D(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_2E(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_2F(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_30(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_31(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_32(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_33(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_34(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_35(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_36(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_37(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_38(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_39(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_3A(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_3B(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_3C(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_3D(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_3E(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_3F(320'h00000000000000000000000000000000000000000000000000000000000000000000000000000000),
    .RAM_MODE("TDP")
  ) \mem_control.loop[0].loop[0].ila_bram.memory.0.0  (
    .A_ADDR({ 1'h0, \mem_control.addr_cnt_wd_pip [10:3], 1'h0, \mem_control.addr_cnt_wd_pip [2:0], 3'h0 }),
    .A_BM({ 15'h0000, _003_, _003_, _003_, _003_, _003_ }),
    .A_CLK(clk180),
    .A_DI({ 18'h00000, \DUT.clk , \DUT.clk0  }),
    .A_DO(_136_),
    .A_EN(1'h1),
    .A_WE(_003_),
    .B_ADDR({ 1'h0, \mem_control.addr_cnt_rd [10:3], 1'h0, \mem_control.addr_cnt_rd [2:0], 3'h0 }),
    .B_BM(20'h00000),
    .B_CLK(\spi_passiv.i_sclk ),
    .B_DI(20'hxxxxx),
    .B_DO({ _134_, _135_[4:2], \mem_control.BRAM_do_tmp[0] [1:0] }),
    .B_EN(1'h1),
    .B_WE(1'h0)
  );
  CC_USR_RSTN usr_rstn_inst (
    .USR_RSTN(\DUT.ILA_rst )
  );
  assign _118_[0] = 1'h0;
  assign _119_[23:0] = _118_[24:1];
  assign _120_[0] = 1'h0;
  assign _121_[9:0] = _120_[10:1];
  assign _123_[0] = 1'h0;
  assign _124_[9:0] = _123_[10:1];
  assign _126_[0] = 1'h0;
  assign _127_[9:0] = _126_[10:1];
  assign _129_[0] = 1'h0;
  assign _130_[9:0] = _129_[10:1];
  assign _135_[1:0] = \mem_control.BRAM_do_tmp[0] [1:0];
  assign _138_[2:1] = { trigger_column[1], trigger_column[2] };
  assign { _139_[3], _139_[1:0] } = { ila_reset_register_sclk, \change_trigger.i_nib [2], trigger_column[2] };
  assign _140_[2:0] = { \spi_passiv.i_ss , \spi_passiv.rx_shift_reg [2], \change_trigger.i_nib [2] };
  assign { _142_[2], _142_[0] } = { \mem_control.i_slave_end_byte_post_edge , conf_trigger_start };
  assign _143_[1] = state_trigger_conf[1];
  assign { _144_[2], _144_[0] } = { ila_reset_register_sclk, \mem_control.i_reset  };
  assign _145_[1:0] = { \change_trigger.i_nib [1], \change_trigger.i_nib [3] };
  assign { _146_[3:2], _146_[0] } = { _140_[3], \spi_passiv.i_ss , \spi_passiv.tx_shift_reg [2] };
  assign { _147_[3:2], _147_[0] } = { _140_[3], \spi_passiv.i_ss , \spi_passiv.tx_shift_reg [0] };
  assign { _148_[3:2], _148_[0] } = { _140_[3], \spi_passiv.i_ss , \spi_passiv.tx_shift_reg [1] };
  assign { _149_[3], _149_[1:0] } = { \mem_control.i_reset , trigger_post_edge, trigger_nedge_edge };
  assign { _150_[2], _150_[0] } = { ila_reset_register_clk, \mem_control.i_trigger_triggered  };
  assign \DUT.counter [24] = \DUT.led ;
  assign \mem_control.BRAM_do_tmp[0] [4:2] = 3'hx;
  assign { \mem_control.addr_cnt_wd [10], \mem_control.addr_cnt_wd [6] } = { \mem_control.wd_cnt_done_edge.i_signal , \mem_control.save_before_done_edge.i_signal  };
  assign \mem_control.genblk4.send_nib_sync [3:2] = 2'h0;
  assign \mem_control.wd_counter [10] = \mem_control.write_done_edge.i_signal ;
  assign \spi_passiv.tx_shift_reg [3] = \spi_passiv.o_miso ;
  assign trigger_column[5:3] = 3'hx;
endmodule
