
FAMILY  = colognechip
PART    = CCGM1A1
BOARD   = GateMateA1-EVB
PROJECT = TestPipeline
CHIPDB  = /home/nikola/ChiliChips/openCologne/pnr_tests-novi/colognechip/CCGM1A1/gatemate-ccgm1a1-pinlist.csv
TOP_VERILOG=$(PROJECT).sv
#SYNTH_OPTS = -nodsp
include ../../config.mk
