-d D:\repos\openCologne\8.StressTest\2.LUTRAM_stress_test\3.build\hw_build_GUI\impl\gwsynthesis\hw_build_GUI.vg
-p GW2AR-18C-QFN88P-8
-pn GW2AR-LV18QN88PC8/I7
-cst D:\repos\LUTRAM_Stress_Test\1.hw\constraints\top.pinout.cst
-cfg D:\repos\openCologne\8.StressTest\2.LUTRAM_stress_test\3.build\hw_build_GUI\impl\pnr\device.cfg
-sdc D:\repos\LUTRAM_Stress_Test\1.hw\constraints\top.timing.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 1
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
