/* Generated by Yosys 0.36+58 (git sha1 ea7818d31, c++ 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module top(clk, arst_n, tick_1us, uart_rx, uart_tx, received, sent, led);
  wire [5:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire [5:0] _038_;
  wire [5:0] _039_;
  wire [5:0] _040_;
  wire [27:0] _041_;
  wire [27:0] _042_;
  wire [27:0] _043_;
  wire [2:0] _044_;
  wire [2:0] _045_;
  wire [2:0] _046_;
  wire [3:0] _047_;
  wire [3:0] _048_;
  wire [3:0] _049_;
  wire [3:0] _050_;
  wire [3:0] _051_;
  wire [3:0] _052_;
  wire _053_;
  wire [3:0] _054_;
  wire _055_;
  wire [3:0] _056_;
  wire _057_;
  wire _058_;
  wire [3:0] _059_;
  wire [3:0] _060_;
  wire [3:0] _061_;
  wire [3:0] _062_;
  wire [1:0] _063_;
  wire [3:0] _064_;
  wire [1:0] _065_;
  wire [2:0] _066_;
  wire [2:0] _067_;
  wire [3:0] _068_;
  wire [2:0] _069_;
  wire [3:0] _070_;
  wire [1:0] _071_;
  wire [2:0] _072_;
  wire [2:0] _073_;
  wire [2:0] _074_;
  wire [1:0] _075_;
  wire [2:0] _076_;
  wire [3:0] _077_;
  wire [3:0] _078_;
  wire [3:0] _079_;
  wire [3:0] _080_;
  wire [3:0] _081_;
  wire [2:0] _082_;
  wire [2:0] _083_;
  wire [2:0] _084_;
  wire [2:0] _085_;
  wire [2:0] _086_;
  wire [1:0] _087_;
  wire [3:0] _088_;
  input arst_n;
  wire arst_n;
  wire \buffer[0] ;
  wire \buffer[1] ;
  wire \buffer[2] ;
  wire \buffer[3] ;
  wire \buffer[4] ;
  wire \buffer[5] ;
  wire \buffer[6] ;
  wire \buffer[7] ;
  wire buffer_full;
  input clk;
  wire clk;
  wire clk180;
  wire clk270;
  wire clk90;
  wire [5:0] counter;
  wire counter_24_prev;
  wire [2:0] in;
  output led;
  wire led;
  output received;
  wire received;
  output sent;
  wire sent;
  output tick_1us;
  wire tick_1us;
  wire [27:0] u_counter;
  wire \u_uart.arst_n ;
  wire \u_uart.clk ;
  wire [3:0] \u_uart.rx_cnt1us ;
  wire [7:0] \u_uart.rx_shift ;
  wire [9:0] \u_uart.rx_state ;
  wire \u_uart.tick_1us ;
  wire [3:0] \u_uart.tx_cnt1us ;
  wire [7:0] \u_uart.tx_data ;
  wire [10:0] \u_uart.tx_state ;
  wire \u_uart.uart_rx ;
  wire [9:0] \u_uart.uart_rx_arr ;
  wire \u_uart.uart_rx_read ;
  wire \u_uart.uart_tx ;
  input uart_rx;
  wire uart_rx;
  wire uart_rx_prev;
  output uart_tx;
  wire uart_tx;
  wire usr_pll_lock;
  wire usr_pll_lock_stdy;
  wire usr_ref_out;
  CC_LUT2 #(
    .INIT(4'h4)
  ) _089_ (
    .I0(_075_[0]),
    .I1(_040_[0]),
    .O(_000_[0])
  );
  CC_LUT3 #(
    .INIT(8'h10)
  ) _090_ (
    .I0(counter[3]),
    .I1(counter[4]),
    .I2(_074_[2]),
    .O(_075_[0])
  );
  CC_LUT4 #(
    .INIT(16'h8000)
  ) _091_ (
    .I0(counter[0]),
    .I1(counter[1]),
    .I2(counter[2]),
    .I3(counter[5]),
    .O(_074_[2])
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _092_ (
    .I0(_075_[0]),
    .I1(_040_[1]),
    .O(_000_[1])
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _093_ (
    .I0(_075_[0]),
    .I1(_040_[2]),
    .O(_000_[2])
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _094_ (
    .I0(_075_[0]),
    .I1(_040_[3]),
    .O(_000_[3])
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _095_ (
    .I0(_075_[0]),
    .I1(_040_[4]),
    .O(_000_[4])
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _096_ (
    .I0(_075_[0]),
    .I1(_040_[5]),
    .O(_000_[5])
  );
  CC_LUT3 #(
    .INIT(8'hac)
  ) _097_ (
    .I0(_085_[0]),
    .I1(_085_[1]),
    .I2(u_counter[27]),
    .O(_001_)
  );
  CC_LUT4 #(
    .INIT(16'h7f00)
  ) _098_ (
    .I0(in[1]),
    .I1(in[2]),
    .I2(in[0]),
    .I3(_046_[2]),
    .O(_030_)
  );
  CC_LUT4 #(
    .INIT(16'h7f00)
  ) _099_ (
    .I0(in[1]),
    .I1(in[2]),
    .I2(in[0]),
    .I3(_046_[0]),
    .O(_028_)
  );
  CC_LUT3 #(
    .INIT(8'h40)
  ) _100_ (
    .I0(\u_uart.uart_rx_read ),
    .I1(\u_uart.rx_state [2]),
    .I2(_066_[2]),
    .O(_026_)
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _101_ (
    .I0(_065_[0]),
    .I1(_065_[1]),
    .O(_066_[2])
  );
  CC_LUT2 #(
    .INIT(4'h1)
  ) _102_ (
    .I0(\u_uart.rx_cnt1us [0]),
    .I1(\u_uart.rx_cnt1us [1]),
    .O(_065_[0])
  );
  CC_LUT3 #(
    .INIT(8'h10)
  ) _103_ (
    .I0(\u_uart.rx_cnt1us [2]),
    .I1(\u_uart.rx_cnt1us [3]),
    .I2(\u_uart.tick_1us ),
    .O(_065_[1])
  );
  CC_LUT3 #(
    .INIT(8'h4f)
  ) _104_ (
    .I0(_073_[0]),
    .I1(_084_[1]),
    .I2(_073_[2]),
    .O(_056_[0])
  );
  CC_LUT2 #(
    .INIT(4'h1)
  ) _105_ (
    .I0(_071_[0]),
    .I1(\u_uart.rx_state [0]),
    .O(_073_[2])
  );
  CC_LUT4 #(
    .INIT(16'h1000)
  ) _106_ (
    .I0(_070_[0]),
    .I1(\u_uart.rx_state [2]),
    .I2(_065_[0]),
    .I3(_065_[1]),
    .O(_071_[0])
  );
  CC_LUT3 #(
    .INIT(8'h01)
  ) _107_ (
    .I0(\u_uart.rx_state [1]),
    .I1(\u_uart.rx_state [5]),
    .I2(\u_uart.rx_state [8]),
    .O(_070_[0])
  );
  CC_LUT3 #(
    .INIT(8'h10)
  ) _108_ (
    .I0(_072_[0]),
    .I1(\u_uart.rx_state [2]),
    .I2(_066_[2]),
    .O(_073_[0])
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _109_ (
    .I0(_068_[0]),
    .I1(_068_[1]),
    .O(_072_[0])
  );
  CC_LUT2 #(
    .INIT(4'h1)
  ) _110_ (
    .I0(\u_uart.rx_state [3]),
    .I1(\u_uart.rx_state [4]),
    .O(_068_[0])
  );
  CC_LUT3 #(
    .INIT(8'h01)
  ) _111_ (
    .I0(\u_uart.rx_state [6]),
    .I1(\u_uart.rx_state [7]),
    .I2(\u_uart.rx_state [9]),
    .O(_068_[1])
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _112_ (
    .I0(\u_uart.rx_cnt1us [0]),
    .I1(_049_[0]),
    .I2(_069_[2]),
    .O(_084_[1])
  );
  CC_LUT4 #(
    .INIT(16'h7f00)
  ) _113_ (
    .I0(_068_[0]),
    .I1(_068_[1]),
    .I2(_068_[2]),
    .I3(\u_uart.tick_1us ),
    .O(_069_[2])
  );
  CC_LUT4 #(
    .INIT(16'h0001)
  ) _114_ (
    .I0(\u_uart.rx_state [2]),
    .I1(\u_uart.rx_state [1]),
    .I2(\u_uart.rx_state [5]),
    .I3(\u_uart.rx_state [8]),
    .O(_068_[2])
  );
  CC_LUT3 #(
    .INIT(8'hf4)
  ) _115_ (
    .I0(_082_[0]),
    .I1(_082_[1]),
    .I2(_082_[2]),
    .O(_056_[1])
  );
  CC_LUT4 #(
    .INIT(16'h0100)
  ) _116_ (
    .I0(_070_[0]),
    .I1(\u_uart.rx_state [2]),
    .I2(\u_uart.rx_state [0]),
    .I3(_066_[2]),
    .O(_082_[2])
  );
  CC_LUT3 #(
    .INIT(8'hf1)
  ) _117_ (
    .I0(_066_[2]),
    .I1(\u_uart.rx_state [0]),
    .I2(\u_uart.rx_state [2]),
    .O(_082_[1])
  );
  CC_LUT3 #(
    .INIT(8'h35)
  ) _118_ (
    .I0(\u_uart.rx_cnt1us [1]),
    .I1(_049_[1]),
    .I2(_069_[2]),
    .O(_082_[0])
  );
  CC_LUT3 #(
    .INIT(8'hfe)
  ) _119_ (
    .I0(_073_[0]),
    .I1(_083_[1]),
    .I2(\u_uart.rx_state [0]),
    .O(_056_[3])
  );
  CC_LUT4 #(
    .INIT(16'h0c0a)
  ) _120_ (
    .I0(\u_uart.rx_cnt1us [3]),
    .I1(_049_[3]),
    .I2(_071_[0]),
    .I3(_069_[2]),
    .O(_083_[1])
  );
  CC_LUT4 #(
    .INIT(16'hbfff)
  ) _121_ (
    .I0(_081_[0]),
    .I1(_081_[1]),
    .I2(_081_[2]),
    .I3(_081_[3]),
    .O(_055_)
  );
  CC_LUT4 #(
    .INIT(16'h0007)
  ) _122_ (
    .I0(\u_uart.tx_data [7]),
    .I1(\u_uart.tx_state [5]),
    .I2(_080_[2]),
    .I3(_080_[3]),
    .O(_081_[1])
  );
  CC_LUT3 #(
    .INIT(8'h80)
  ) _123_ (
    .I0(_060_[1]),
    .I1(\u_uart.tx_data [0]),
    .I2(\u_uart.tx_state [10]),
    .O(_080_[2])
  );
  CC_LUT4 #(
    .INIT(16'h0001)
  ) _124_ (
    .I0(\u_uart.tx_cnt1us [0]),
    .I1(\u_uart.tx_cnt1us [1]),
    .I2(\u_uart.tx_cnt1us [2]),
    .I3(\u_uart.tx_cnt1us [3]),
    .O(_060_[1])
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _125_ (
    .I0(\u_uart.tx_state [4]),
    .I1(\u_uart.tx_data [3]),
    .O(_080_[3])
  );
  CC_LUT3 #(
    .INIT(8'h80)
  ) _126_ (
    .I0(_062_[3]),
    .I1(_062_[1]),
    .I2(_062_[2]),
    .O(_081_[0])
  );
  CC_LUT3 #(
    .INIT(8'h01)
  ) _127_ (
    .I0(\u_uart.tx_state [4]),
    .I1(\u_uart.tx_state [7]),
    .I2(\u_uart.tx_state [10]),
    .O(_062_[3])
  );
  CC_LUT2 #(
    .INIT(4'h1)
  ) _128_ (
    .I0(\u_uart.tx_state [3]),
    .I1(\u_uart.tx_state [5]),
    .O(_062_[1])
  );
  CC_LUT3 #(
    .INIT(8'h01)
  ) _129_ (
    .I0(\u_uart.tx_state [6]),
    .I1(\u_uart.tx_state [8]),
    .I2(\u_uart.tx_state [1]),
    .O(_062_[2])
  );
  CC_LUT3 #(
    .INIT(8'h70)
  ) _130_ (
    .I0(\u_uart.tx_data [6]),
    .I1(\u_uart.tx_state [7]),
    .I2(_076_[2]),
    .O(_081_[2])
  );
  CC_LUT4 #(
    .INIT(16'h0777)
  ) _131_ (
    .I0(\u_uart.tx_data [1]),
    .I1(\u_uart.tx_state [1]),
    .I2(\u_uart.tx_state [6]),
    .I3(\u_uart.tx_data [2]),
    .O(_076_[2])
  );
  CC_LUT4 #(
    .INIT(16'h0777)
  ) _132_ (
    .I0(\u_uart.tx_data [4]),
    .I1(\u_uart.tx_state [8]),
    .I2(\u_uart.tx_state [3]),
    .I3(\u_uart.tx_data [5]),
    .O(_081_[3])
  );
  CC_LUT4 #(
    .INIT(16'h7f00)
  ) _133_ (
    .I0(in[1]),
    .I1(in[2]),
    .I2(in[0]),
    .I3(_046_[1]),
    .O(_029_)
  );
  CC_LUT4 #(
    .INIT(16'h0eff)
  ) _134_ (
    .I0(_078_[0]),
    .I1(_078_[1]),
    .I2(_078_[2]),
    .I3(_078_[3]),
    .O(_054_[0])
  );
  CC_LUT4 #(
    .INIT(16'hca00)
  ) _135_ (
    .I0(_064_[0]),
    .I1(\u_uart.tx_state [0]),
    .I2(_067_[1]),
    .I3(_062_[3]),
    .O(_078_[2])
  );
  CC_LUT3 #(
    .INIT(8'h40)
  ) _136_ (
    .I0(\u_uart.tx_state [9]),
    .I1(_062_[2]),
    .I2(_062_[1]),
    .O(_067_[1])
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _137_ (
    .I0(_060_[1]),
    .I1(\u_uart.tick_1us ),
    .O(_064_[0])
  );
  CC_LUT4 #(
    .INIT(16'h4f00)
  ) _138_ (
    .I0(\u_uart.tx_state [2]),
    .I1(_063_[1]),
    .I2(\u_uart.tick_1us ),
    .I3(\u_uart.tx_cnt1us [0]),
    .O(_078_[0])
  );
  CC_LUT4 #(
    .INIT(16'h4000)
  ) _139_ (
    .I0(\u_uart.tx_state [9]),
    .I1(_062_[1]),
    .I2(_062_[2]),
    .I3(_062_[3]),
    .O(_063_[1])
  );
  CC_LUT4 #(
    .INIT(16'hb000)
  ) _140_ (
    .I0(\u_uart.tx_state [2]),
    .I1(_063_[1]),
    .I2(_052_[0]),
    .I3(\u_uart.tick_1us ),
    .O(_078_[1])
  );
  CC_LUT2 #(
    .INIT(4'h1)
  ) _141_ (
    .I0(_077_[1]),
    .I1(\u_uart.tx_state [0]),
    .O(_078_[3])
  );
  CC_LUT3 #(
    .INIT(8'h40)
  ) _142_ (
    .I0(_062_[3]),
    .I1(_060_[1]),
    .I2(\u_uart.tick_1us ),
    .O(_077_[1])
  );
  CC_LUT4 #(
    .INIT(16'h00fe)
  ) _143_ (
    .I0(_077_[1]),
    .I1(_079_[1]),
    .I2(_079_[2]),
    .I3(_078_[2]),
    .O(_054_[1])
  );
  CC_LUT4 #(
    .INIT(16'hb000)
  ) _144_ (
    .I0(\u_uart.tx_state [2]),
    .I1(_063_[1]),
    .I2(_052_[1]),
    .I3(\u_uart.tick_1us ),
    .O(_079_[1])
  );
  CC_LUT4 #(
    .INIT(16'h4f00)
  ) _145_ (
    .I0(\u_uart.tx_state [2]),
    .I1(_063_[1]),
    .I2(\u_uart.tick_1us ),
    .I3(\u_uart.tx_cnt1us [1]),
    .O(_079_[2])
  );
  CC_LUT4 #(
    .INIT(16'h00fe)
  ) _146_ (
    .I0(_077_[1]),
    .I1(_088_[1]),
    .I2(_088_[2]),
    .I3(_078_[2]),
    .O(_054_[2])
  );
  CC_LUT4 #(
    .INIT(16'hb000)
  ) _147_ (
    .I0(\u_uart.tx_state [2]),
    .I1(_063_[1]),
    .I2(_052_[2]),
    .I3(\u_uart.tick_1us ),
    .O(_088_[1])
  );
  CC_LUT4 #(
    .INIT(16'h4f00)
  ) _148_ (
    .I0(\u_uart.tx_state [2]),
    .I1(_063_[1]),
    .I2(\u_uart.tick_1us ),
    .I3(\u_uart.tx_cnt1us [2]),
    .O(_088_[2])
  );
  CC_LUT4 #(
    .INIT(16'h01ff)
  ) _149_ (
    .I0(_077_[0]),
    .I1(_077_[1]),
    .I2(_077_[2]),
    .I3(_077_[3]),
    .O(_054_[3])
  );
  CC_LUT4 #(
    .INIT(16'h004f)
  ) _150_ (
    .I0(\u_uart.tx_state [2]),
    .I1(_063_[1]),
    .I2(\u_uart.tick_1us ),
    .I3(\u_uart.tx_cnt1us [3]),
    .O(_077_[0])
  );
  CC_LUT4 #(
    .INIT(16'h0b00)
  ) _151_ (
    .I0(\u_uart.tx_state [2]),
    .I1(_063_[1]),
    .I2(_052_[3]),
    .I3(\u_uart.tick_1us ),
    .O(_077_[2])
  );
  CC_LUT3 #(
    .INIT(8'h0d)
  ) _152_ (
    .I0(_064_[0]),
    .I1(_067_[1]),
    .I2(\u_uart.tx_state [0]),
    .O(_077_[3])
  );
  CC_LUT3 #(
    .INIT(8'h14)
  ) _153_ (
    .I0(buffer_full),
    .I1(\u_uart.uart_rx ),
    .I2(uart_rx_prev),
    .O(_059_[3])
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _154_ (
    .I0(\u_uart.tx_state [0]),
    .I1(\u_uart.uart_rx_read ),
    .O(_086_[2])
  );
  CC_LUT3 #(
    .INIT(8'hf4)
  ) _155_ (
    .I0(_064_[0]),
    .I1(\u_uart.tx_state [10]),
    .I2(_086_[2]),
    .O(_014_)
  );
  CC_LUT4 #(
    .INIT(16'h4f44)
  ) _156_ (
    .I0(\u_uart.uart_rx ),
    .I1(\u_uart.rx_state [0]),
    .I2(_066_[2]),
    .I3(\u_uart.rx_state [1]),
    .O(_004_)
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _157_ (
    .I0(\u_uart.tx_state [9]),
    .I1(\u_uart.tx_state [5]),
    .I2(_064_[0]),
    .O(_023_)
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _158_ (
    .I0(\u_uart.rx_state [3]),
    .I1(\u_uart.rx_state [8]),
    .I2(_066_[2]),
    .O(_006_)
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _159_ (
    .I0(\u_uart.tx_state [8]),
    .I1(\u_uart.tx_state [4]),
    .I2(_064_[0]),
    .O(_022_)
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _160_ (
    .I0(\u_uart.rx_state [2]),
    .I1(\u_uart.rx_state [9]),
    .I2(_066_[2]),
    .O(_005_)
  );
  CC_LUT2 #(
    .INIT(4'he)
  ) _161_ (
    .I0(_087_[0]),
    .I1(_087_[1]),
    .O(_024_)
  );
  CC_LUT4 #(
    .INIT(16'h8000)
  ) _162_ (
    .I0(_059_[3]),
    .I1(in[2]),
    .I2(in[0]),
    .I3(in[1]),
    .O(_087_[0])
  );
  CC_LUT4 #(
    .INIT(16'h4000)
  ) _163_ (
    .I0(_059_[3]),
    .I1(u_counter[27]),
    .I2(u_counter[25]),
    .I3(u_counter[26]),
    .O(_087_[1])
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _164_ (
    .I0(\u_uart.tx_state [7]),
    .I1(\u_uart.tx_state [3]),
    .I2(_064_[0]),
    .O(_021_)
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _165_ (
    .I0(\u_uart.tx_state [6]),
    .I1(\u_uart.tx_state [1]),
    .I2(_064_[0]),
    .O(_020_)
  );
  CC_LUT4 #(
    .INIT(16'hf444)
  ) _166_ (
    .I0(\u_uart.uart_rx_read ),
    .I1(\u_uart.tx_state [0]),
    .I2(_064_[0]),
    .I3(\u_uart.tx_state [2]),
    .O(_013_)
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _167_ (
    .I0(\u_uart.tx_state [5]),
    .I1(\u_uart.tx_state [7]),
    .I2(_064_[0]),
    .O(_019_)
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _168_ (
    .I0(\u_uart.tx_state [1]),
    .I1(\u_uart.tx_state [10]),
    .I2(_064_[0]),
    .O(_015_)
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _169_ (
    .I0(\u_uart.rx_state [8]),
    .I1(\u_uart.rx_state [4]),
    .I2(_066_[2]),
    .O(_011_)
  );
  CC_LUT3 #(
    .INIT(8'h10)
  ) _170_ (
    .I0(\u_uart.rx_state [2]),
    .I1(\u_uart.rx_state [0]),
    .I2(_066_[2]),
    .O(_025_)
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _171_ (
    .I0(\u_uart.rx_state [7]),
    .I1(\u_uart.rx_state [3]),
    .I2(_066_[2]),
    .O(_010_)
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _172_ (
    .I0(\u_uart.tx_state [2]),
    .I1(\u_uart.tx_state [9]),
    .I2(_064_[0]),
    .O(_016_)
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _173_ (
    .I0(\u_uart.tx_state [3]),
    .I1(\u_uart.tx_state [8]),
    .I2(_064_[0]),
    .O(_017_)
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _174_ (
    .I0(\u_uart.rx_state [6]),
    .I1(\u_uart.rx_state [1]),
    .I2(_066_[2]),
    .O(_009_)
  );
  CC_LUT4 #(
    .INIT(16'hf888)
  ) _175_ (
    .I0(\u_uart.rx_state [0]),
    .I1(\u_uart.uart_rx ),
    .I2(_066_[2]),
    .I3(\u_uart.rx_state [2]),
    .O(_003_)
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _176_ (
    .I0(\u_uart.rx_state [5]),
    .I1(\u_uart.rx_state [7]),
    .I2(_066_[2]),
    .O(_008_)
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _177_ (
    .I0(\u_uart.tx_state [4]),
    .I1(\u_uart.tx_state [6]),
    .I2(_064_[0]),
    .O(_018_)
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _178_ (
    .I0(\u_uart.tx_state [0]),
    .I1(_063_[1]),
    .O(_064_[2])
  );
  CC_LUT4 #(
    .INIT(16'hcf05)
  ) _179_ (
    .I0(\u_uart.tx_state [10]),
    .I1(_060_[1]),
    .I2(\u_uart.tx_state [3]),
    .I3(\u_uart.tick_1us ),
    .O(_064_[3])
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _180_ (
    .I0(\u_uart.rx_state [4]),
    .I1(\u_uart.rx_state [6]),
    .I2(_066_[2]),
    .O(_007_)
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _181_ (
    .I0(\u_uart.rx_state [9]),
    .I1(\u_uart.rx_state [5]),
    .I2(_066_[2]),
    .O(_012_)
  );
  CC_LUT4 #(
    .INIT(16'h4000)
  ) _182_ (
    .I0(in[2]),
    .I1(_059_[3]),
    .I2(in[0]),
    .I3(in[1]),
    .O(_034_)
  );
  CC_LUT4 #(
    .INIT(16'h1000)
  ) _183_ (
    .I0(in[2]),
    .I1(in[1]),
    .I2(in[0]),
    .I3(_059_[3]),
    .O(_032_)
  );
  CC_LUT4 #(
    .INIT(16'h1000)
  ) _184_ (
    .I0(in[2]),
    .I1(in[0]),
    .I2(_059_[3]),
    .I3(in[1]),
    .O(_033_)
  );
  CC_LUT4 #(
    .INIT(16'h4000)
  ) _185_ (
    .I0(in[1]),
    .I1(in[2]),
    .I2(in[0]),
    .I3(_059_[3]),
    .O(_036_)
  );
  CC_LUT4 #(
    .INIT(16'h0100)
  ) _186_ (
    .I0(in[2]),
    .I1(in[0]),
    .I2(in[1]),
    .I3(_059_[3]),
    .O(_031_)
  );
  CC_LUT4 #(
    .INIT(16'h4000)
  ) _187_ (
    .I0(in[0]),
    .I1(in[2]),
    .I2(_059_[3]),
    .I3(in[1]),
    .O(_037_)
  );
  CC_LUT4 #(
    .INIT(16'h1000)
  ) _188_ (
    .I0(in[0]),
    .I1(in[1]),
    .I2(_059_[3]),
    .I3(in[2]),
    .O(_035_)
  );
  CC_LUT3 #(
    .INIT(8'h40)
  ) _189_ (
    .I0(counter_24_prev),
    .I1(buffer_full),
    .I2(u_counter[24]),
    .O(_002_)
  );
  CC_LUT3 #(
    .INIT(8'hac)
  ) _190_ (
    .I0(_049_[2]),
    .I1(\u_uart.rx_cnt1us [2]),
    .I2(_069_[2]),
    .O(_073_[1])
  );
  CC_LUT3 #(
    .INIT(8'h4f)
  ) _191_ (
    .I0(_073_[0]),
    .I1(_073_[1]),
    .I2(_073_[2]),
    .O(_056_[2])
  );
  CC_LUT4 #(
    .INIT(16'h0001)
  ) _192_ (
    .I0(\u_uart.tx_state [7]),
    .I1(\u_uart.tx_state [6]),
    .I2(\u_uart.tx_state [8]),
    .I3(\u_uart.tx_state [1]),
    .O(_061_[3])
  );
  CC_LUT4 #(
    .INIT(16'hfeff)
  ) _193_ (
    .I0(\u_uart.tx_state [9]),
    .I1(\u_uart.tx_state [5]),
    .I2(\u_uart.tx_state [4]),
    .I3(_061_[3]),
    .O(_064_[1])
  );
  CC_LUT4 #(
    .INIT(16'h0b00)
  ) _194_ (
    .I0(_064_[0]),
    .I1(_064_[1]),
    .I2(_064_[2]),
    .I3(_064_[3]),
    .O(_027_)
  );
  CC_ADDF _195_ (
    .A(1'h1),
    .B(counter[0]),
    .CI(1'h0),
    .CO(_038_[1]),
    .S(_040_[0])
  );
  CC_ADDF _196_ (
    .A(1'h0),
    .B(counter[1]),
    .CI(_038_[1]),
    .CO(_038_[2]),
    .S(_040_[1])
  );
  CC_ADDF _197_ (
    .A(1'h0),
    .B(counter[2]),
    .CI(_038_[2]),
    .CO(_038_[3]),
    .S(_040_[2])
  );
  CC_ADDF _198_ (
    .A(1'h0),
    .B(counter[3]),
    .CI(_038_[3]),
    .CO(_038_[4]),
    .S(_040_[3])
  );
  CC_ADDF _199_ (
    .A(1'h0),
    .B(counter[4]),
    .CI(_038_[4]),
    .CO(_038_[5]),
    .S(_040_[4])
  );
  CC_ADDF _200_ (
    .A(1'h0),
    .B(counter[5]),
    .CI(_038_[5]),
    .CO(_039_[5]),
    .S(_040_[5])
  );
  CC_ADDF _201_ (
    .A(1'h1),
    .B(u_counter[0]),
    .CI(1'h0),
    .CO(_041_[1]),
    .S(_043_[0])
  );
  CC_ADDF _202_ (
    .A(1'h0),
    .B(u_counter[10]),
    .CI(_041_[10]),
    .CO(_041_[11]),
    .S(_043_[10])
  );
  CC_ADDF _203_ (
    .A(1'h0),
    .B(u_counter[11]),
    .CI(_041_[11]),
    .CO(_041_[12]),
    .S(_043_[11])
  );
  CC_ADDF _204_ (
    .A(1'h0),
    .B(u_counter[12]),
    .CI(_041_[12]),
    .CO(_041_[13]),
    .S(_043_[12])
  );
  CC_ADDF _205_ (
    .A(1'h0),
    .B(u_counter[13]),
    .CI(_041_[13]),
    .CO(_041_[14]),
    .S(_043_[13])
  );
  CC_ADDF _206_ (
    .A(1'h0),
    .B(u_counter[14]),
    .CI(_041_[14]),
    .CO(_041_[15]),
    .S(_043_[14])
  );
  CC_ADDF _207_ (
    .A(1'h0),
    .B(u_counter[15]),
    .CI(_041_[15]),
    .CO(_041_[16]),
    .S(_043_[15])
  );
  CC_ADDF _208_ (
    .A(1'h0),
    .B(u_counter[16]),
    .CI(_041_[16]),
    .CO(_041_[17]),
    .S(_043_[16])
  );
  CC_ADDF _209_ (
    .A(1'h0),
    .B(u_counter[17]),
    .CI(_041_[17]),
    .CO(_041_[18]),
    .S(_043_[17])
  );
  CC_ADDF _210_ (
    .A(1'h0),
    .B(u_counter[18]),
    .CI(_041_[18]),
    .CO(_041_[19]),
    .S(_043_[18])
  );
  CC_ADDF _211_ (
    .A(1'h0),
    .B(u_counter[19]),
    .CI(_041_[19]),
    .CO(_041_[20]),
    .S(_043_[19])
  );
  CC_ADDF _212_ (
    .A(1'h0),
    .B(u_counter[1]),
    .CI(_041_[1]),
    .CO(_041_[2]),
    .S(_043_[1])
  );
  CC_ADDF _213_ (
    .A(1'h0),
    .B(u_counter[20]),
    .CI(_041_[20]),
    .CO(_041_[21]),
    .S(_043_[20])
  );
  CC_ADDF _214_ (
    .A(1'h0),
    .B(u_counter[21]),
    .CI(_041_[21]),
    .CO(_041_[22]),
    .S(_043_[21])
  );
  CC_ADDF _215_ (
    .A(1'h0),
    .B(u_counter[22]),
    .CI(_041_[22]),
    .CO(_041_[23]),
    .S(_043_[22])
  );
  CC_ADDF _216_ (
    .A(1'h0),
    .B(u_counter[23]),
    .CI(_041_[23]),
    .CO(_041_[24]),
    .S(_043_[23])
  );
  CC_ADDF _217_ (
    .A(1'h0),
    .B(u_counter[24]),
    .CI(_041_[24]),
    .CO(_041_[25]),
    .S(_043_[24])
  );
  CC_ADDF _218_ (
    .A(1'h0),
    .B(u_counter[25]),
    .CI(_041_[25]),
    .CO(_041_[26]),
    .S(_043_[25])
  );
  CC_ADDF _219_ (
    .A(1'h0),
    .B(u_counter[26]),
    .CI(_041_[26]),
    .CO(_041_[27]),
    .S(_043_[26])
  );
  CC_ADDF _220_ (
    .A(1'h0),
    .B(u_counter[27]),
    .CI(_041_[27]),
    .CO(_042_[27]),
    .S(_043_[27])
  );
  CC_ADDF _221_ (
    .A(1'h0),
    .B(u_counter[2]),
    .CI(_041_[2]),
    .CO(_041_[3]),
    .S(_043_[2])
  );
  CC_ADDF _222_ (
    .A(1'h0),
    .B(u_counter[3]),
    .CI(_041_[3]),
    .CO(_041_[4]),
    .S(_043_[3])
  );
  CC_ADDF _223_ (
    .A(1'h0),
    .B(u_counter[4]),
    .CI(_041_[4]),
    .CO(_041_[5]),
    .S(_043_[4])
  );
  CC_ADDF _224_ (
    .A(1'h0),
    .B(u_counter[5]),
    .CI(_041_[5]),
    .CO(_041_[6]),
    .S(_043_[5])
  );
  CC_ADDF _225_ (
    .A(1'h0),
    .B(u_counter[6]),
    .CI(_041_[6]),
    .CO(_041_[7]),
    .S(_043_[6])
  );
  CC_ADDF _226_ (
    .A(1'h0),
    .B(u_counter[7]),
    .CI(_041_[7]),
    .CO(_041_[8]),
    .S(_043_[7])
  );
  CC_ADDF _227_ (
    .A(1'h0),
    .B(u_counter[8]),
    .CI(_041_[8]),
    .CO(_041_[9]),
    .S(_043_[8])
  );
  CC_ADDF _228_ (
    .A(1'h0),
    .B(u_counter[9]),
    .CI(_041_[9]),
    .CO(_041_[10]),
    .S(_043_[9])
  );
  CC_ADDF _229_ (
    .A(1'h1),
    .B(in[0]),
    .CI(1'h0),
    .CO(_044_[1]),
    .S(_046_[0])
  );
  CC_ADDF _230_ (
    .A(1'h0),
    .B(in[1]),
    .CI(_044_[1]),
    .CO(_044_[2]),
    .S(_046_[1])
  );
  CC_ADDF _231_ (
    .A(1'h0),
    .B(in[2]),
    .CI(_044_[2]),
    .CO(_045_[2]),
    .S(_046_[2])
  );
  CC_ADDF _232_ (
    .A(\u_uart.rx_cnt1us [0]),
    .B(1'h0),
    .CI(1'h1),
    .CO(_047_[1]),
    .S(_049_[0])
  );
  CC_ADDF _233_ (
    .A(\u_uart.rx_cnt1us [1]),
    .B(1'h1),
    .CI(_047_[1]),
    .CO(_047_[2]),
    .S(_049_[1])
  );
  CC_ADDF _234_ (
    .A(\u_uart.rx_cnt1us [2]),
    .B(1'h1),
    .CI(_047_[2]),
    .CO(_047_[3]),
    .S(_049_[2])
  );
  CC_ADDF _235_ (
    .A(\u_uart.rx_cnt1us [3]),
    .B(1'h1),
    .CI(_047_[3]),
    .CO(_048_[3]),
    .S(_049_[3])
  );
  CC_ADDF _236_ (
    .A(\u_uart.tx_cnt1us [0]),
    .B(1'h0),
    .CI(1'h1),
    .CO(_050_[1]),
    .S(_052_[0])
  );
  CC_ADDF _237_ (
    .A(\u_uart.tx_cnt1us [1]),
    .B(1'h1),
    .CI(_050_[1]),
    .CO(_050_[2]),
    .S(_052_[1])
  );
  CC_ADDF _238_ (
    .A(\u_uart.tx_cnt1us [2]),
    .B(1'h1),
    .CI(_050_[2]),
    .CO(_050_[3]),
    .S(_052_[2])
  );
  CC_ADDF _239_ (
    .A(\u_uart.tx_cnt1us [3]),
    .B(1'h1),
    .CI(_050_[3]),
    .CO(_051_[3]),
    .S(_052_[3])
  );
  CC_BUFG _240_ (
    .I(_053_),
    .O(\u_uart.clk )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _241_ (
    .CLK(\u_uart.clk ),
    .D(_043_[16]),
    .EN(1'h1),
    .Q(u_counter[16]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _242_ (
    .CLK(\u_uart.clk ),
    .D(_043_[17]),
    .EN(1'h1),
    .Q(u_counter[17]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _243_ (
    .CLK(\u_uart.clk ),
    .D(_043_[18]),
    .EN(1'h1),
    .Q(u_counter[18]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _244_ (
    .CLK(\u_uart.clk ),
    .D(_043_[19]),
    .EN(1'h1),
    .Q(u_counter[19]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _245_ (
    .CLK(\u_uart.clk ),
    .D(_043_[20]),
    .EN(1'h1),
    .Q(u_counter[20]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _246_ (
    .CLK(\u_uart.clk ),
    .D(_043_[21]),
    .EN(1'h1),
    .Q(u_counter[21]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _247_ (
    .CLK(\u_uart.clk ),
    .D(_043_[22]),
    .EN(1'h1),
    .Q(u_counter[22]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _248_ (
    .CLK(\u_uart.clk ),
    .D(_043_[23]),
    .EN(1'h1),
    .Q(u_counter[23]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _249_ (
    .CLK(\u_uart.clk ),
    .D(_043_[24]),
    .EN(1'h1),
    .Q(u_counter[24]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _250_ (
    .CLK(\u_uart.clk ),
    .D(_043_[25]),
    .EN(1'h1),
    .Q(u_counter[25]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _251_ (
    .CLK(\u_uart.clk ),
    .D(_043_[26]),
    .EN(1'h1),
    .Q(u_counter[26]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _252_ (
    .CLK(\u_uart.clk ),
    .D(_043_[27]),
    .EN(1'h1),
    .Q(u_counter[27]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _253_ (
    .CLK(\u_uart.clk ),
    .D(_000_[0]),
    .EN(1'h1),
    .Q(counter[0]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _254_ (
    .CLK(\u_uart.clk ),
    .D(_000_[1]),
    .EN(1'h1),
    .Q(counter[1]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _255_ (
    .CLK(\u_uart.clk ),
    .D(_000_[2]),
    .EN(1'h1),
    .Q(counter[2]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _256_ (
    .CLK(\u_uart.clk ),
    .D(_000_[3]),
    .EN(1'h1),
    .Q(counter[3]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _257_ (
    .CLK(\u_uart.clk ),
    .D(_000_[4]),
    .EN(1'h1),
    .Q(counter[4]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _258_ (
    .CLK(\u_uart.clk ),
    .D(_000_[5]),
    .EN(1'h1),
    .Q(counter[5]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _259_ (
    .CLK(\u_uart.clk ),
    .D(_059_[3]),
    .EN(_024_),
    .Q(buffer_full),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _260_ (
    .CLK(\u_uart.clk ),
    .D(\u_uart.uart_rx ),
    .EN(_087_[0]),
    .Q(\buffer[7] ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h1)
  ) _261_ (
    .CLK(\u_uart.clk ),
    .D(_003_),
    .EN(1'h1),
    .Q(\u_uart.rx_state [0]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _262_ (
    .CLK(\u_uart.clk ),
    .D(_004_),
    .EN(1'h1),
    .Q(\u_uart.rx_state [1]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _263_ (
    .CLK(\u_uart.clk ),
    .D(_005_),
    .EN(1'h1),
    .Q(\u_uart.rx_state [2]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _264_ (
    .CLK(\u_uart.clk ),
    .D(_006_),
    .EN(1'h1),
    .Q(\u_uart.rx_state [3]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _265_ (
    .CLK(\u_uart.clk ),
    .D(_007_),
    .EN(1'h1),
    .Q(\u_uart.rx_state [4]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _266_ (
    .CLK(\u_uart.clk ),
    .D(_008_),
    .EN(1'h1),
    .Q(\u_uart.rx_state [5]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _267_ (
    .CLK(\u_uart.clk ),
    .D(_009_),
    .EN(1'h1),
    .Q(\u_uart.rx_state [6]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _268_ (
    .CLK(\u_uart.clk ),
    .D(_010_),
    .EN(1'h1),
    .Q(\u_uart.rx_state [7]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _269_ (
    .CLK(\u_uart.clk ),
    .D(_011_),
    .EN(1'h1),
    .Q(\u_uart.rx_state [8]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _270_ (
    .CLK(\u_uart.clk ),
    .D(_012_),
    .EN(1'h1),
    .Q(\u_uart.rx_state [9]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _271_ (
    .CLK(\u_uart.clk ),
    .D(\u_uart.uart_rx ),
    .EN(_034_),
    .Q(\buffer[3] ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _272_ (
    .CLK(\u_uart.clk ),
    .D(\u_uart.uart_rx ),
    .EN(_033_),
    .Q(\buffer[2] ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _273_ (
    .CLK(\u_uart.clk ),
    .D(_075_[0]),
    .EN(\u_uart.arst_n ),
    .Q(\u_uart.tick_1us ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _274_ (
    .CLK(\u_uart.clk ),
    .D(\u_uart.uart_rx ),
    .EN(_032_),
    .Q(\buffer[1] ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _275_ (
    .CLK(\u_uart.clk ),
    .D(_026_),
    .EN(1'h1),
    .Q(\u_uart.uart_rx_read ),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _276_ (
    .CLK(\u_uart.clk ),
    .D(\u_uart.uart_rx ),
    .EN(_037_),
    .Q(\buffer[6] ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _277_ (
    .CLK(\u_uart.clk ),
    .D(\u_uart.uart_rx ),
    .EN(_036_),
    .Q(\buffer[5] ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _278_ (
    .CLK(\u_uart.clk ),
    .D(\u_uart.uart_rx ),
    .EN(_035_),
    .Q(\buffer[4] ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _279_ (
    .CLK(\u_uart.clk ),
    .D(_054_[0]),
    .EN(1'h1),
    .Q(\u_uart.tx_cnt1us [0]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _280_ (
    .CLK(\u_uart.clk ),
    .D(_054_[1]),
    .EN(1'h1),
    .Q(\u_uart.tx_cnt1us [1]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _281_ (
    .CLK(\u_uart.clk ),
    .D(_054_[2]),
    .EN(1'h1),
    .Q(\u_uart.tx_cnt1us [2]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _282_ (
    .CLK(\u_uart.clk ),
    .D(_054_[3]),
    .EN(1'h1),
    .Q(\u_uart.tx_cnt1us [3]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h1)
  ) _283_ (
    .CLK(\u_uart.clk ),
    .D(_055_),
    .EN(_027_),
    .Q(\u_uart.uart_tx ),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _284_ (
    .CLK(\u_uart.clk ),
    .D(\u_uart.uart_rx_arr [0]),
    .EN(_086_[2]),
    .Q(\u_uart.tx_data [0]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _285_ (
    .CLK(\u_uart.clk ),
    .D(\u_uart.uart_rx_arr [1]),
    .EN(_086_[2]),
    .Q(\u_uart.tx_data [1]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _286_ (
    .CLK(\u_uart.clk ),
    .D(\u_uart.uart_rx_arr [2]),
    .EN(_086_[2]),
    .Q(\u_uart.tx_data [2]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _287_ (
    .CLK(\u_uart.clk ),
    .D(\u_uart.uart_rx_arr [3]),
    .EN(_086_[2]),
    .Q(\u_uart.tx_data [3]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _288_ (
    .CLK(\u_uart.clk ),
    .D(\u_uart.uart_rx_arr [4]),
    .EN(_086_[2]),
    .Q(\u_uart.tx_data [4]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _289_ (
    .CLK(\u_uart.clk ),
    .D(\u_uart.uart_rx_arr [5]),
    .EN(_086_[2]),
    .Q(\u_uart.tx_data [5]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _290_ (
    .CLK(\u_uart.clk ),
    .D(\u_uart.uart_rx_arr [6]),
    .EN(_086_[2]),
    .Q(\u_uart.tx_data [6]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _291_ (
    .CLK(\u_uart.clk ),
    .D(\u_uart.uart_rx_arr [7]),
    .EN(_086_[2]),
    .Q(\u_uart.tx_data [7]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _292_ (
    .CLK(\u_uart.clk ),
    .D(_056_[0]),
    .EN(1'h1),
    .Q(\u_uart.rx_cnt1us [0]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _293_ (
    .CLK(\u_uart.clk ),
    .D(_056_[1]),
    .EN(1'h1),
    .Q(\u_uart.rx_cnt1us [1]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _294_ (
    .CLK(\u_uart.clk ),
    .D(_056_[2]),
    .EN(1'h1),
    .Q(\u_uart.rx_cnt1us [2]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _295_ (
    .CLK(\u_uart.clk ),
    .D(_056_[3]),
    .EN(1'h1),
    .Q(\u_uart.rx_cnt1us [3]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _296_ (
    .CLK(\u_uart.clk ),
    .D(\u_uart.rx_shift [0]),
    .EN(_026_),
    .Q(\u_uart.uart_rx_arr [0]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _297_ (
    .CLK(\u_uart.clk ),
    .D(\u_uart.rx_shift [1]),
    .EN(_026_),
    .Q(\u_uart.uart_rx_arr [1]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _298_ (
    .CLK(\u_uart.clk ),
    .D(\u_uart.rx_shift [2]),
    .EN(_026_),
    .Q(\u_uart.uart_rx_arr [2]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _299_ (
    .CLK(\u_uart.clk ),
    .D(\u_uart.rx_shift [3]),
    .EN(_026_),
    .Q(\u_uart.uart_rx_arr [3]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _300_ (
    .CLK(\u_uart.clk ),
    .D(\u_uart.rx_shift [4]),
    .EN(_026_),
    .Q(\u_uart.uart_rx_arr [4]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _301_ (
    .CLK(\u_uart.clk ),
    .D(\u_uart.rx_shift [5]),
    .EN(_026_),
    .Q(\u_uart.uart_rx_arr [5]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _302_ (
    .CLK(\u_uart.clk ),
    .D(\u_uart.rx_shift [6]),
    .EN(_026_),
    .Q(\u_uart.uart_rx_arr [6]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _303_ (
    .CLK(\u_uart.clk ),
    .D(\u_uart.rx_shift [7]),
    .EN(_026_),
    .Q(\u_uart.uart_rx_arr [7]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h1)
  ) _304_ (
    .CLK(\u_uart.clk ),
    .D(_013_),
    .EN(1'h1),
    .Q(\u_uart.tx_state [0]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _305_ (
    .CLK(\u_uart.clk ),
    .D(_015_),
    .EN(1'h1),
    .Q(\u_uart.tx_state [1]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _306_ (
    .CLK(\u_uart.clk ),
    .D(_016_),
    .EN(1'h1),
    .Q(\u_uart.tx_state [2]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _307_ (
    .CLK(\u_uart.clk ),
    .D(_017_),
    .EN(1'h1),
    .Q(\u_uart.tx_state [3]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _308_ (
    .CLK(\u_uart.clk ),
    .D(_018_),
    .EN(1'h1),
    .Q(\u_uart.tx_state [4]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _309_ (
    .CLK(\u_uart.clk ),
    .D(_019_),
    .EN(1'h1),
    .Q(\u_uart.tx_state [5]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _310_ (
    .CLK(\u_uart.clk ),
    .D(_020_),
    .EN(1'h1),
    .Q(\u_uart.tx_state [6]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _311_ (
    .CLK(\u_uart.clk ),
    .D(_021_),
    .EN(1'h1),
    .Q(\u_uart.tx_state [7]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _312_ (
    .CLK(\u_uart.clk ),
    .D(_022_),
    .EN(1'h1),
    .Q(\u_uart.tx_state [8]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _313_ (
    .CLK(\u_uart.clk ),
    .D(_023_),
    .EN(1'h1),
    .Q(\u_uart.tx_state [9]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _314_ (
    .CLK(\u_uart.clk ),
    .D(_014_),
    .EN(1'h1),
    .Q(\u_uart.tx_state [10]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _315_ (
    .CLK(\u_uart.clk ),
    .D(\u_uart.uart_rx ),
    .EN(_031_),
    .Q(\buffer[0] ),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _316_ (
    .CLK(\u_uart.clk ),
    .D(_001_),
    .EN(_002_),
    .Q(_058_),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _317_ (
    .CLK(\u_uart.clk ),
    .D(\u_uart.rx_shift [1]),
    .EN(_025_),
    .Q(\u_uart.rx_shift [0]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _318_ (
    .CLK(\u_uart.clk ),
    .D(\u_uart.rx_shift [2]),
    .EN(_025_),
    .Q(\u_uart.rx_shift [1]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _319_ (
    .CLK(\u_uart.clk ),
    .D(\u_uart.rx_shift [3]),
    .EN(_025_),
    .Q(\u_uart.rx_shift [2]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _320_ (
    .CLK(\u_uart.clk ),
    .D(\u_uart.rx_shift [4]),
    .EN(_025_),
    .Q(\u_uart.rx_shift [3]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _321_ (
    .CLK(\u_uart.clk ),
    .D(\u_uart.rx_shift [5]),
    .EN(_025_),
    .Q(\u_uart.rx_shift [4]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _322_ (
    .CLK(\u_uart.clk ),
    .D(\u_uart.rx_shift [6]),
    .EN(_025_),
    .Q(\u_uart.rx_shift [5]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _323_ (
    .CLK(\u_uart.clk ),
    .D(\u_uart.rx_shift [7]),
    .EN(_025_),
    .Q(\u_uart.rx_shift [6]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _324_ (
    .CLK(\u_uart.clk ),
    .D(\u_uart.uart_rx ),
    .EN(_025_),
    .Q(\u_uart.rx_shift [7]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _325_ (
    .CLK(\u_uart.clk ),
    .D(u_counter[24]),
    .EN(1'h1),
    .Q(counter_24_prev),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _326_ (
    .CLK(\u_uart.clk ),
    .D(_028_),
    .EN(_059_[3]),
    .Q(in[0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _327_ (
    .CLK(\u_uart.clk ),
    .D(_029_),
    .EN(_059_[3]),
    .Q(in[1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _328_ (
    .CLK(\u_uart.clk ),
    .D(_030_),
    .EN(_059_[3]),
    .Q(in[2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _329_ (
    .CLK(\u_uart.clk ),
    .D(\u_uart.uart_rx ),
    .EN(1'h1),
    .Q(uart_rx_prev),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _330_ (
    .CLK(\u_uart.clk ),
    .D(_043_[0]),
    .EN(1'h1),
    .Q(u_counter[0]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _331_ (
    .CLK(\u_uart.clk ),
    .D(_043_[1]),
    .EN(1'h1),
    .Q(u_counter[1]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _332_ (
    .CLK(\u_uart.clk ),
    .D(_043_[2]),
    .EN(1'h1),
    .Q(u_counter[2]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _333_ (
    .CLK(\u_uart.clk ),
    .D(_043_[3]),
    .EN(1'h1),
    .Q(u_counter[3]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _334_ (
    .CLK(\u_uart.clk ),
    .D(_043_[4]),
    .EN(1'h1),
    .Q(u_counter[4]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _335_ (
    .CLK(\u_uart.clk ),
    .D(_043_[5]),
    .EN(1'h1),
    .Q(u_counter[5]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _336_ (
    .CLK(\u_uart.clk ),
    .D(_043_[6]),
    .EN(1'h1),
    .Q(u_counter[6]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _337_ (
    .CLK(\u_uart.clk ),
    .D(_043_[7]),
    .EN(1'h1),
    .Q(u_counter[7]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _338_ (
    .CLK(\u_uart.clk ),
    .D(_043_[8]),
    .EN(1'h1),
    .Q(u_counter[8]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _339_ (
    .CLK(\u_uart.clk ),
    .D(_043_[9]),
    .EN(1'h1),
    .Q(u_counter[9]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _340_ (
    .CLK(\u_uart.clk ),
    .D(_043_[10]),
    .EN(1'h1),
    .Q(u_counter[10]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _341_ (
    .CLK(\u_uart.clk ),
    .D(_043_[11]),
    .EN(1'h1),
    .Q(u_counter[11]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _342_ (
    .CLK(\u_uart.clk ),
    .D(_043_[12]),
    .EN(1'h1),
    .Q(u_counter[12]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _343_ (
    .CLK(\u_uart.clk ),
    .D(_043_[13]),
    .EN(1'h1),
    .Q(u_counter[13]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _344_ (
    .CLK(\u_uart.clk ),
    .D(_043_[14]),
    .EN(1'h1),
    .Q(u_counter[14]),
    .SR(\u_uart.arst_n )
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _345_ (
    .CLK(\u_uart.clk ),
    .D(_043_[15]),
    .EN(1'h1),
    .Q(u_counter[15]),
    .SR(\u_uart.arst_n )
  );
  CC_MX4 _346_ (
    .D0(\buffer[0] ),
    .D1(\buffer[1] ),
    .D2(\buffer[2] ),
    .D3(\buffer[3] ),
    .S0(u_counter[25]),
    .S1(u_counter[26]),
    .Y(_085_[1])
  );
  CC_MX4 _347_ (
    .D0(\buffer[4] ),
    .D1(\buffer[5] ),
    .D2(\buffer[6] ),
    .D3(\buffer[7] ),
    .S0(u_counter[25]),
    .S1(u_counter[26]),
    .Y(_085_[0])
  );
  CC_IBUF _348_ (
    .I(arst_n),
    .Y(\u_uart.arst_n )
  );
  CC_IBUF _349_ (
    .I(clk),
    .Y(_057_)
  );
  CC_OBUF _350_ (
    .A(_058_),
    .O(led)
  );
  CC_OBUF _351_ (
    .A(\u_uart.uart_rx ),
    .O(received)
  );
  CC_OBUF _352_ (
    .A(\u_uart.uart_rx ),
    .O(sent)
  );
  CC_OBUF _353_ (
    .A(\u_uart.tick_1us ),
    .O(tick_1us)
  );
  CC_IBUF _354_ (
    .I(uart_rx),
    .Y(\u_uart.uart_rx )
  );
  CC_OBUF _355_ (
    .A(\u_uart.uart_tx ),
    .O(uart_tx)
  );
  CC_PLL #(
    .CI_FILTER_CONST(32'sd2),
    .CP_FILTER_CONST(32'sd4),
    .LOW_JITTER(32'sd1),
    .OUT_CLK("40.0"),
    .PERF_MD("ECONOMY"),
    .REF_CLK("10.0")
  ) u_pll (
    .CLK0(_053_),
    .CLK180(clk180),
    .CLK270(clk270),
    .CLK90(clk90),
    .CLK_FEEDBACK(1'h0),
    .CLK_REF(_057_),
    .CLK_REF_OUT(usr_ref_out),
    .USR_CLK_REF(1'h0),
    .USR_LOCKED_STDY_RST(1'h0),
    .USR_PLL_LOCKED(usr_pll_lock),
    .USR_PLL_LOCKED_STDY(usr_pll_lock_stdy)
  );
  assign _038_[0] = 1'h0;
  assign _039_[4:0] = _038_[5:1];
  assign _041_[0] = 1'h0;
  assign _042_[26:0] = _041_[27:1];
  assign _044_[0] = 1'h0;
  assign _045_[1:0] = _044_[2:1];
  assign _047_[0] = 1'h1;
  assign _048_[2:0] = _047_[3:1];
  assign _050_[0] = 1'h1;
  assign _051_[2:0] = _050_[3:1];
  assign _059_[2:0] = { in[0], in[1], in[2] };
  assign { _060_[3:2], _060_[0] } = { \u_uart.tick_1us , \u_uart.tx_state [3], \u_uart.tx_state [10] };
  assign _061_[2:0] = { \u_uart.tx_state [4], \u_uart.tx_state [5], \u_uart.tx_state [9] };
  assign _062_[0] = \u_uart.tx_state [9];
  assign _063_[0] = \u_uart.tx_state [0];
  assign _066_[1:0] = { \u_uart.rx_state [1], \u_uart.rx_state [6] };
  assign { _067_[2], _067_[0] } = { \u_uart.tx_state [0], _064_[0] };
  assign _068_[3] = \u_uart.tick_1us ;
  assign _069_[1:0] = { \u_uart.rx_cnt1us [2], _049_[2] };
  assign _070_[3:1] = { _065_, \u_uart.rx_state [2] };
  assign _071_[1] = \u_uart.rx_state [0];
  assign _072_[2:1] = { _066_[2], \u_uart.rx_state [2] };
  assign _074_[1:0] = counter[4:3];
  assign _075_[1] = _040_[3];
  assign _076_[1:0] = { \u_uart.tx_state [7], \u_uart.tx_data [6] };
  assign { _079_[3], _079_[0] } = { _078_[2], _077_[1] };
  assign _080_[1:0] = { \u_uart.tx_state [5], \u_uart.tx_data [7] };
  assign { _083_[2], _083_[0] } = { \u_uart.rx_state [0], _073_[0] };
  assign { _084_[2], _084_[0] } = { _073_[2], _073_[0] };
  assign _085_[2] = u_counter[27];
  assign _086_[1:0] = { \u_uart.tx_state [10], _064_[0] };
  assign { _088_[3], _088_[0] } = { _078_[2], _077_[1] };
  assign \u_uart.uart_rx_arr [9:8] = { \u_uart.uart_rx_read , 1'hx };
endmodule
