/* Generated by Yosys 0.36+58 (git sha1 ea7818d31, c++ 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module afifo(i_wclk, i_wr_reset_n, i_wr, i_wr_data, o_wr_full, i_rclk, i_rd_reset_n, i_rd, o_rd_data, o_rd_empty);
  wire [15:0] _000_;
  wire [15:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire [3:0] _017_;
  wire [3:0] _018_;
  wire [3:0] _019_;
  wire [3:0] _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire [15:0] _025_;
  wire _026_;
  wire [15:0] _027_;
  wire [2:0] _028_;
  wire [2:0] _029_;
  wire [1:0] _030_;
  wire [1:0] _031_;
  wire [2:0] _032_;
  wire [2:0] _033_;
  wire [2:0] _034_;
  wire [2:0] _035_;
  wire [2:0] _036_;
  wire [2:0] _037_;
  wire [2:0] _038_;
  wire [2:0] _039_;
  wire [2:0] _040_;
  wire [2:0] _041_;
  wire [2:0] _042_;
  wire [1:0] _043_;
  wire [2:0] _044_;
  wire [2:0] _045_;
  wire [1:0] _046_;
  wire [2:0] _047_;
  wire [2:0] _048_;
  wire [2:0] _049_;
  input i_rclk;
  wire i_rclk;
  input i_rd;
  wire i_rd;
  input i_rd_reset_n;
  wire i_rd_reset_n;
  input i_wclk;
  wire i_wclk;
  input i_wr;
  wire i_wr;
  input [15:0] i_wr_data;
  wire [15:0] i_wr_data;
  input i_wr_reset_n;
  wire i_wr_reset_n;
  wire lcl_rd_empty;
  wire lcl_read;
  wire [15:0] \mem[0] ;
  wire [15:0] \mem[1] ;
  wire [15:0] \mem[2] ;
  wire [15:0] \mem[3] ;
  wire [15:0] \mem[4] ;
  wire [15:0] \mem[5] ;
  wire [15:0] \mem[6] ;
  wire [15:0] \mem[7] ;
  wire [3:0] next_rd_addr;
  wire [3:0] next_wr_addr;
  output [15:0] o_rd_data;
  wire [15:0] o_rd_data;
  output o_rd_empty;
  wire o_rd_empty;
  output o_wr_full;
  wire o_wr_full;
  wire [3:0] rd_addr;
  wire [3:0] rd_wgray;
  wire [3:0] rgray;
  wire [3:0] rgray_cross;
  wire wclk;
  wire [3:0] wgray;
  wire [3:0] wgray_cross;
  wire [3:0] wr_addr;
  wire [3:0] wr_rgray;
  CC_LUT3 #(
    .INIT(8'h40)
  ) _050_ (
    .I0(wr_addr[2]),
    .I1(wr_addr[1]),
    .I2(_049_[2]),
    .O(_011_)
  );
  CC_LUT4 #(
    .INIT(16'h0700)
  ) _051_ (
    .I0(_030_[1]),
    .I1(_030_[0]),
    .I2(wr_addr[0]),
    .I3(_031_[1]),
    .O(_049_[2])
  );
  CC_LUT2 #(
    .INIT(4'h6)
  ) _052_ (
    .I0(next_rd_addr[0]),
    .I1(next_rd_addr[1]),
    .O(_005_)
  );
  CC_LUT2 #(
    .INIT(4'h6)
  ) _053_ (
    .I0(next_rd_addr[1]),
    .I1(next_rd_addr[2]),
    .O(_006_)
  );
  CC_LUT2 #(
    .INIT(4'h6)
  ) _054_ (
    .I0(next_rd_addr[2]),
    .I1(next_rd_addr[3]),
    .O(_007_)
  );
  CC_LUT3 #(
    .INIT(8'h40)
  ) _055_ (
    .I0(wr_addr[2]),
    .I1(wr_addr[1]),
    .I2(_032_[2]),
    .O(_012_)
  );
  CC_LUT3 #(
    .INIT(8'h10)
  ) _056_ (
    .I0(wr_addr[1]),
    .I1(wr_addr[2]),
    .I2(_049_[2]),
    .O(_009_)
  );
  CC_LUT3 #(
    .INIT(8'h40)
  ) _057_ (
    .I0(wr_addr[1]),
    .I1(_049_[2]),
    .I2(wr_addr[2]),
    .O(_013_)
  );
  CC_LUT3 #(
    .INIT(8'h40)
  ) _058_ (
    .I0(wr_addr[1]),
    .I1(_032_[2]),
    .I2(wr_addr[2]),
    .O(_014_)
  );
  CC_LUT3 #(
    .INIT(8'h80)
  ) _059_ (
    .I0(_049_[2]),
    .I1(wr_addr[1]),
    .I2(wr_addr[2]),
    .O(_015_)
  );
  CC_LUT3 #(
    .INIT(8'h80)
  ) _060_ (
    .I0(_032_[2]),
    .I1(wr_addr[1]),
    .I2(wr_addr[2]),
    .O(_016_)
  );
  CC_LUT3 #(
    .INIT(8'hac)
  ) _061_ (
    .I0(_033_[0]),
    .I1(_033_[1]),
    .I2(rd_addr[2]),
    .O(_001_[0])
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _062_ (
    .I0(_037_[0]),
    .I1(_037_[1]),
    .I2(rd_addr[2]),
    .O(_001_[1])
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _063_ (
    .I0(_039_[0]),
    .I1(_039_[1]),
    .I2(rd_addr[2]),
    .O(_001_[2])
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _064_ (
    .I0(_040_[0]),
    .I1(_040_[1]),
    .I2(rd_addr[2]),
    .O(_001_[3])
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _065_ (
    .I0(_028_[0]),
    .I1(_028_[1]),
    .I2(rd_addr[2]),
    .O(_001_[4])
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _066_ (
    .I0(_034_[0]),
    .I1(_034_[1]),
    .I2(rd_addr[2]),
    .O(_001_[5])
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _067_ (
    .I0(_035_[0]),
    .I1(_035_[1]),
    .I2(rd_addr[2]),
    .O(_001_[6])
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _068_ (
    .I0(_041_[0]),
    .I1(_041_[1]),
    .I2(rd_addr[2]),
    .O(_001_[7])
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _069_ (
    .I0(_042_[0]),
    .I1(_042_[1]),
    .I2(rd_addr[2]),
    .O(_001_[8])
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _070_ (
    .I0(_044_[0]),
    .I1(_044_[1]),
    .I2(rd_addr[2]),
    .O(_001_[9])
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _071_ (
    .I0(_029_[0]),
    .I1(_029_[1]),
    .I2(rd_addr[2]),
    .O(_001_[10])
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _072_ (
    .I0(_036_[0]),
    .I1(_036_[1]),
    .I2(rd_addr[2]),
    .O(_001_[11])
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _073_ (
    .I0(_038_[0]),
    .I1(_038_[1]),
    .I2(rd_addr[2]),
    .O(_001_[12])
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _074_ (
    .I0(_045_[0]),
    .I1(_045_[1]),
    .I2(rd_addr[2]),
    .O(_001_[13])
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _075_ (
    .I0(_047_[0]),
    .I1(_047_[1]),
    .I2(rd_addr[2]),
    .O(_001_[14])
  );
  CC_LUT3 #(
    .INIT(8'hca)
  ) _076_ (
    .I0(_048_[0]),
    .I1(_048_[1]),
    .I2(rd_addr[2]),
    .O(_001_[15])
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _077_ (
    .I0(_030_[0]),
    .I1(_030_[1]),
    .O(_031_[0])
  );
  CC_LUT4 #(
    .INIT(16'h9009)
  ) _078_ (
    .I0(wr_rgray[0]),
    .I1(wgray[0]),
    .I2(wr_rgray[1]),
    .I3(wgray[1]),
    .O(_030_[0])
  );
  CC_LUT4 #(
    .INIT(16'h1428)
  ) _079_ (
    .I0(wgray[2]),
    .I1(wgray[3]),
    .I2(wr_rgray[3]),
    .I3(wr_rgray[2]),
    .O(_030_[1])
  );
  CC_LUT2 #(
    .INIT(4'h8)
  ) _080_ (
    .I0(_046_[0]),
    .I1(_046_[1]),
    .O(lcl_rd_empty)
  );
  CC_LUT4 #(
    .INIT(16'h9009)
  ) _081_ (
    .I0(rd_wgray[0]),
    .I1(rgray[0]),
    .I2(rd_wgray[1]),
    .I3(rgray[1]),
    .O(_046_[0])
  );
  CC_LUT4 #(
    .INIT(16'h9009)
  ) _082_ (
    .I0(rd_wgray[2]),
    .I1(rgray[2]),
    .I2(rd_wgray[3]),
    .I3(rd_addr[3]),
    .O(_046_[1])
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _083_ (
    .I0(_031_[0]),
    .I1(_031_[1]),
    .O(_000_[15])
  );
  CC_LUT2 #(
    .INIT(4'he)
  ) _084_ (
    .I0(_043_[0]),
    .I1(_043_[1]),
    .O(lcl_read)
  );
  CC_LUT2 #(
    .INIT(4'h4)
  ) _085_ (
    .I0(lcl_rd_empty),
    .I1(lcl_read),
    .O(_008_)
  );
  CC_LUT2 #(
    .INIT(4'h6)
  ) _086_ (
    .I0(next_wr_addr[0]),
    .I1(next_wr_addr[1]),
    .O(_002_)
  );
  CC_LUT2 #(
    .INIT(4'h6)
  ) _087_ (
    .I0(next_wr_addr[1]),
    .I1(next_wr_addr[2]),
    .O(_003_)
  );
  CC_LUT2 #(
    .INIT(4'h6)
  ) _088_ (
    .I0(next_wr_addr[2]),
    .I1(next_wr_addr[3]),
    .O(_004_)
  );
  CC_LUT3 #(
    .INIT(8'h10)
  ) _089_ (
    .I0(wr_addr[1]),
    .I1(wr_addr[2]),
    .I2(_032_[2]),
    .O(_010_)
  );
  CC_LUT4 #(
    .INIT(16'h7000)
  ) _090_ (
    .I0(_030_[1]),
    .I1(_030_[0]),
    .I2(wr_addr[0]),
    .I3(_031_[1]),
    .O(_032_[2])
  );
  CC_ADDF _091_ (
    .A(1'h1),
    .B(wr_addr[0]),
    .CI(1'h0),
    .CO(_017_[1]),
    .S(next_wr_addr[0])
  );
  CC_ADDF _092_ (
    .A(1'h0),
    .B(wr_addr[1]),
    .CI(_017_[1]),
    .CO(_017_[2]),
    .S(next_wr_addr[1])
  );
  CC_ADDF _093_ (
    .A(1'h0),
    .B(wr_addr[2]),
    .CI(_017_[2]),
    .CO(_017_[3]),
    .S(next_wr_addr[2])
  );
  CC_ADDF _094_ (
    .A(1'h0),
    .B(wgray[3]),
    .CI(_017_[3]),
    .CO(_018_[3]),
    .S(next_wr_addr[3])
  );
  CC_ADDF _095_ (
    .A(1'h1),
    .B(rd_addr[0]),
    .CI(1'h0),
    .CO(_019_[1]),
    .S(next_rd_addr[0])
  );
  CC_ADDF _096_ (
    .A(1'h0),
    .B(rd_addr[1]),
    .CI(_019_[1]),
    .CO(_019_[2]),
    .S(next_rd_addr[1])
  );
  CC_ADDF _097_ (
    .A(1'h0),
    .B(rd_addr[2]),
    .CI(_019_[2]),
    .CO(_019_[3]),
    .S(next_rd_addr[2])
  );
  CC_ADDF _098_ (
    .A(1'h0),
    .B(rd_addr[3]),
    .CI(_019_[3]),
    .CO(_020_[3]),
    .S(next_rd_addr[3])
  );
  CC_BUFG _099_ (
    .I(_021_),
    .O(_023_)
  );
  CC_BUFG _100_ (
    .I(_022_),
    .O(wclk)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _101_ (
    .CLK(_023_),
    .D(_001_[0]),
    .EN(lcl_read),
    .Q(_027_[0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _102_ (
    .CLK(_023_),
    .D(_001_[1]),
    .EN(lcl_read),
    .Q(_027_[1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _103_ (
    .CLK(_023_),
    .D(_001_[2]),
    .EN(lcl_read),
    .Q(_027_[2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _104_ (
    .CLK(_023_),
    .D(_001_[3]),
    .EN(lcl_read),
    .Q(_027_[3]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _105_ (
    .CLK(_023_),
    .D(_001_[4]),
    .EN(lcl_read),
    .Q(_027_[4]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _106_ (
    .CLK(_023_),
    .D(_001_[5]),
    .EN(lcl_read),
    .Q(_027_[5]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _107_ (
    .CLK(_023_),
    .D(_001_[6]),
    .EN(lcl_read),
    .Q(_027_[6]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _108_ (
    .CLK(_023_),
    .D(_001_[7]),
    .EN(lcl_read),
    .Q(_027_[7]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _109_ (
    .CLK(_023_),
    .D(_001_[8]),
    .EN(lcl_read),
    .Q(_027_[8]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _110_ (
    .CLK(_023_),
    .D(_001_[9]),
    .EN(lcl_read),
    .Q(_027_[9]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _111_ (
    .CLK(_023_),
    .D(_001_[10]),
    .EN(lcl_read),
    .Q(_027_[10]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _112_ (
    .CLK(_023_),
    .D(_001_[11]),
    .EN(lcl_read),
    .Q(_027_[11]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _113_ (
    .CLK(_023_),
    .D(_001_[12]),
    .EN(lcl_read),
    .Q(_027_[12]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _114_ (
    .CLK(_023_),
    .D(_001_[13]),
    .EN(lcl_read),
    .Q(_027_[13]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _115_ (
    .CLK(_023_),
    .D(_001_[14]),
    .EN(lcl_read),
    .Q(_027_[14]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _116_ (
    .CLK(_023_),
    .D(_001_[15]),
    .EN(lcl_read),
    .Q(_027_[15]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _117_ (
    .CLK(wclk),
    .D(_025_[0]),
    .EN(_013_),
    .Q(\mem[4] [0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _118_ (
    .CLK(wclk),
    .D(_025_[1]),
    .EN(_013_),
    .Q(\mem[4] [1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _119_ (
    .CLK(wclk),
    .D(_025_[2]),
    .EN(_013_),
    .Q(\mem[4] [2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _120_ (
    .CLK(wclk),
    .D(_025_[3]),
    .EN(_013_),
    .Q(\mem[4] [3]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _121_ (
    .CLK(wclk),
    .D(_025_[4]),
    .EN(_013_),
    .Q(\mem[4] [4]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _122_ (
    .CLK(wclk),
    .D(_025_[5]),
    .EN(_013_),
    .Q(\mem[4] [5]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _123_ (
    .CLK(wclk),
    .D(_025_[6]),
    .EN(_013_),
    .Q(\mem[4] [6]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _124_ (
    .CLK(wclk),
    .D(_025_[7]),
    .EN(_013_),
    .Q(\mem[4] [7]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _125_ (
    .CLK(wclk),
    .D(_025_[8]),
    .EN(_013_),
    .Q(\mem[4] [8]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _126_ (
    .CLK(wclk),
    .D(_025_[9]),
    .EN(_013_),
    .Q(\mem[4] [9]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _127_ (
    .CLK(wclk),
    .D(_025_[10]),
    .EN(_013_),
    .Q(\mem[4] [10]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _128_ (
    .CLK(wclk),
    .D(_025_[11]),
    .EN(_013_),
    .Q(\mem[4] [11]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _129_ (
    .CLK(wclk),
    .D(_025_[12]),
    .EN(_013_),
    .Q(\mem[4] [12]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _130_ (
    .CLK(wclk),
    .D(_025_[13]),
    .EN(_013_),
    .Q(\mem[4] [13]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _131_ (
    .CLK(wclk),
    .D(_025_[14]),
    .EN(_013_),
    .Q(\mem[4] [14]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _132_ (
    .CLK(wclk),
    .D(_025_[15]),
    .EN(_013_),
    .Q(\mem[4] [15]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _133_ (
    .CLK(wclk),
    .D(_025_[0]),
    .EN(_011_),
    .Q(\mem[2] [0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _134_ (
    .CLK(wclk),
    .D(_025_[1]),
    .EN(_011_),
    .Q(\mem[2] [1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _135_ (
    .CLK(wclk),
    .D(_025_[2]),
    .EN(_011_),
    .Q(\mem[2] [2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _136_ (
    .CLK(wclk),
    .D(_025_[3]),
    .EN(_011_),
    .Q(\mem[2] [3]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _137_ (
    .CLK(wclk),
    .D(_025_[4]),
    .EN(_011_),
    .Q(\mem[2] [4]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _138_ (
    .CLK(wclk),
    .D(_025_[5]),
    .EN(_011_),
    .Q(\mem[2] [5]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _139_ (
    .CLK(wclk),
    .D(_025_[6]),
    .EN(_011_),
    .Q(\mem[2] [6]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _140_ (
    .CLK(wclk),
    .D(_025_[7]),
    .EN(_011_),
    .Q(\mem[2] [7]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _141_ (
    .CLK(wclk),
    .D(_025_[8]),
    .EN(_011_),
    .Q(\mem[2] [8]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _142_ (
    .CLK(wclk),
    .D(_025_[9]),
    .EN(_011_),
    .Q(\mem[2] [9]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _143_ (
    .CLK(wclk),
    .D(_025_[10]),
    .EN(_011_),
    .Q(\mem[2] [10]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _144_ (
    .CLK(wclk),
    .D(_025_[11]),
    .EN(_011_),
    .Q(\mem[2] [11]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _145_ (
    .CLK(wclk),
    .D(_025_[12]),
    .EN(_011_),
    .Q(\mem[2] [12]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _146_ (
    .CLK(wclk),
    .D(_025_[13]),
    .EN(_011_),
    .Q(\mem[2] [13]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _147_ (
    .CLK(wclk),
    .D(_025_[14]),
    .EN(_011_),
    .Q(\mem[2] [14]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _148_ (
    .CLK(wclk),
    .D(_025_[15]),
    .EN(_011_),
    .Q(\mem[2] [15]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _149_ (
    .CLK(wclk),
    .D(_025_[0]),
    .EN(_012_),
    .Q(\mem[3] [0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _150_ (
    .CLK(wclk),
    .D(_025_[1]),
    .EN(_012_),
    .Q(\mem[3] [1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _151_ (
    .CLK(wclk),
    .D(_025_[2]),
    .EN(_012_),
    .Q(\mem[3] [2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _152_ (
    .CLK(wclk),
    .D(_025_[3]),
    .EN(_012_),
    .Q(\mem[3] [3]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _153_ (
    .CLK(wclk),
    .D(_025_[4]),
    .EN(_012_),
    .Q(\mem[3] [4]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _154_ (
    .CLK(wclk),
    .D(_025_[5]),
    .EN(_012_),
    .Q(\mem[3] [5]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _155_ (
    .CLK(wclk),
    .D(_025_[6]),
    .EN(_012_),
    .Q(\mem[3] [6]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _156_ (
    .CLK(wclk),
    .D(_025_[7]),
    .EN(_012_),
    .Q(\mem[3] [7]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _157_ (
    .CLK(wclk),
    .D(_025_[8]),
    .EN(_012_),
    .Q(\mem[3] [8]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _158_ (
    .CLK(wclk),
    .D(_025_[9]),
    .EN(_012_),
    .Q(\mem[3] [9]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _159_ (
    .CLK(wclk),
    .D(_025_[10]),
    .EN(_012_),
    .Q(\mem[3] [10]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _160_ (
    .CLK(wclk),
    .D(_025_[11]),
    .EN(_012_),
    .Q(\mem[3] [11]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _161_ (
    .CLK(wclk),
    .D(_025_[12]),
    .EN(_012_),
    .Q(\mem[3] [12]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _162_ (
    .CLK(wclk),
    .D(_025_[13]),
    .EN(_012_),
    .Q(\mem[3] [13]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _163_ (
    .CLK(wclk),
    .D(_025_[14]),
    .EN(_012_),
    .Q(\mem[3] [14]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _164_ (
    .CLK(wclk),
    .D(_025_[15]),
    .EN(_012_),
    .Q(\mem[3] [15]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _165_ (
    .CLK(wclk),
    .D(_025_[0]),
    .EN(_015_),
    .Q(\mem[6] [0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _166_ (
    .CLK(wclk),
    .D(_025_[1]),
    .EN(_015_),
    .Q(\mem[6] [1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _167_ (
    .CLK(wclk),
    .D(_025_[2]),
    .EN(_015_),
    .Q(\mem[6] [2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _168_ (
    .CLK(wclk),
    .D(_025_[3]),
    .EN(_015_),
    .Q(\mem[6] [3]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _169_ (
    .CLK(wclk),
    .D(_025_[4]),
    .EN(_015_),
    .Q(\mem[6] [4]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _170_ (
    .CLK(wclk),
    .D(_025_[5]),
    .EN(_015_),
    .Q(\mem[6] [5]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _171_ (
    .CLK(wclk),
    .D(_025_[6]),
    .EN(_015_),
    .Q(\mem[6] [6]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _172_ (
    .CLK(wclk),
    .D(_025_[7]),
    .EN(_015_),
    .Q(\mem[6] [7]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _173_ (
    .CLK(wclk),
    .D(_025_[8]),
    .EN(_015_),
    .Q(\mem[6] [8]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _174_ (
    .CLK(wclk),
    .D(_025_[9]),
    .EN(_015_),
    .Q(\mem[6] [9]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _175_ (
    .CLK(wclk),
    .D(_025_[10]),
    .EN(_015_),
    .Q(\mem[6] [10]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _176_ (
    .CLK(wclk),
    .D(_025_[11]),
    .EN(_015_),
    .Q(\mem[6] [11]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _177_ (
    .CLK(wclk),
    .D(_025_[12]),
    .EN(_015_),
    .Q(\mem[6] [12]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _178_ (
    .CLK(wclk),
    .D(_025_[13]),
    .EN(_015_),
    .Q(\mem[6] [13]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _179_ (
    .CLK(wclk),
    .D(_025_[14]),
    .EN(_015_),
    .Q(\mem[6] [14]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _180_ (
    .CLK(wclk),
    .D(_025_[15]),
    .EN(_015_),
    .Q(\mem[6] [15]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _181_ (
    .CLK(_023_),
    .D(wgray_cross[0]),
    .EN(1'h1),
    .Q(rd_wgray[0]),
    .SR(_024_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _182_ (
    .CLK(_023_),
    .D(wgray_cross[1]),
    .EN(1'h1),
    .Q(rd_wgray[1]),
    .SR(_024_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _183_ (
    .CLK(_023_),
    .D(wgray_cross[2]),
    .EN(1'h1),
    .Q(rd_wgray[2]),
    .SR(_024_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _184_ (
    .CLK(_023_),
    .D(wgray_cross[3]),
    .EN(1'h1),
    .Q(rd_wgray[3]),
    .SR(_024_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _185_ (
    .CLK(wclk),
    .D(rgray[0]),
    .EN(1'h1),
    .Q(rgray_cross[0]),
    .SR(_026_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _186_ (
    .CLK(wclk),
    .D(rgray[1]),
    .EN(1'h1),
    .Q(rgray_cross[1]),
    .SR(_026_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _187_ (
    .CLK(wclk),
    .D(rgray[2]),
    .EN(1'h1),
    .Q(rgray_cross[2]),
    .SR(_026_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _188_ (
    .CLK(wclk),
    .D(rd_addr[3]),
    .EN(1'h1),
    .Q(rgray_cross[3]),
    .SR(_026_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _189_ (
    .CLK(wclk),
    .D(rgray_cross[0]),
    .EN(1'h1),
    .Q(wr_rgray[0]),
    .SR(_026_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _190_ (
    .CLK(wclk),
    .D(rgray_cross[1]),
    .EN(1'h1),
    .Q(wr_rgray[1]),
    .SR(_026_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _191_ (
    .CLK(wclk),
    .D(rgray_cross[2]),
    .EN(1'h1),
    .Q(wr_rgray[2]),
    .SR(_026_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _192_ (
    .CLK(wclk),
    .D(rgray_cross[3]),
    .EN(1'h1),
    .Q(wr_rgray[3]),
    .SR(_026_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _193_ (
    .CLK(_023_),
    .D(wgray[0]),
    .EN(1'h1),
    .Q(wgray_cross[0]),
    .SR(_024_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _194_ (
    .CLK(_023_),
    .D(wgray[1]),
    .EN(1'h1),
    .Q(wgray_cross[1]),
    .SR(_024_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _195_ (
    .CLK(_023_),
    .D(wgray[2]),
    .EN(1'h1),
    .Q(wgray_cross[2]),
    .SR(_024_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _196_ (
    .CLK(_023_),
    .D(wgray[3]),
    .EN(1'h1),
    .Q(wgray_cross[3]),
    .SR(_024_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _197_ (
    .CLK(wclk),
    .D(_025_[0]),
    .EN(_009_),
    .Q(\mem[0] [0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _198_ (
    .CLK(wclk),
    .D(_025_[1]),
    .EN(_009_),
    .Q(\mem[0] [1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _199_ (
    .CLK(wclk),
    .D(_025_[2]),
    .EN(_009_),
    .Q(\mem[0] [2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _200_ (
    .CLK(wclk),
    .D(_025_[3]),
    .EN(_009_),
    .Q(\mem[0] [3]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _201_ (
    .CLK(wclk),
    .D(_025_[4]),
    .EN(_009_),
    .Q(\mem[0] [4]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _202_ (
    .CLK(wclk),
    .D(_025_[5]),
    .EN(_009_),
    .Q(\mem[0] [5]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _203_ (
    .CLK(wclk),
    .D(_025_[6]),
    .EN(_009_),
    .Q(\mem[0] [6]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _204_ (
    .CLK(wclk),
    .D(_025_[7]),
    .EN(_009_),
    .Q(\mem[0] [7]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _205_ (
    .CLK(wclk),
    .D(_025_[8]),
    .EN(_009_),
    .Q(\mem[0] [8]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _206_ (
    .CLK(wclk),
    .D(_025_[9]),
    .EN(_009_),
    .Q(\mem[0] [9]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _207_ (
    .CLK(wclk),
    .D(_025_[10]),
    .EN(_009_),
    .Q(\mem[0] [10]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _208_ (
    .CLK(wclk),
    .D(_025_[11]),
    .EN(_009_),
    .Q(\mem[0] [11]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _209_ (
    .CLK(wclk),
    .D(_025_[12]),
    .EN(_009_),
    .Q(\mem[0] [12]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _210_ (
    .CLK(wclk),
    .D(_025_[13]),
    .EN(_009_),
    .Q(\mem[0] [13]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _211_ (
    .CLK(wclk),
    .D(_025_[14]),
    .EN(_009_),
    .Q(\mem[0] [14]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _212_ (
    .CLK(wclk),
    .D(_025_[15]),
    .EN(_009_),
    .Q(\mem[0] [15]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _213_ (
    .CLK(wclk),
    .D(_025_[0]),
    .EN(_014_),
    .Q(\mem[5] [0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _214_ (
    .CLK(wclk),
    .D(_025_[1]),
    .EN(_014_),
    .Q(\mem[5] [1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _215_ (
    .CLK(wclk),
    .D(_025_[2]),
    .EN(_014_),
    .Q(\mem[5] [2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _216_ (
    .CLK(wclk),
    .D(_025_[3]),
    .EN(_014_),
    .Q(\mem[5] [3]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _217_ (
    .CLK(wclk),
    .D(_025_[4]),
    .EN(_014_),
    .Q(\mem[5] [4]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _218_ (
    .CLK(wclk),
    .D(_025_[5]),
    .EN(_014_),
    .Q(\mem[5] [5]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _219_ (
    .CLK(wclk),
    .D(_025_[6]),
    .EN(_014_),
    .Q(\mem[5] [6]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _220_ (
    .CLK(wclk),
    .D(_025_[7]),
    .EN(_014_),
    .Q(\mem[5] [7]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _221_ (
    .CLK(wclk),
    .D(_025_[8]),
    .EN(_014_),
    .Q(\mem[5] [8]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _222_ (
    .CLK(wclk),
    .D(_025_[9]),
    .EN(_014_),
    .Q(\mem[5] [9]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _223_ (
    .CLK(wclk),
    .D(_025_[10]),
    .EN(_014_),
    .Q(\mem[5] [10]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _224_ (
    .CLK(wclk),
    .D(_025_[11]),
    .EN(_014_),
    .Q(\mem[5] [11]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _225_ (
    .CLK(wclk),
    .D(_025_[12]),
    .EN(_014_),
    .Q(\mem[5] [12]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _226_ (
    .CLK(wclk),
    .D(_025_[13]),
    .EN(_014_),
    .Q(\mem[5] [13]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _227_ (
    .CLK(wclk),
    .D(_025_[14]),
    .EN(_014_),
    .Q(\mem[5] [14]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _228_ (
    .CLK(wclk),
    .D(_025_[15]),
    .EN(_014_),
    .Q(\mem[5] [15]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _229_ (
    .CLK(wclk),
    .D(_002_),
    .EN(_000_[15]),
    .Q(wgray[0]),
    .SR(_026_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _230_ (
    .CLK(wclk),
    .D(_003_),
    .EN(_000_[15]),
    .Q(wgray[1]),
    .SR(_026_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _231_ (
    .CLK(wclk),
    .D(_004_),
    .EN(_000_[15]),
    .Q(wgray[2]),
    .SR(_026_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _232_ (
    .CLK(wclk),
    .D(_025_[0]),
    .EN(_010_),
    .Q(\mem[1] [0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _233_ (
    .CLK(wclk),
    .D(_025_[1]),
    .EN(_010_),
    .Q(\mem[1] [1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _234_ (
    .CLK(wclk),
    .D(_025_[2]),
    .EN(_010_),
    .Q(\mem[1] [2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _235_ (
    .CLK(wclk),
    .D(_025_[3]),
    .EN(_010_),
    .Q(\mem[1] [3]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _236_ (
    .CLK(wclk),
    .D(_025_[4]),
    .EN(_010_),
    .Q(\mem[1] [4]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _237_ (
    .CLK(wclk),
    .D(_025_[5]),
    .EN(_010_),
    .Q(\mem[1] [5]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _238_ (
    .CLK(wclk),
    .D(_025_[6]),
    .EN(_010_),
    .Q(\mem[1] [6]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _239_ (
    .CLK(wclk),
    .D(_025_[7]),
    .EN(_010_),
    .Q(\mem[1] [7]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _240_ (
    .CLK(wclk),
    .D(_025_[8]),
    .EN(_010_),
    .Q(\mem[1] [8]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _241_ (
    .CLK(wclk),
    .D(_025_[9]),
    .EN(_010_),
    .Q(\mem[1] [9]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _242_ (
    .CLK(wclk),
    .D(_025_[10]),
    .EN(_010_),
    .Q(\mem[1] [10]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _243_ (
    .CLK(wclk),
    .D(_025_[11]),
    .EN(_010_),
    .Q(\mem[1] [11]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _244_ (
    .CLK(wclk),
    .D(_025_[12]),
    .EN(_010_),
    .Q(\mem[1] [12]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _245_ (
    .CLK(wclk),
    .D(_025_[13]),
    .EN(_010_),
    .Q(\mem[1] [13]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _246_ (
    .CLK(wclk),
    .D(_025_[14]),
    .EN(_010_),
    .Q(\mem[1] [14]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _247_ (
    .CLK(wclk),
    .D(_025_[15]),
    .EN(_010_),
    .Q(\mem[1] [15]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _248_ (
    .CLK(wclk),
    .D(_025_[0]),
    .EN(_016_),
    .Q(\mem[7] [0]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _249_ (
    .CLK(wclk),
    .D(_025_[1]),
    .EN(_016_),
    .Q(\mem[7] [1]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _250_ (
    .CLK(wclk),
    .D(_025_[2]),
    .EN(_016_),
    .Q(\mem[7] [2]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _251_ (
    .CLK(wclk),
    .D(_025_[3]),
    .EN(_016_),
    .Q(\mem[7] [3]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _252_ (
    .CLK(wclk),
    .D(_025_[4]),
    .EN(_016_),
    .Q(\mem[7] [4]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _253_ (
    .CLK(wclk),
    .D(_025_[5]),
    .EN(_016_),
    .Q(\mem[7] [5]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _254_ (
    .CLK(wclk),
    .D(_025_[6]),
    .EN(_016_),
    .Q(\mem[7] [6]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _255_ (
    .CLK(wclk),
    .D(_025_[7]),
    .EN(_016_),
    .Q(\mem[7] [7]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _256_ (
    .CLK(wclk),
    .D(_025_[8]),
    .EN(_016_),
    .Q(\mem[7] [8]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _257_ (
    .CLK(wclk),
    .D(_025_[9]),
    .EN(_016_),
    .Q(\mem[7] [9]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _258_ (
    .CLK(wclk),
    .D(_025_[10]),
    .EN(_016_),
    .Q(\mem[7] [10]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _259_ (
    .CLK(wclk),
    .D(_025_[11]),
    .EN(_016_),
    .Q(\mem[7] [11]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _260_ (
    .CLK(wclk),
    .D(_025_[12]),
    .EN(_016_),
    .Q(\mem[7] [12]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _261_ (
    .CLK(wclk),
    .D(_025_[13]),
    .EN(_016_),
    .Q(\mem[7] [13]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _262_ (
    .CLK(wclk),
    .D(_025_[14]),
    .EN(_016_),
    .Q(\mem[7] [14]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h0),
    .SR_VAL(1'h0)
  ) _263_ (
    .CLK(wclk),
    .D(_025_[15]),
    .EN(_016_),
    .Q(\mem[7] [15]),
    .SR(1'h0)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h1)
  ) _264_ (
    .CLK(_023_),
    .D(lcl_rd_empty),
    .EN(lcl_read),
    .Q(_043_[0]),
    .SR(_024_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _265_ (
    .CLK(_023_),
    .D(next_rd_addr[0]),
    .EN(_008_),
    .Q(rd_addr[0]),
    .SR(_024_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _266_ (
    .CLK(_023_),
    .D(next_rd_addr[1]),
    .EN(_008_),
    .Q(rd_addr[1]),
    .SR(_024_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _267_ (
    .CLK(_023_),
    .D(next_rd_addr[2]),
    .EN(_008_),
    .Q(rd_addr[2]),
    .SR(_024_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _268_ (
    .CLK(_023_),
    .D(_005_),
    .EN(_008_),
    .Q(rgray[0]),
    .SR(_024_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _269_ (
    .CLK(_023_),
    .D(_006_),
    .EN(_008_),
    .Q(rgray[1]),
    .SR(_024_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _270_ (
    .CLK(_023_),
    .D(_007_),
    .EN(_008_),
    .Q(rgray[2]),
    .SR(_024_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _271_ (
    .CLK(_023_),
    .D(next_rd_addr[3]),
    .EN(_008_),
    .Q(rd_addr[3]),
    .SR(_024_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _272_ (
    .CLK(wclk),
    .D(next_wr_addr[0]),
    .EN(_000_[15]),
    .Q(wr_addr[0]),
    .SR(_026_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _273_ (
    .CLK(wclk),
    .D(next_wr_addr[1]),
    .EN(_000_[15]),
    .Q(wr_addr[1]),
    .SR(_026_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _274_ (
    .CLK(wclk),
    .D(next_wr_addr[2]),
    .EN(_000_[15]),
    .Q(wr_addr[2]),
    .SR(_026_)
  );
  CC_DFF #(
    .CLK_INV(1'h0),
    .EN_INV(1'h0),
    .INIT(1'hx),
    .SR_INV(1'h1),
    .SR_VAL(1'h0)
  ) _275_ (
    .CLK(wclk),
    .D(next_wr_addr[3]),
    .EN(_000_[15]),
    .Q(wgray[3]),
    .SR(_026_)
  );
  CC_MX4 _276_ (
    .D0(\mem[0] [0]),
    .D1(\mem[1] [0]),
    .D2(\mem[2] [0]),
    .D3(\mem[3] [0]),
    .S0(rd_addr[0]),
    .S1(rd_addr[1]),
    .Y(_033_[1])
  );
  CC_MX4 _277_ (
    .D0(\mem[4] [0]),
    .D1(\mem[5] [0]),
    .D2(\mem[6] [0]),
    .D3(\mem[7] [0]),
    .S0(rd_addr[0]),
    .S1(rd_addr[1]),
    .Y(_033_[0])
  );
  CC_MX4 _278_ (
    .D0(\mem[0] [1]),
    .D1(\mem[1] [1]),
    .D2(\mem[2] [1]),
    .D3(\mem[3] [1]),
    .S0(rd_addr[0]),
    .S1(rd_addr[1]),
    .Y(_037_[0])
  );
  CC_MX4 _279_ (
    .D0(\mem[4] [1]),
    .D1(\mem[5] [1]),
    .D2(\mem[6] [1]),
    .D3(\mem[7] [1]),
    .S0(rd_addr[0]),
    .S1(rd_addr[1]),
    .Y(_037_[1])
  );
  CC_MX4 _280_ (
    .D0(\mem[0] [2]),
    .D1(\mem[1] [2]),
    .D2(\mem[2] [2]),
    .D3(\mem[3] [2]),
    .S0(rd_addr[0]),
    .S1(rd_addr[1]),
    .Y(_039_[0])
  );
  CC_MX4 _281_ (
    .D0(\mem[4] [2]),
    .D1(\mem[5] [2]),
    .D2(\mem[6] [2]),
    .D3(\mem[7] [2]),
    .S0(rd_addr[0]),
    .S1(rd_addr[1]),
    .Y(_039_[1])
  );
  CC_MX4 _282_ (
    .D0(\mem[0] [3]),
    .D1(\mem[1] [3]),
    .D2(\mem[2] [3]),
    .D3(\mem[3] [3]),
    .S0(rd_addr[0]),
    .S1(rd_addr[1]),
    .Y(_040_[0])
  );
  CC_MX4 _283_ (
    .D0(\mem[4] [3]),
    .D1(\mem[5] [3]),
    .D2(\mem[6] [3]),
    .D3(\mem[7] [3]),
    .S0(rd_addr[0]),
    .S1(rd_addr[1]),
    .Y(_040_[1])
  );
  CC_MX4 _284_ (
    .D0(\mem[0] [4]),
    .D1(\mem[1] [4]),
    .D2(\mem[2] [4]),
    .D3(\mem[3] [4]),
    .S0(rd_addr[0]),
    .S1(rd_addr[1]),
    .Y(_028_[0])
  );
  CC_MX4 _285_ (
    .D0(\mem[4] [4]),
    .D1(\mem[5] [4]),
    .D2(\mem[6] [4]),
    .D3(\mem[7] [4]),
    .S0(rd_addr[0]),
    .S1(rd_addr[1]),
    .Y(_028_[1])
  );
  CC_MX4 _286_ (
    .D0(\mem[0] [5]),
    .D1(\mem[1] [5]),
    .D2(\mem[2] [5]),
    .D3(\mem[3] [5]),
    .S0(rd_addr[0]),
    .S1(rd_addr[1]),
    .Y(_034_[0])
  );
  CC_MX4 _287_ (
    .D0(\mem[4] [5]),
    .D1(\mem[5] [5]),
    .D2(\mem[6] [5]),
    .D3(\mem[7] [5]),
    .S0(rd_addr[0]),
    .S1(rd_addr[1]),
    .Y(_034_[1])
  );
  CC_MX4 _288_ (
    .D0(\mem[0] [6]),
    .D1(\mem[1] [6]),
    .D2(\mem[2] [6]),
    .D3(\mem[3] [6]),
    .S0(rd_addr[0]),
    .S1(rd_addr[1]),
    .Y(_035_[0])
  );
  CC_MX4 _289_ (
    .D0(\mem[4] [6]),
    .D1(\mem[5] [6]),
    .D2(\mem[6] [6]),
    .D3(\mem[7] [6]),
    .S0(rd_addr[0]),
    .S1(rd_addr[1]),
    .Y(_035_[1])
  );
  CC_MX4 _290_ (
    .D0(\mem[0] [7]),
    .D1(\mem[1] [7]),
    .D2(\mem[2] [7]),
    .D3(\mem[3] [7]),
    .S0(rd_addr[0]),
    .S1(rd_addr[1]),
    .Y(_041_[0])
  );
  CC_MX4 _291_ (
    .D0(\mem[4] [7]),
    .D1(\mem[5] [7]),
    .D2(\mem[6] [7]),
    .D3(\mem[7] [7]),
    .S0(rd_addr[0]),
    .S1(rd_addr[1]),
    .Y(_041_[1])
  );
  CC_MX4 _292_ (
    .D0(\mem[0] [8]),
    .D1(\mem[1] [8]),
    .D2(\mem[2] [8]),
    .D3(\mem[3] [8]),
    .S0(rd_addr[0]),
    .S1(rd_addr[1]),
    .Y(_042_[0])
  );
  CC_MX4 _293_ (
    .D0(\mem[4] [8]),
    .D1(\mem[5] [8]),
    .D2(\mem[6] [8]),
    .D3(\mem[7] [8]),
    .S0(rd_addr[0]),
    .S1(rd_addr[1]),
    .Y(_042_[1])
  );
  CC_MX4 _294_ (
    .D0(\mem[0] [9]),
    .D1(\mem[1] [9]),
    .D2(\mem[2] [9]),
    .D3(\mem[3] [9]),
    .S0(rd_addr[0]),
    .S1(rd_addr[1]),
    .Y(_044_[0])
  );
  CC_MX4 _295_ (
    .D0(\mem[4] [9]),
    .D1(\mem[5] [9]),
    .D2(\mem[6] [9]),
    .D3(\mem[7] [9]),
    .S0(rd_addr[0]),
    .S1(rd_addr[1]),
    .Y(_044_[1])
  );
  CC_MX4 _296_ (
    .D0(\mem[0] [10]),
    .D1(\mem[1] [10]),
    .D2(\mem[2] [10]),
    .D3(\mem[3] [10]),
    .S0(rd_addr[0]),
    .S1(rd_addr[1]),
    .Y(_029_[0])
  );
  CC_MX4 _297_ (
    .D0(\mem[4] [10]),
    .D1(\mem[5] [10]),
    .D2(\mem[6] [10]),
    .D3(\mem[7] [10]),
    .S0(rd_addr[0]),
    .S1(rd_addr[1]),
    .Y(_029_[1])
  );
  CC_MX4 _298_ (
    .D0(\mem[0] [11]),
    .D1(\mem[1] [11]),
    .D2(\mem[2] [11]),
    .D3(\mem[3] [11]),
    .S0(rd_addr[0]),
    .S1(rd_addr[1]),
    .Y(_036_[0])
  );
  CC_MX4 _299_ (
    .D0(\mem[4] [11]),
    .D1(\mem[5] [11]),
    .D2(\mem[6] [11]),
    .D3(\mem[7] [11]),
    .S0(rd_addr[0]),
    .S1(rd_addr[1]),
    .Y(_036_[1])
  );
  CC_MX4 _300_ (
    .D0(\mem[0] [12]),
    .D1(\mem[1] [12]),
    .D2(\mem[2] [12]),
    .D3(\mem[3] [12]),
    .S0(rd_addr[0]),
    .S1(rd_addr[1]),
    .Y(_038_[0])
  );
  CC_MX4 _301_ (
    .D0(\mem[4] [12]),
    .D1(\mem[5] [12]),
    .D2(\mem[6] [12]),
    .D3(\mem[7] [12]),
    .S0(rd_addr[0]),
    .S1(rd_addr[1]),
    .Y(_038_[1])
  );
  CC_MX4 _302_ (
    .D0(\mem[0] [13]),
    .D1(\mem[1] [13]),
    .D2(\mem[2] [13]),
    .D3(\mem[3] [13]),
    .S0(rd_addr[0]),
    .S1(rd_addr[1]),
    .Y(_045_[0])
  );
  CC_MX4 _303_ (
    .D0(\mem[4] [13]),
    .D1(\mem[5] [13]),
    .D2(\mem[6] [13]),
    .D3(\mem[7] [13]),
    .S0(rd_addr[0]),
    .S1(rd_addr[1]),
    .Y(_045_[1])
  );
  CC_MX4 _304_ (
    .D0(\mem[0] [14]),
    .D1(\mem[1] [14]),
    .D2(\mem[2] [14]),
    .D3(\mem[3] [14]),
    .S0(rd_addr[0]),
    .S1(rd_addr[1]),
    .Y(_047_[0])
  );
  CC_MX4 _305_ (
    .D0(\mem[4] [14]),
    .D1(\mem[5] [14]),
    .D2(\mem[6] [14]),
    .D3(\mem[7] [14]),
    .S0(rd_addr[0]),
    .S1(rd_addr[1]),
    .Y(_047_[1])
  );
  CC_MX4 _306_ (
    .D0(\mem[0] [15]),
    .D1(\mem[1] [15]),
    .D2(\mem[2] [15]),
    .D3(\mem[3] [15]),
    .S0(rd_addr[0]),
    .S1(rd_addr[1]),
    .Y(_048_[0])
  );
  CC_MX4 _307_ (
    .D0(\mem[4] [15]),
    .D1(\mem[5] [15]),
    .D2(\mem[6] [15]),
    .D3(\mem[7] [15]),
    .S0(rd_addr[0]),
    .S1(rd_addr[1]),
    .Y(_048_[1])
  );
  CC_IBUF _308_ (
    .I(i_rclk),
    .Y(_021_)
  );
  CC_IBUF _309_ (
    .I(i_rd),
    .Y(_043_[1])
  );
  CC_IBUF _310_ (
    .I(i_rd_reset_n),
    .Y(_024_)
  );
  CC_IBUF _311_ (
    .I(i_wclk),
    .Y(_022_)
  );
  CC_IBUF _312_ (
    .I(i_wr),
    .Y(_031_[1])
  );
  CC_IBUF _313_ (
    .I(i_wr_data[0]),
    .Y(_025_[0])
  );
  CC_IBUF _314_ (
    .I(i_wr_data[1]),
    .Y(_025_[1])
  );
  CC_IBUF _315_ (
    .I(i_wr_data[10]),
    .Y(_025_[10])
  );
  CC_IBUF _316_ (
    .I(i_wr_data[11]),
    .Y(_025_[11])
  );
  CC_IBUF _317_ (
    .I(i_wr_data[12]),
    .Y(_025_[12])
  );
  CC_IBUF _318_ (
    .I(i_wr_data[13]),
    .Y(_025_[13])
  );
  CC_IBUF _319_ (
    .I(i_wr_data[14]),
    .Y(_025_[14])
  );
  CC_IBUF _320_ (
    .I(i_wr_data[15]),
    .Y(_025_[15])
  );
  CC_IBUF _321_ (
    .I(i_wr_data[2]),
    .Y(_025_[2])
  );
  CC_IBUF _322_ (
    .I(i_wr_data[3]),
    .Y(_025_[3])
  );
  CC_IBUF _323_ (
    .I(i_wr_data[4]),
    .Y(_025_[4])
  );
  CC_IBUF _324_ (
    .I(i_wr_data[5]),
    .Y(_025_[5])
  );
  CC_IBUF _325_ (
    .I(i_wr_data[6]),
    .Y(_025_[6])
  );
  CC_IBUF _326_ (
    .I(i_wr_data[7]),
    .Y(_025_[7])
  );
  CC_IBUF _327_ (
    .I(i_wr_data[8]),
    .Y(_025_[8])
  );
  CC_IBUF _328_ (
    .I(i_wr_data[9]),
    .Y(_025_[9])
  );
  CC_IBUF _329_ (
    .I(i_wr_reset_n),
    .Y(_026_)
  );
  CC_OBUF _330_ (
    .A(_027_[0]),
    .O(o_rd_data[0])
  );
  CC_OBUF _331_ (
    .A(_027_[1]),
    .O(o_rd_data[1])
  );
  CC_OBUF _332_ (
    .A(_027_[10]),
    .O(o_rd_data[10])
  );
  CC_OBUF _333_ (
    .A(_027_[11]),
    .O(o_rd_data[11])
  );
  CC_OBUF _334_ (
    .A(_027_[12]),
    .O(o_rd_data[12])
  );
  CC_OBUF _335_ (
    .A(_027_[13]),
    .O(o_rd_data[13])
  );
  CC_OBUF _336_ (
    .A(_027_[14]),
    .O(o_rd_data[14])
  );
  CC_OBUF _337_ (
    .A(_027_[15]),
    .O(o_rd_data[15])
  );
  CC_OBUF _338_ (
    .A(_027_[2]),
    .O(o_rd_data[2])
  );
  CC_OBUF _339_ (
    .A(_027_[3]),
    .O(o_rd_data[3])
  );
  CC_OBUF _340_ (
    .A(_027_[4]),
    .O(o_rd_data[4])
  );
  CC_OBUF _341_ (
    .A(_027_[5]),
    .O(o_rd_data[5])
  );
  CC_OBUF _342_ (
    .A(_027_[6]),
    .O(o_rd_data[6])
  );
  CC_OBUF _343_ (
    .A(_027_[7]),
    .O(o_rd_data[7])
  );
  CC_OBUF _344_ (
    .A(_027_[8]),
    .O(o_rd_data[8])
  );
  CC_OBUF _345_ (
    .A(_027_[9]),
    .O(o_rd_data[9])
  );
  CC_OBUF _346_ (
    .A(_043_[0]),
    .O(o_rd_empty)
  );
  CC_OBUF _347_ (
    .A(_031_[0]),
    .O(o_wr_full)
  );
  assign _000_[14:0] = { _000_[15], _000_[15], _000_[15], _000_[15], _000_[15], _000_[15], _000_[15], _000_[15], _000_[15], _000_[15], _000_[15], _000_[15], _000_[15], _000_[15], _000_[15] };
  assign _017_[0] = 1'h0;
  assign _018_[2:0] = _017_[3:1];
  assign _019_[0] = 1'h0;
  assign _020_[2:0] = _019_[3:1];
  assign _028_[2] = rd_addr[2];
  assign _029_[2] = rd_addr[2];
  assign _032_[1:0] = wr_addr[2:1];
  assign _033_[2] = rd_addr[2];
  assign _034_[2] = rd_addr[2];
  assign _035_[2] = rd_addr[2];
  assign _036_[2] = rd_addr[2];
  assign _037_[2] = rd_addr[2];
  assign _038_[2] = rd_addr[2];
  assign _039_[2] = rd_addr[2];
  assign _040_[2] = rd_addr[2];
  assign _041_[2] = rd_addr[2];
  assign _042_[2] = rd_addr[2];
  assign _044_[2] = rd_addr[2];
  assign _045_[2] = rd_addr[2];
  assign _047_[2] = rd_addr[2];
  assign _048_[2] = rd_addr[2];
  assign _049_[1:0] = { wr_addr[1], wr_addr[2] };
  assign rgray[3] = rd_addr[3];
  assign wr_addr[3] = wgray[3];
endmodule
